/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSMenuItem.h"

@interface _MenuItemThatDoesNotRetainRepresentedObject : NSMenuItem
{
    id _representedObject;
}

- (id)representedObject;
- (void)setRepresentedObject:(id)fp8;

@end

