/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import <Foundation/Foundation.h>

@class AuthScheme, MailAccount, NSButton, NSPopUpButton, NSTextField, NSView, SpecialMailboxes;

@interface AccountDetails : NSObject
{
    NSView *_detailView;
    NSButton *_enableAccountCheckbox;
    NSTextField *_directory;
    NSButton *_chooseDirectoryButton;
    NSTextField *_portNumberField;
    NSButton *_autoFetch;
    NSButton *_sslSwitch;
    NSPopUpButton *_authenticationPopup;
    NSTextField *_domainLabel;
    NSTextField *_domainField;
    SpecialMailboxes *_specialMailboxes;
    MailAccount *_account;
    AuthScheme *_authScheme;
}

+ (id)accountDetailsForAccountClass:(Class)fp8;
+ (id)accountDetailsNibName;
- (void)_specialMailboxesDidChange:(id)fp8;
- (void)_updateDomainUI;
- (Class)accountClass;
- (id)accountPath;
- (void)accountPathDialogDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (void)authenticationChanged:(id)fp8;
- (void)dealloc;
- (id)detailView;
- (void)didDisplayTabViewItem:(id)fp8;
- (id)init;
- (BOOL)isAccountInformationDirty:(id)fp8;
- (void)openAccountPathDialog:(id)fp8;
- (void)setAccountPath:(id)fp8;
- (void)setUIElementsEnabled:(BOOL)fp8;
- (void)setupAccountFromValuesInSpecialMailboxesUI:(id)fp8;
- (void)setupAccountFromValuesInUI:(id)fp8 forValidation:(BOOL)fp12;
- (id)setupSpecialMailboxesUIFromValuesInAccount:(id)fp8;
- (void)setupUIFromValuesInAccount:(id)fp8;
- (void)sslChanged:(id)fp8;
- (BOOL)userWantsAccountActive;

@end

