/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import <Message/Account.h>

@interface Account (Applescript)
- (id)accountName;
- (id)accountPassword;
- (int)accountType;
- (int)customAuthentication;
- (id)loginName;
- (id)serverName;
- (void)setAccountName:(id)fp8;
- (void)setAccountPassword:(id)fp8;
- (void)setCustomAuthentication:(int)fp8;
- (void)setLoginName:(id)fp8;
- (void)setServerName:(id)fp8;
@end

