/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableSet;

@interface ActivityMonitorMultiTarget : NSObject
{
    id _primaryTarget;
    NSMutableSet *_allTargets;
}

- (BOOL)addActivityTarget:(id)fp8;
- (id)allTargets;
- (void)dealloc;
- (id)displayName;
- (id)primaryTarget;
- (BOOL)removeActivityTarget:(id)fp8;
- (void)setPrimaryTarget:(id)fp8;

@end

