/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "EmailImporter.h"

@class NSMutableArray;

@interface ApplescriptEmailImporter : EmailImporter
{
    NSMutableArray *_mailboxArray;
}

+ (id)explanatoryText;
- (id)dataForMessageString:(id)fp8;
- (void)dealloc;
- (void)importFinished;
- (id)messageSourceForMessage:(id)fp8;
- (id)prepareForImport;
- (void)prepareImportArray;
- (void)processMessageViaApplescript:(int)fp8 url:(id)fp12 currentMailbox:(id)fp16;
- (void)readMailbox:(id)fp8 intoURL:(id)fp12;
- (id)scriptName;
- (id)statusLine;
- (id)subMailboxes:(id)fp8;
- (BOOL)topLevelMailboxes;

@end

