/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "AttachmentManager.h"

@interface AttachmentManager (DiskImageSupport)
- (void)_checkDiskImageFileAtPath:(id)fp8 privately:(BOOL)fp12 didEndSelector:(SEL)fp16 contextInfo:(id)fp20;
- (void)_reallyCheckDiskImageFileAtPath:(id)fp8 privately:(BOOL)fp12 didEndSelector:(SEL)fp16 contextInfo:(id)fp20;
@end

