/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

@class IMAPFetchResult, NSArray, NSDictionary, NSString;

struct EnrichedState {
    unsigned int excerptLevel:8;
    unsigned int alignment:4;
    unsigned int bold:1;
    unsigned int italic:1;
    unsigned int fixed:1;
    unsigned int underline:1;
    unsigned int fontDelta:16;
    id fontFamily;
    id color;
};

struct KClientPrincipalOpaque;

struct KClientSessionOpaque;

struct NtlmGenerator;

struct OpaqueSecCertificateRef;

struct OpaqueSecKeychainItemRef;

struct OpaqueSecPolicyRef;

struct OpaqueSecTrustRef;

struct _CommandStackEntry {
    struct {
    } *_field1;
    id _field2;
};

struct _MessageSortingInformation {
    char _field1;
    char _field2;
    id _field3;
};

struct _NSMapTable;

struct _NSPoint {
    float _field1;
    float _field2;
};

struct _NSRange {
    unsigned int location;
    unsigned int length;
};

struct _NSRect {
    struct _NSPoint _field1;
    struct _NSSize _field2;
};

struct _NSSize {
    float _field1;
    float _field2;
};

struct _NSZone;

struct __CFArray;

struct __CFDictionary;

struct __CFReadStream;

struct __CFSet;

struct __CFString;

struct __CFTree;

struct __CFWriteStream;

struct __MDQuery;

struct __SCDynamicStore;

struct sqlite3;

struct sqlite3_stmt;

typedef struct {
    int version;
    int count;
    int timeStamp;
    float tocHeight;
    unsigned int sortOrder;
    unsigned int sortedAscending;
    int unused1;
    int unused2;
} CDAnonymousStruct1;

typedef struct {
    unsigned int _field1;
    unsigned int _field2;
    char _field3;
    char _field4;
} CDAnonymousStruct6;

typedef struct {
    unsigned int colorHasBeenEvaluated:1;
    unsigned int colorWasSetManually:1;
    unsigned int redColor:8;
    unsigned int greenColor:8;
    unsigned int blueColor:8;
    unsigned int loadingBody:1;
    unsigned int unused:5;
} CDAnonymousStruct3;

typedef struct {
    id _field1;
    id _field2;
    char _field3;
    id _field4;
    id _field5;
    id _field6;
    id _field7;
    unsigned int _field8;
    id _field9;
    unsigned int _field10;
} CDAnonymousStruct2;

typedef struct {
    unsigned int _field1;
    unsigned int _field2;
} CDAnonymousStruct9;

typedef struct {
    unsigned short buffer[64];
    struct __CFString *theString;
    unsigned short *directBuffer;
    struct {
        int location;
        int length;
    } rangeToBuffer;
    int bufferedRangeStart;
    int bufferedRangeEnd;
} CDAnonymousStruct11;

typedef struct {
    id _field1;
    id _field2;
    char _field3;
    id _field4;
    id _field5;
    id _field6;
    id _field7;
    unsigned int _field8;
    id _field9;
} CDAnonymousStruct10;

typedef struct {
    id _field1;
    id _field2;
    struct __CFDictionary *_field3;
    struct __CFDictionary *_field4;
    struct __CFDictionary *_field5;
    unsigned int _field6;
    unsigned int _field7;
    int _field8;
    id _field9;
} CDAnonymousStruct12;

typedef struct {
    int _field1;
    id _field2;
    id _field3;
    unsigned int _field4;
} CDAnonymousStruct7;

typedef struct {
    id _field1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :2;
} CDAnonymousStruct5;

typedef struct {
    unsigned int isRich:1;
    unsigned int isHTML:1;
    unsigned int hasTemporaryUid:1;
    unsigned int partsHaveBeenCached:1;
    unsigned int isPartial:1;
    unsigned int hasCustomEncoding:1;
    unsigned int reserved:26;
} CDAnonymousStruct4;

typedef struct {
    unsigned int count;
    unsigned long long size;
} CDAnonymousStruct8;

union _IMAPResponseData {
    struct {
        int responseCode;
        id responseInfoAndOrUserData;
    } basic;
    NSArray *capabilities;
    unsigned int number;
    NSArray *flags;
    struct {
        NSString *mailboxName;
        NSDictionary *entries;
    } status;
    NSArray *searchResults;
    struct {
        unsigned long mailboxAttributes;
        id separatorAndOrMboxName;
    } list;
    struct {
        unsigned long number;
        NSArray *items;
    } fetch;
    struct {
        NSString *mailboxName;
        NSArray *quotaRootNames;
    } quotaRoot;
    struct {
        NSString *quotaRootName;
        NSArray *quotas;
    } quota;
    struct {
        NSString *uids;
        IMAPFetchResult *flagsFetchResult;
        unsigned int change:1;
    } uidFlags;
    struct {
        NSString *name;
        NSArray *parameters;
    } other;
};

