/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import <Foundation/Foundation.h>

@class NSData, _NSSocket;

@interface Connection : NSObject
{
    id _securityLayer;
    _NSSocket *_socket;
    char *_buffer;
    int _bufferRemainingBytes;
    unsigned int _bufferStart;
    unsigned int _bufferLength;
    NSData *_logData;
}

+ (void)initialize;
+ (id)logActivityOnHosts;
+ (id)logActivityOnPorts;
+ (BOOL)logAllSocketActivity;
+ (void)setLogActivityOnHosts:(id)fp8;
+ (void)setLogActivityOnPorts:(id)fp8;
+ (void)setLogAllSocketActivity:(BOOL)fp8;
- (void *)_socket;
- (BOOL)authenticateUsingAccount:(id)fp8;
- (BOOL)authenticateUsingAccount:(id)fp8 authenticator:(id)fp12;
- (id)authenticationMechanisms;
- (id)capabilities;
- (BOOL)connectUsingAccount:(id)fp8;
- (void)dealloc;
- (void)disconnect;
- (void)finalize;
- (BOOL)isValid;
- (BOOL)readBytesIntoData:(id)fp8 desiredLength:(unsigned int)fp12;
- (BOOL)readLineIntoData:(id)fp8;
- (BOOL)startTLSForAccount:(id)fp8;
- (BOOL)writeData:(id)fp8;
- (BOOL)writeData:(id)fp8 dontLogBytesInRange:(struct _NSRange)fp12;

@end

