/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSObject.h"

@class NSButton, NSImageView, NSMutableArray, NSMutableDictionary, NSProgressIndicator, NSTableView, NSTextField, NSTextView;

@interface ConnectionDoctor : NSObject
{
    NSTableView *_tableView;
    NSImageView *_internetStatusIndicator;
    NSProgressIndicator *_internetStatusProgressIndicator;
    NSTextField *_internetStatusField;
    NSButton *_checkStatusButton;
    NSButton *_assistMeButton;
    NSTextView *_ispInfoField;
    NSMutableArray *_accounts;
    NSMutableDictionary *_progressIndicators;
    NSMutableDictionary *_statusMessages;
    NSMutableDictionary *_results;
    struct __CFNetDiagnostic *netDiagnostics;
}

+ (id)sharedInstance;
- (void)_checkAccountStatus;
- (void)_updateConnectionStatusWithInfo:(id)fp8;
- (void)assistMeClicked:(id)fp8;
- (void)awakeFromNib;
- (void)checkAccountStatusFinishedWithResult;
- (void)checkAccounts:(id)fp8;
- (void)checkInternetStatus;
- (void)checkInternetStatusFinishedWithResult:(id)fp8;
- (void)dealloc;
- (void)doubleClickAction:(id)fp8;
- (int)numberOfRowsInTableView:(id)fp8;
- (void)show;
- (id)tableView:(id)fp8 objectValueForTableColumn:(id)fp12 row:(int)fp16;
- (void)tableView:(id)fp8 willDisplayCell:(id)fp12 forTableColumn:(id)fp16 row:(int)fp20;
- (void)tableViewSelectionDidChange:(id)fp8;

@end

