/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSObject.h"

@class NSData;

@interface DataScanner : NSObject
{
    NSData *myData;
    unsigned int myLocation;
}

+ (id)scannerWithData:(id)fp8;
- (BOOL)byteAtScanLocation;
- (id)data;
- (void)dealloc;
- (void)finalize;
- (void)incrementLocation;
- (id)initWithData:(id)fp8;
- (BOOL)isAtEnd;
- (id)nextTokenWithPunctuation:(id)fp8;
- (BOOL)scanByte:(char *)fp8;
- (BOOL)scanBytesFromSet:(id)fp8 intoData:(id *)fp12;
- (BOOL)scanCString:(const char *)fp8 intoData:(id *)fp12;
- (BOOL)scanData:(id)fp8 intoData:(id *)fp12;
- (BOOL)scanInt:(int *)fp8;
- (unsigned int)scanLocation;
- (BOOL)scanUpToBytesFromSet:(id)fp8 intoData:(id *)fp12;
- (BOOL)scanUpToCString:(const char *)fp8 intoData:(id *)fp12;
- (BOOL)scanUpToData:(id)fp8 intoData:(id *)fp12;
- (void)setData:(id)fp8;
- (void)setScanLocation:(unsigned int)fp8;

@end

