/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSPopUpButton.h"

@class NSArray, NSURL;

@interface DefaultApplicationPopUpButton : NSPopUpButton
{
    NSURL *_appURL;
    int _index;
    NSArray *_schemes;
}

- (int)addItemToPopup:(id)fp8;
- (void)configurePopUpForURLSchemes:(id)fp8 usingExampleURLString:(id)fp12;
- (id)copyDefaultURLForScheme:(id)fp8;
- (id)imageForURL:(id)fp8;
- (id)mainScheme;
- (void)populateSchemeHandlerPopupWithURL:(id)fp8;
- (void)selectDefaultMailClientAtIndex:(int)fp8;
- (void)selectItemInPopup:(id)fp8;
- (void)selectNewAppSelected:(id)fp8;
- (void)setHandler:(id)fp8 forScheme:(id)fp12;
- (void)setNewApplication;
- (void)sheetDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;

@end

