/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSObject.h"

@class ISS_DMMemberAccount, iToolsAccount;

@interface DocMacAliasUpdater : NSObject
{
    iToolsAccount *_account;
    ISS_DMMemberAccount *_dmAccount;
    id _delegate;
    int _state;
}

- (void)_transactionDidFinishWithError:(id)fp8;
- (id)account;
- (void)dealloc;
- (id)delegate;
- (void)fetchIfModifiedSince:(id)fp8;
- (id)initWithIToolsAccount:(id)fp8;
- (void)setDelegate:(id)fp8;
- (int)state;
- (void)transactionAborted:(id)fp8;
- (void)transactionHadError:(id)fp8;
- (void)transactionSuccessful:(id)fp8;

@end

