/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "WebMessageController.h"

@interface EditingWebMessageController : WebMessageController
{
}

- (BOOL)considerBaseURLsInternal;
- (BOOL)scrollVerticallyBy:(float)fp8;
- (void)setMainFrameDocumentView:(id)fp8;
- (float)verticalPageScrollDistance;

@end

