/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSObject.h"

@class NSPanel, NSScrollView, NSTextField, SFCertificateView;

@interface EncryptionErrorPanelController : NSObject
{
    NSPanel *panel;
    SFCertificateView *certificateView;
    NSTextField *titleField;
    NSTextField *messageField;
    NSScrollView *scrollView;
}

- (void)endSheet:(id)fp8;
- (void)runModalForError:(id)fp8 certificate:(struct OpaqueSecCertificateRef *)fp12 emailAddress:(id)fp16 modalForWindow:(id)fp20;
- (void)sheetEnded:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;

@end

