/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import <Message/IMAPAccount.h>

@interface ExchangeAccount : IMAPAccount
{
}

+ (id)accountTypeString;
+ (id)activeDirectoryEmailAddress;
+ (id)activeDirectoryFullName;
+ (id)activeDirectoryPassword;
+ (id)activeDirectoryUser;
+ (id)exchangeServer;
+ (id)outlookWebAccessServer;
+ (void)setActiveDirectoryPassword:(id)fp8;
+ (void)setActiveDirectoryUser:(id)fp8;
+ (void)setExchangeServer:(id)fp8;
+ (void)setOutlookWebAccessServer:(id)fp8;
+ (BOOL)usingActiveDirectory;
- (id)_defaultSpecialMailboxNameForType:(int)fp8;
- (void)_filterMailboxList:(id)fp8 forMailboxWithPath:(id)fp12 iisServer:(id)fp16;
- (id)_nonMailboxChildrenOfMailboxWithPath:(id)fp8 iisServer:(id)fp12;
- (void)_removePasswordInKeychain;
- (BOOL)_syncOnly_defaultValueForShouldStoreJunkOnServer;
- (Class)connectionClass;
- (id)defaultsDictionary;
- (void)filterMailboxList:(id)fp8 forMailbox:(id)fp12 options:(int)fp16;
- (void)handleOpenMailboxError:(id)fp8;
- (id)hostname;
- (id)passwordFromKeychain;
- (id)passwordFromStoredUserInfo;
- (void)setHostname:(id)fp8;
- (void)setPassword:(id)fp8;
- (void)setPasswordInKeychain:(id)fp8;
- (void)setUsername:(id)fp8;
- (BOOL)storeDraftsOnServer;
- (BOOL)storeJunkOnServer;
- (BOOL)storeSentMessagesOnServer;
- (void)updateFromSyncedDictionary:(id)fp8;
- (id)username;

@end

