/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSPopUpButtonCell.h"

@interface FlatPopUpButtonCell : NSPopUpButtonCell
{
}

+ (void)loadCapGraphics;
- (void)_drawWithFrame:(struct _NSRect)fp8 inView:(id)fp24;
- (void)drawWithFrame:(struct _NSRect)fp8 inView:(id)fp24;
- (struct _NSRect)titleRectForBounds:(struct _NSRect)fp8;

@end

