/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSObject.h"

@class NSAttributedString, NSMutableAttributedString, NSMutableString, NSString;

@interface FormatFlowedWriter : NSObject
{
    NSAttributedString *_inputAttrString;
    NSString *_inputString;
    unsigned int _encoding;
    NSMutableString *_outputString;
    unsigned int _addedTrailingSpaces:1;
    unsigned int _quoteLevel:31;
    struct _NSRange _paraRange;
    NSMutableString *_lineString;
    NSMutableAttributedString *_attrString;
}

+ (id)newWithAttributedString:(id)fp8 encoding:(unsigned long)fp12;
- (unsigned int)_findLineBreakInRange:(struct _NSRange)fp8 maxCharWidthCount:(unsigned int)fp16;
- (void)_outputQuotedParagraph;
- (BOOL)addedTrailingSpaces;
- (void)dealloc;
- (id)outputString;

@end

