/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSPreferencesModule.h"

@class DefaultApplicationPopUpButton, NSButton, NSPopUpButton, NSString, NSWindow, SoundPopUpButton;

@interface GeneralPreferences : NSPreferencesModule
{
    NSPopUpButton *fetchFrequencyPopup;
    SoundPopUpButton *newMailSoundPopup;
    NSButton *playMailSoundsCheckbox;
    NSString *soundFile;
    DefaultApplicationPopUpButton *defaultMailClientPopUp;
    NSButton *indexDecryptedMessagesButton;
    NSPopUpButton *downloadFolderPopup;
    NSPopUpButton *addInvitationsPopup;
    NSPopUpButton *attachmentDeletionPopup;
    NSButton *syncOtherStuffButton;
    NSButton *syncAccountsButton;
    NSWindow *dotMacSyncingWindow;
}

- (void)_addInvitationsBehaviorChanged:(id)fp8;
- (void)_openPanelSheetDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (void)_updateAddInvitationsPopup;
- (void)addInvitationsPopupChanged:(id)fp8;
- (void)asynchronouslyTellSyncServicesToEnableSyncing:(BOOL)fp8 forDataType:(int)fp12;
- (void)attachmentDeletionPopupChanged:(id)fp8;
- (void)awakeFromNib;
- (void)cancelDotMacSheet:(id)fp8;
- (void)chooseNewDownloadFolder:(id)fp8;
- (void)dealloc;
- (void)didTellSyncServicesToEnableSyncingForDataType:(id)fp8 success:(id)fp12;
- (void)dotMacSyncingSheetDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (void)fetchFrequencyChanged:(id)fp8;
- (void)indexDecryptedMessagesButtonClicked:(id)fp8;
- (void)initializeFromDefaults;
- (BOOL)isResizable;
- (void)newMailSoundDidChange:(id)fp8;
- (void)playSoundsClicked:(id)fp8;
- (void)showDotMacSystemPrefs:(id)fp8;
- (void)showMoreInfoAboutDotMac:(id)fp8;
- (void)synchronouslyTellSyncServicesToEnableSyncing:(id)fp8 forDataType:(id)fp12;
- (void)syncingPrefChanged:(id)fp8;
- (id)titleForIdentifier:(id)fp8;
- (id)titleForSoundFile:(id)fp8;
- (id)windowTitle;

@end

