/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import <Message/SASLAuthenticator.h>

#import "SASLSecurityLayerProtocol.h"

@interface GSSAPIAuthenticator : SASLAuthenticator <SASLSecurityLayer>
{
    unsigned int _maxBufferSize:16;
    unsigned int _substate:2;
    unsigned int _securityLevel:4;
    void *_gssContext;
    void *_targetName;
    unsigned int _qopState;
    int _requestConfidentiality;
}

+ (id)allocWithZone:(struct _NSZone *)fp8;
- (id)createDecryptedDataForBytes:(const char *)fp8 length:(unsigned int)fp12;
- (id)createEncryptedDataForBytes:(const char *)fp8 length:(unsigned int)fp12;
- (unsigned int)encryptionBufferSize;
- (id)responseForServerData:(id)fp8;
- (id)securityLayer;
- (void)setAuthenticationState:(int)fp8;

@end

