/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSTextFieldCell.h"

@class NSImage;

@interface ImageTextFieldAlertTrackingCell : NSTextFieldCell
{
    NSImage *_image;
    struct MVAlertStateImageNames *_alertImages;
    BOOL _isRolledOver;
    BOOL _isClickedOn;
    BOOL _useLargeIconsIfPossible;
    BOOL isSelected;
    BOOL isOffline;
    int _progressIndicatorType;
    struct _NSRect _trackingRect;
    id item;
    int progressIndicatorImageIndex;
    float progressIndicatorPercentDone;
    int unreadCount;
    int _alertState;
}

- (void)_sendActionFrom:(id)fp8;
- (id)accessibilityAttributeNames;
- (id)accessibilityAttributeValue:(id)fp8;
- (int)alertState;
- (struct _NSSize)cellSize;
- (BOOL)continueTracking:(struct _NSPoint)fp8 at:(struct _NSPoint)fp16 inView:(id)fp24;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)dealloc;
- (void)drawInteriorWithFrame:(struct _NSRect)fp8 inView:(id)fp24;
- (void)drawWithFrame:(struct _NSRect)fp8 inView:(id)fp24;
- (void)editWithFrame:(struct _NSRect)fp8 inView:(id)fp24 editor:(id)fp28 delegate:(id)fp32 event:(id)fp36;
- (BOOL)hasAlertImages;
- (id)highlightColorWithFrame:(struct _NSRect)fp8 inView:(id)fp24;
- (id)image;
- (id)initImageCell:(id)fp8;
- (BOOL)isOffline;
- (BOOL)isRolledOver;
- (void)selectWithFrame:(struct _NSRect)fp8 inView:(id)fp24 editor:(id)fp28 delegate:(id)fp32 start:(int)fp36 length:(int)fp40;
- (void)setAlertState:(int)fp8;
- (void)setAlertStateImages:(struct MVAlertStateImageNames)fp8 forAlertState:(int)fp40;
- (void)setAllowLargeIcons:(BOOL)fp8;
- (void)setImage:(id)fp8;
- (void)setIsOffline:(BOOL)fp8;
- (void)setIsRolledOver:(BOOL)fp8;
- (void)setItem:(id)fp8;
- (void)setUnreadCount:(int)fp8;
- (void)setUpTextAttributes;
- (void)showProgressIndicator:(BOOL)fp8 percentDone:(float)fp12;
- (BOOL)trackMouse:(id)fp8 inRect:(struct _NSRect)fp12 ofView:(id)fp28 untilMouseUp:(BOOL)fp32;
- (struct _NSRect)trackingRectForCellFrame:(struct _NSRect)fp8 item:(id)fp24;

@end

