/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import <Message/IMAPDownload.h>

@class NSMutableArray;

@interface IMAPCompoundDownload : IMAPDownload
{
    NSMutableArray *_subdownloads;
}

- (void)addCommandsToPipeline:(id)fp8 withCache:(id)fp12;
- (void)addSubdownload:(id)fp8;
- (void)dealloc;
- (unsigned long)expectedLength;
- (BOOL)isComplete;
- (void)processResults;
- (void)removeSubdownload:(id)fp8;
- (id)subdownloads;

@end

