/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import <Message/MessageStore.h>

#import "NSCodingProtocol.h"

@class NSConditionLock, NSDate, NSMutableArray, NSMutableDictionary, NSSet, NSString;

@interface IMAPStore : MessageStore <NSCoding>
{
    NSMutableArray *_unsolicitedResponses;
    NSString *_statusMessageFormat;
    int _statusMessageCount;
    int _statusMessageMaximum;
    int _activityMonitorKey;
    unsigned int _numberOfFirstNewMessage;
    unsigned int _synchronizationState:3;
    unsigned int _supportsCustomPermanentFlags:1;
    unsigned int _supportsJunkFlag:1;
    unsigned int _supportsDollarJunkFlag:1;
    unsigned int _supportsNotJunkFlag:1;
    unsigned int _supportsDollarNotJunkFlag:1;
    unsigned int _supportsForwardedFlag:1;
    unsigned int _supportsDollarForwardedFlag:1;
    unsigned int _updatingCache:1;
    unsigned int _updateIndex:1;
    unsigned int _updateEverythingElse:1;
    unsigned int _reserved:19;
    NSString *_mailboxName;
    NSConditionLock *_synchronizationStateLock;
    NSMutableDictionary *_headersForMessagesBeingRouted;
    NSSet *_cachedContents;
    NSDate *_cachedDirModDate;
    NSMutableDictionary *_recentFlagChangesByMessage;
}

+ (BOOL)createEmptyStoreForPath:(id)fp8;
+ (void)initialize;
+ (BOOL)storeAtPathIsWritable:(id)fp8;
- (void)_addOfflineTransferMessages:(id)fp8;
- (BOOL)_allMessagesHaveDateReceived;
- (void)_cacheAttachmentPartsForMessages:(id)fp8 cacheDirectoryContents:(id)fp12;
- (id)_cacheDirectoryContents;
- (id)_cacheDirectoryContentsCheckingModDate:(BOOL)fp8;
- (void)_cacheMessageBodiesAndUpdateIndex:(id)fp8;
- (void)_cacheMessageBodiesAndUpdateIndex:(id)fp8 cacheDirectoryContents:(id)fp12;
- (void)_cacheMessageBodiesAsynchronously:(id)fp8;
- (void)_cacheMessageBodiesToDisk:(id)fp8 cacheDirectoryContents:(id)fp12;
- (void)_copyCacheFilesForMessage:(id)fp8 fromDirectory:(id)fp12 toBasePath:(id)fp16;
- (void)_copyDataFrom:(id)fp8;
- (BOOL)_copyMessages:(id)fp8 toStore:(id)fp12 newMessages:(id)fp16;
- (id)_copyOfflineTransferMessage:(id)fp8 withUid:(unsigned int)fp12;
- (id)_createDataFromMimePart:(id)fp8 threshold:(unsigned int)fp12;
- (id)_dataForMessage:(id)fp8 readHeadersOnly:(BOOL)fp12;
- (int)_doAppend:(CDAnonymousStruct10 *)fp8;
- (id)_fetchBodyDataForMessage:(id)fp8 andHeaderDataIfReadilyAvailable:(id *)fp12;
- (id)_fetchDataForMimePart:(id)fp8 keepInMemory:(BOOL)fp12 writeToDisk:(BOOL)fp16;
- (id)_fetchHeaderDataForMessage:(id)fp8;
- (void)_fetchMessageIDHeaderForMessages:(id)fp8;
- (void)_invalidate;
- (id)_messageForTemporaryUid:(unsigned int)fp8;
- (id)_messageForUid:(unsigned int)fp8;
- (int)_numberOfNewMessagesWaitingOnConnection:(id)fp8;
- (id)_preferredOrderForFetchingMessageBodies:(id)fp8;
- (void)_processUnsolicitedResponsesUsingConnection:(id)fp8;
- (void)_retrieveNewMessages;
- (void)_retrieveNewMessagesInUIDRange:(CDAnonymousStruct9)fp8 intoArray:(id)fp16 statusFormat:(id)fp20 usingConnection:(id)fp24;
- (void)_setFlagsFromDictionary:(id)fp8 forMessages:(id)fp12;
- (void)_setInternalDateForMessages:(id)fp8;
- (void)_setNeedsAutosave;
- (BOOL)_shouldCallCompactWhenClosing;
- (void)_synchronizationCompleted;
- (BOOL)_synchronizeUidRange:(CDAnonymousStruct9)fp8 newMessages:(id)fp16 usingConnection:(id)fp20;
- (void)_synchronizeWithServerUsingConnection:(id)fp8;
- (void)_synchronouslyStoreFlagsFromDictionary:(id)fp8 forMessages:(id)fp12;
- (id)_uidsForMessages:(id)fp8;
- (void)_updateCacheDirectoryAndIndexDoTheseFirst:(id)fp8;
- (BOOL)allowsAppend;
- (int)appendMessages:(id)fp8 unsuccessfulOnes:(id)fp12 newMessageIDs:(id)fp16 newMessages:(id)fp20;
- (BOOL)canCompact;
- (BOOL)canRebuild;
- (id)colorForMessage:(id)fp8;
- (id)connection;
- (void)connection:(id)fp8 didReceiveResponse:(id)fp12 forCommand:(CDAnonymousStruct7 *)fp16;
- (BOOL)connection:(id)fp8 shouldHandleUntaggedResponse:(id)fp12 forCommand:(CDAnonymousStruct7 *)fp16;
- (void)connectionDidDisconnect:(id)fp8;
- (id)dataForMimePart:(id)fp8;
- (void)dealloc;
- (void)encodeWithCoder:(id)fp8;
- (void)fetchSynchronously;
- (void)finalize;
- (id)fullBodyDataForMessage:(id)fp8;
- (BOOL)hasCachedDataForMimePart:(id)fp8;
- (BOOL)hasValidCacheFileForMessage:(id)fp8;
- (BOOL)hasValidCacheFileForUid:(int)fp8;
- (id)headersForMessage:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (id)initWithMailboxUid:(id)fp8 readOnly:(BOOL)fp12;
- (id)mailboxName;
- (id)messageForMessageID:(id)fp8;
- (void)openSynchronouslyUpdatingMetadata:(BOOL)fp8;
- (void)removeCachedFiles:(id)fp8;
- (id)routeMessages:(id)fp8;
- (id)setFlagsFromDictionary:(id)fp8 forMessages:(id)fp12;
- (BOOL)setPreferredEncoding:(unsigned long)fp8 forMessage:(id)fp12;
- (void)setUid:(unsigned int)fp8 forMessageWithTemporaryUid:(unsigned int)fp12;
- (void)startSynchronization;
- (int)undoAppendOfMessageIDs:(id)fp8;
- (void)updateMetadata;
- (void)waitForSynchronizationToComplete;
- (void)writeUpdatedMessageDataToDisk;

@end

