/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import <Message/SizeEngine.h>

@class NSMutableArray, NSMutableDictionary;

@interface IMAPSizeEngine : SizeEngine
{
    unsigned int _quotaStatus:3;
    struct __CFDictionary *_usageByMailboxUid;
    NSMutableDictionary *_mailboxesByQuotaRoot;
    NSMutableDictionary *_usageByQuotaName;
    NSMutableArray *_mailboxesToSize;
    NSMutableArray *_quotasToFetch;
}

- (void)_changeQuotaRoots:(id)fp8 forMailboxUid:(id)fp12;
- (void)_changeQuotas:(id)fp8 forQuotaRootName:(id)fp12;
- (BOOL)_changeUsageInfo:(CDAnonymousStruct8 *)fp8 forMailboxUid:(id)fp12 refetchQuotas:(BOOL)fp16;
- (void)_getSize:(CDAnonymousStruct8 *)fp8 forMailboxUid:(id)fp12;
- (void)_mailbox:(id)fp8 didRemoveUsage:(id)fp12 fromQuotaRoots:(id)fp16;
- (void)_mailboxBecameInvalid:(id)fp8;
- (void)_mailboxChanged:(id)fp8;
- (void)_mailboxSizeChanged:(id)fp8;
- (BOOL)_prepareToRefresh;
- (void)_refetchListing:(id)fp8;
- (void)_runWorkerThread;
- (BOOL)_shouldStartWorkerThread;
- (void)_sizeChangedForMailboxUid:(id)fp8;
- (BOOL)connection:(id)fp8 shouldHandleUntaggedResponse:(id)fp12 forCommand:(CDAnonymousStruct7 *)fp16;
- (void)dealloc;
- (void)finalize;
- (void)handleMailboxSizeChanged:(id)fp8;
- (id)initWithIMAPAccount:(id)fp8;
- (BOOL)mailbox:(id)fp8 usesQuotaName:(id)fp12;
- (id)mutableCopyOfMailboxesForQuotaName:(id)fp8;
- (id)quotaNames;
- (int)quotaStatus;
- (id)usageForMailbox:(id)fp8;
- (id)usageForQuotaName:(id)fp8;

@end

