/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import <Message/IMAPMailboxSyncEngine.h>

@interface IMAPMailboxSyncEngine (Internal)
- (void)_go;
- (void)_notifyBackgroundFetchCompleted;
@end

