/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "Quota.h"

@class NSButton, NSMutableArray, NSPopUpButton, NSProgressIndicator, NSTableView, NSTextField, NSView, QuotaBar;

@interface IMAPQuota : Quota
{
    NSPopUpButton *_quotaPopup;
    NSTextField *_quotaPopupLabel;
    NSView *_quotaContainerView;
    QuotaBar *_quotaBar;
    NSTextField *_usageField;
    NSTextField *_capacityField;
    NSTableView *_quotaTable;
    NSProgressIndicator *_progressIndicator;
    NSTextField *_progressField;
    NSTextField *_statusField;
    NSButton *_showMessagesButton;
    NSMutableArray *_mailboxes;
    struct _QuotaSimpleSortDescriptor _simpleSortDescs[3];
}

- (void)_showMessagesInMailboxAtRow:(int)fp8;
- (void)dealloc;
- (void)doubleClickedMailbox:(id)fp8;
- (id)initWithIMAPAccount:(id)fp8;
- (int)numberOfRowsInTableView:(id)fp8;
- (void)quotaPopupChanged:(id)fp8;
- (void)showMessages:(id)fp8;
- (id)tableView:(id)fp8 objectValueForTableColumn:(id)fp12 row:(int)fp16;
- (void)tableView:(id)fp8 sortDescriptorsDidChange:(id)fp12;
- (void)tableView:(id)fp8 willDisplayCell:(id)fp12 forTableColumn:(id)fp16 row:(int)fp20;
- (void)tableViewSelectionDidChange:(id)fp8;

@end

