/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "IMAPQuota.h"

@interface IMAPQuota (Internal)
- (void)_engineStatusChanged:(id)fp8;
- (id)_iconForMailboxUid:(id)fp8;
- (id)_nameForMailboxUid:(id)fp8;
- (void)_resortMailboxes;
- (id)_selectedQuotaName;
- (id)_stringForSize:(unsigned long long)fp8 andCount:(unsigned long)fp16 isCapacity:(BOOL)fp20;
- (void)_syncSortDescriptors;
- (void)_updateMailbox:(id)fp8 usage:(id)fp12;
- (void)_updateQuotaBarWithSize:(unsigned long long)fp8 maxSize:(unsigned long long)fp16 count:(unsigned long)fp24 maxCount:(unsigned long)fp28;
- (void)_updateQuotaPopupWithQuotaNames:(id)fp8;
- (void)_updateStatusField;
- (void)_updateUIForQuotaName:(id)fp8 updateTable:(BOOL)fp12;
- (void)engineDidFinish;
- (void)engineDidStart;
- (void)engineUpdated:(id)fp8;
- (unsigned int)numberOfSortDescriptors;
- (const struct _QuotaSimpleSortDescriptor *)sortDescriptorAtIndex:(unsigned int)fp8;
- (void)updateProgress:(id)fp8;
@end

