/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSObject.h"

@class NSConditionLock, NSMutableArray;

@interface InvocationQueue : NSObject
{
    NSMutableArray *_items;
    unsigned int _maxThreads:16;
    unsigned int _numThreads:16;
    double _threadRecycleTimeout;
    NSConditionLock *_threadRecycleLock;
}

- (void)_drainQueue;
- (void)addInvocation:(id)fp8;
- (void)dealloc;
- (void)finalize;
- (id)init;
- (unsigned int)invocationCount;
- (unsigned int)maxThreadCount;
- (void)removeAllItems;
- (void)setMaxThreadCount:(unsigned int)fp8;
- (void)setThreadRecycleTimeout:(double)fp8;
- (double)threadRecycleTimeout;

@end

