/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import <Message/POP3Connection.h>

@interface KPOPConnection : POP3Connection
{
}

+ (id)allocWithZone:(struct _NSZone *)fp8;
- (BOOL)authenticateUsingAccount:(id)fp8;
- (BOOL)connectUsingAccount:(id)fp8;

@end

