/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSTextAttachmentCell.h"

@class NSColor, NSImage, NSMutableAttributedString, NSString, NSView;

@interface LabelledTextAttachmentCell : NSTextAttachmentCell
{
    NSMutableAttributedString *_attrString;
    NSImage *_image;
    NSImage *_dimmedImage;
    NSColor *_highlightedColor;
    NSString *_label;
    unsigned int _linkState:2;
    unsigned int _isDisplayingLabel:1;
    float _maxWidth;
    NSView *containingView;
    struct _NSRect attachmentDrawingRect;
}

- (void)_discardDimmedImage;
- (void)_makeString;
- (struct _NSRect)_rectForImageInRect:(struct _NSRect)fp8;
- (struct _NSRect)_rectForLinkInRect:(struct _NSRect)fp8;
- (id)accessibilityActionNames;
- (id)accessibilityAttributeNames;
- (id)accessibilityAttributeValue:(id)fp8;
- (void)accessibilityPerformAction:(id)fp8;
- (id)attributedString;
- (struct _NSPoint)cellBaselineOffset;
- (struct _NSSize)cellSize;
- (void)dealloc;
- (id)dimmedImage;
- (void)drawWithFrame:(struct _NSRect)fp8 inView:(id)fp24;
- (void)drawWithFrame:(struct _NSRect)fp8 inView:(id)fp24 characterIndex:(unsigned int)fp28;
- (id)highlightedColor;
- (id)image;
- (id)initWithTextAttachment:(id)fp8;
- (BOOL)isDisplayingLabel;
- (id)label;
- (id)labelColor;
- (id)labelFont;
- (unsigned int)linkState;
- (void)resetCursorAndToolTipRect:(struct _NSRect)fp8 inView:(id)fp24;
- (void)setAttachment:(id)fp8;
- (void)setHighlightedWithColor:(id)fp8;
- (void)setImage:(id)fp8;
- (void)setIsDisplayingLabel:(BOOL)fp8;
- (void)setLabel:(id)fp8;
- (void)setLinkState:(int)fp8;
- (void)setMaxWidth:(float)fp8;
- (void)showMenu;
- (BOOL)trackLink:(id)fp8 inRect:(struct _NSRect)fp12 ofView:(id)fp28 atCharacterIndex:(int)fp32;
- (BOOL)trackMouse:(id)fp8 inRect:(struct _NSRect)fp12 ofView:(id)fp28 atCharacterIndex:(unsigned int)fp32 untilMouseUp:(BOOL)fp36;
- (BOOL)wantsToTrackMouse;
- (BOOL)wantsToTrackMouseForEvent:(id)fp8 inRect:(struct _NSRect)fp12 ofView:(id)fp28 atCharacterIndex:(unsigned int)fp32;

@end

