/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "MailAccount.h"

@class NSMutableArray;

@interface LocalAccount : MailAccount
{
    NSMutableArray *_disembodiedUids;
}

+ (id)accountTypeString;
+ (id)localAccount;
- (id)_URLScheme;
- (id)_copyMailboxUidWithParent:(id)fp8 name:(id)fp12 attributes:(unsigned int)fp16 existingMailboxUid:(id)fp20;
- (id)_infoForMatchingURL:(id)fp8;
- (BOOL)_setChildren:(id)fp8 forMailboxUid:(id)fp12;
- (void)_synchronouslyLoadListingForParent:(id)fp8;
- (BOOL)canFetch;
- (id)createMailboxWithParent:(id)fp8 name:(id)fp12;
- (id)displayName;
- (int)emptyTrashFrequency;
- (id)initWithPath:(id)fp8;
- (void)insertInMailboxes:(id)fp8 atIndex:(unsigned int)fp12;
- (BOOL)isOffline;
- (id)mailboxPathExtension;
- (id)mailboxUidForFileSystemPath:(id)fp8;
- (id)password:(BOOL)fp8;
- (id)primaryMailboxUid;
- (BOOL)renameMailbox:(id)fp8 newName:(id)fp12 parent:(id)fp16;
- (id)rootMailboxUid;
- (void)setHostname:(id)fp8;
- (void)setIsOffline:(BOOL)fp8;
- (void)setPassword:(id)fp8;
- (void)setPath:(id)fp8;
- (void)setUsername:(id)fp8;
- (BOOL)shouldAutoFetch;
- (BOOL)shouldMoveDeletedMessagesToTrash;
- (Class)storeClass;
- (id)uniqueId;

@end

