/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import <Message/SASLAuthenticator.h>

@interface LoginAuthenticator : SASLAuthenticator
{
    BOOL _justSentPassword;
}

- (BOOL)justSentPlainTextPassword;
- (id)responseForServerData:(id)fp8;
- (id)saslName;

@end

