/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "MailApp.h"

@interface MailApp (MFUserAgent) 
- (void)_runAlertPanelInMainThreadWithInfo:(struct MailAlertInfo *)fp8;
- (void)_runPasswordPanelInMainThreadWithInfo:(struct MailPasswordInfo *)fp8;
- (void)dismissNonModalAlertPanelForObject:(id)fp8;
- (id)displayStringForMailbox:(id)fp8;
- (void)downloadBigMessage:(id)fp8;
- (int)informUserOfError:(id)fp8;
- (BOOL)isTerminating;
- (BOOL)openTemporaryAttachments:(id)fp8 applicationBundle:(id)fp12;
- (BOOL)personWithEmailIsOnline:(id)fp8;
- (void)queryUserForBigMessageAction:(id)fp8 userResponse:(int *)fp12;
- (id)queryUserForPasswordWithMessage:(id)fp8 title:(id)fp12 remember:(char *)fp16;
- (BOOL)queryUserForYesNoWithMessage:(id)fp8 title:(id)fp12 yesTitle:(id)fp16 noTitle:(id)fp20;
- (BOOL)queryUserIfNeededToCreateMailbox:(id)fp8 orChooseNewMailbox:(id *)fp12;
- (id)queryUserToSelectMailbox:(id)fp8;
- (int)runAlertPanelWithTitle:(id)fp8 defaultTitle:(id)fp12 alternateTitle:(id)fp16 otherTitle:(id)fp20 message:(id)fp24;
- (void)runNonModalAlertPanelForObject:(id)fp8 withError:(id)fp12;
- (void)selectMailboxPanelDone:(id)fp8;
- (id)sharedAttachmentContextMenu;
- (BOOL)shouldInvalidateMailbox:(id)fp8;
- (BOOL)showCertificateTrustPanelForError:(id)fp8 certificates:(id)fp12;
- (void)storeBeingInvalidated:(id)fp8;
- (BOOL)wakingFromSleep;
@end

