/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "MailSegmentedCell.h"

@interface MailToolbarButtonCell : MailSegmentedCell
{
}

+ (id)buttonFillColorPattern:(int)fp8 value:(int)fp12 tint:(int)fp16 controlSize:(int)fp20;
+ (id)buttonSeparator:(int)fp8 value:(int)fp12 tint:(int)fp16 controlSize:(int)fp20;
+ (id)disabledColor;
+ (id)leftButtonCap:(int)fp8 value:(int)fp12 tint:(int)fp16 controlSize:(int)fp20;
+ (id)leftSeparator:(int)fp8 value:(int)fp12 tint:(int)fp16 controlSize:(int)fp20;
+ (float)maxImageHeightAllowedForControlSize:(int)fp8;
+ (id)menuIndicator:(int)fp8;
+ (const struct MailSegmentedCellMetrics *)metricsForControlSize:(int)fp8;
+ (id)rightButtonCap:(int)fp8 value:(int)fp12 tint:(int)fp16 controlSize:(int)fp20;
+ (id)rightSeparator:(int)fp8 value:(int)fp12 tint:(int)fp16 controlSize:(int)fp20;
+ (int)segmentedCellStyle;
- (id)accessibilitySegmentAtIndex:(int)fp8;
- (void)drawImageForSegment:(int)fp8 inFrame:(struct _NSRect)fp12 withView:(id)fp28;
- (id)toolbarItem;

@end

