/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "FilesystemEmailImporter.h"

@interface MailEmailImporter : FilesystemEmailImporter
{
}

+ (id)explanatoryText;
+ (id)name;
- (void)importMailbox:(id)fp8;
- (BOOL)isValidMailbox:(id)fp8;
- (id)pathExtension;

@end

