/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "MailApp.h"

@interface MailApp (ApplescriptViewerPreferences)
- (BOOL)downloadHTMLAttachments;
- (int)headerDetail;
- (void)setDownloadHTMLAttachments:(BOOL)fp8;
- (void)setHeaderDetail:(int)fp8;
- (void)setShouldHighlightThreads:(BOOL)fp8;
- (void)setShouldShowPresence:(BOOL)fp8;
- (void)setShouldShowUnreadMessagesInBold:(BOOL)fp8;
- (BOOL)shouldHighlightThreads;
- (BOOL)shouldShowMailboxesAtLeft;
- (BOOL)shouldShowPresence;
- (BOOL)shouldShowUnreadMessagesInBold;
@end

