/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "MailApp.h"

@interface MailApp (ApplescriptMailSorterPreferences)
- (void)insertInRules:(id)fp8;
- (void)insertInRules:(id)fp8 atIndex:(unsigned int)fp12;
- (void)removeFromRulesAtIndex:(unsigned int)fp8;
- (id)rules;
@end

