/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSToolbarItem.h"

@class NSArray;

@interface MailToolbarItem : NSToolbarItem
{
    NSArray *_segments;
    unsigned int _extraSegmentWidth;
    unsigned int _extraHorizontalPadding;
    unsigned int _borderless:1;
}

- (id)_copyOfCustomView;
- (void)_validateAsCustomItem:(id)fp8;
- (void)_validateSegment:(int)fp8 forToolbarItem:(id)fp12;
- (SEL)actionForSegment:(int)fp8;
- (BOOL)bordered;
- (void)configureForDisplayMode:(int)fp8 andSizeMode:(int)fp12;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)dealloc;
- (unsigned int)extraHorizontalPadding;
- (unsigned int)extraSegmentWidth;
- (id)imageForSegment:(int)fp8;
- (id)inactiveImageForSegment:(int)fp8;
- (id)initWithItemIdentifier:(id)fp8;
- (id)initWithItemIdentifier:(id)fp8 segments:(id)fp12 bordered:(BOOL)fp16 toolbar:(id)fp20;
- (BOOL)isEnabledForSegment:(int)fp8;
- (id)itemView;
- (id)labelForSegment:(int)fp8;
- (id)menuFormRepresentation;
- (id)paletteLabelForSegment:(int)fp8;
- (void)performActionForSegment:(int)fp8;
- (id)pressedImageForSegment:(int)fp8;
- (id)segmentAtIndex:(int)fp8;
- (unsigned int)segmentCount;
- (id)segments;
- (void)setAction:(SEL)fp8 forSegment:(int)fp12;
- (void)setEnabled:(BOOL)fp8;
- (void)setEnabled:(BOOL)fp8 forSegment:(int)fp12;
- (void)setExtraHorizontalPadding:(unsigned int)fp8;
- (void)setExtraSegmentWidth:(unsigned int)fp8;
- (void)setImage:(id)fp8 forSegment:(int)fp12;
- (void)setInactiveImage:(id)fp8 forSegment:(int)fp12;
- (void)setLabel:(id)fp8 forSegment:(int)fp12;
- (void)setPaletteLabel:(id)fp8 forSegment:(int)fp12;
- (void)setPressedImage:(id)fp8 forSegment:(int)fp12;
- (void)setTag:(int)fp8 forSegment:(int)fp12;
- (void)setTarget:(id)fp8 forSegment:(int)fp12;
- (void)setToolTip:(id)fp8 forSegment:(int)fp12;
- (int)tagForSegment:(int)fp8;
- (id)targetForSegment:(int)fp8;
- (id)toolTipForSegment:(int)fp8;
- (BOOL)usesMenuFormRepresentationInDisplayMode:(int)fp8;
- (BOOL)wantsToDrawIconInDisplayMode:(int)fp8;
- (BOOL)wantsToDrawIconIntoLabelAreaInDisplayMode:(int)fp8;
- (BOOL)wantsToDrawLabelInDisplayMode:(int)fp8;
- (BOOL)wantsToDrawLabelInPalette;

@end

