/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSView.h"

@class MailToolbarSpaceItemWithPin;

@interface MailToolbarSpace : NSView
{
    MailToolbarSpaceItemWithPin *_spaceItem;
    BOOL _inPalette;
}

- (void)drawRect:(struct _NSRect)fp8;
- (BOOL)inPalette;
- (id)initWithSize:(struct _NSSize)fp8 forSpaceItem:(id)fp16;
- (void)setInPalette:(BOOL)fp8;

@end

