/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import <Foundation/Foundation.h>

@class NSMutableArray, NSString;

@interface MailboxUid : NSObject
{
    NSString *uniqueId;
    id _accountOrPathComponent;
    unsigned int _attributes;
    void *_tree;
    NSString *pendingNameChange;
    BOOL isSmartMailbox;
    NSMutableArray *criteria;
    BOOL allCriteriaMustBeSatisfied;
    NSString *_realFullPath;
    unsigned int _numberOfGenericChildren;
}

+ (id)_smartMailboxWithIdentifier:(id)fp8 inArray:(id)fp12;
+ (void)setSmartMailboxUids:(id)fp8;
+ (id)smartMailboxUids;
+ (id)smartMailboxWithIdentifier:(id)fp8;
+ (id)smartMailboxesEnumerator;
+ (id)specialMailboxUids;
- (id)URL;
- (id)URLString;
- (id)URLStringWithAccount:(id)fp8;
- (void)_deleteChildrenWithURLsIfInvalid:(id)fp8 fullPaths:(id)fp12;
- (id)_loadUserInfo;
- (id)account;
- (id)accountRelativePath;
- (BOOL)allCriteriaMustBeSatisfied;
- (id)ancestralAccount;
- (id)applescriptAccount;
- (unsigned int)attributes;
- (id)childAtIndex:(unsigned int)fp8;
- (id)childWithName:(id)fp8;
- (int)compareWithMailboxUid:(id)fp8;
- (id)copyWithZone:(id)fp8;
- (id)criteria;
- (BOOL)criteriaAreValid:(id *)fp8;
- (id)criterion;
- (void)dealloc;
- (id)deepCopy;
- (id)depthFirstEnumerator;
- (id)description;
- (id)dictionaryRepresentation;
- (id)displayName;
- (void)finalize;
- (void)flushCriteria;
- (id)fullPath;
- (id)fullPathNonNil;
- (BOOL)hasChildren;
- (unsigned int)indexOfChild:(id)fp8;
- (int)indexToInsertChildMailboxUid:(id)fp8;
- (id)init;
- (id)initWithAccount:(id)fp8;
- (id)initWithDictionaryRepresentation:(id)fp8;
- (id)initWithMailboxUid:(id)fp8;
- (id)initWithName:(id)fp8 attributes:(unsigned int)fp12 forAccount:(id)fp16;
- (void)invalidate;
- (void)invalidateCachedNumberOfGenericChildren;
- (BOOL)isContainer;
- (BOOL)isDescendantOfMailbox:(id)fp8;
- (BOOL)isFlaggedSmartMailbox;
- (BOOL)isIndexable;
- (BOOL)isSmartMailbox;
- (BOOL)isSpecialMailboxUid;
- (BOOL)isStore;
- (BOOL)isValid;
- (id)mutableCopyOfChildren;
- (id)name;
- (unsigned int)numberOfChildren;
- (unsigned int)numberOfGenericChildren;
- (id)oldURLString;
- (id)parent;
- (id)pathRelativeToMailbox:(id)fp8;
- (id)realFullPath;
- (void)removeIndexFlagFileIfNeeded;
- (id)representedAccount;
- (void)saveUserInfo;
- (void)setAllCriteriaMustBeSatisfied:(BOOL)fp8;
- (void)setAttributes:(unsigned int)fp8;
- (BOOL)setChildren:(id)fp8;
- (void)setCriteria:(id)fp8;
- (void)setIsSmartMailbox:(BOOL)fp8;
- (void)setName:(id)fp8;
- (void)setParent:(id)fp8;
- (void)setPendingNameChange:(id)fp8;
- (void)setRepresentedAccount:(id)fp8;
- (void)setType:(int)fp8;
- (void)setUnreadCount:(unsigned int)fp8;
- (void)setUserInfoBool:(BOOL)fp8 forKey:(id)fp12;
- (void)setUserInfoObject:(id)fp8 forKey:(id)fp12;
- (void)setUserInfoWithDictionary:(id)fp8;
- (void)sortChildren;
- (id)store;
- (id)tildeAbbreviatedPath;
- (int)type;
- (id)uniqueId;
- (unsigned int)unreadCount;
- (id)userInfo;
- (BOOL)userInfoBoolForKey:(id)fp8;
- (id)userInfoDictionary;
- (id)userInfoObjectForKey:(id)fp8;
- (void)writeIndexFlagFileIfNeeded;

@end

