/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "MailApp.h"

@interface MailApp (ApplescriptSignature)
- (void)insertInSignatures:(id)fp8;
- (void)insertInSignatures:(id)fp8 atIndex:(unsigned int)fp12;
- (void)removeFromSignaturesAtIndex:(unsigned int)fp8;
@end

