/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSConcreteTextStorage.h"

@interface MessageTextStorage : NSConcreteTextStorage
{
    BOOL _isRichText;
    unsigned int _delegateRespondsToAttachmentsAdded:1;
    unsigned int _delegateRespondsToAttachmentsDeleteded:1;
    id _delegate;
}

- (id)defaultFont;
- (void)deleteCharactersInRange:(struct _NSRange)fp8;
- (void)fixParagraphStyleAttributeInRange:(struct _NSRange)fp8;
- (void)fixQuotingDisplayAttributesInRange:(struct _NSRange)fp8;
- (BOOL)isRichText;
- (void)replaceCharactersInRange:(struct _NSRange)fp8 withAttributedString:(id)fp16;
- (void)replaceCharactersInRange:(struct _NSRange)fp8 withString:(id)fp16;
- (void)setDelegate:(id)fp8;
- (void)setRichText:(BOOL)fp8;

@end

