/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "MessageViewer.h"

@interface MessageViewer (AppleScript)
- (id)allMessages;
- (int)appleScriptSortColumn;
- (id)draftsMailbox;
- (id)focusedMessages;
- (id)inbox;
- (BOOL)isSortedAscending;
- (id)junkMailbox;
- (id)objectSpecifier;
- (id)outbox;
- (BOOL)previewPaneVisible;
- (id)sentMailbox;
- (void)setAppleScriptSortColumn:(int)fp8;
- (void)setFocusedMessages:(id)fp8;
- (void)setIsSortedAscending:(BOOL)fp8;
- (void)setPreviewPaneVisible:(BOOL)fp8;
- (void)setScriptingProperties:(id)fp8;
- (void)setVisibleColumns:(id)fp8;
- (id)trashMailbox;
- (id)uniqueID;
- (id)visibleColumns;
@end

