/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSObject.h"

@class NSPort, WebView;

@interface MessageHTMLConverter : NSObject
{
    WebView *_webView;
    NSPort *_replyPort;
    unsigned int _sequenceNumber:31;
    unsigned int _outputHtml:1;
    id _result;
    int _numberOfCharacters;
    int _numberOfImages;
}

+ (id)sharedInstance;
- (id)_copyAttributedStringFromData:(id)fp8 textEncodingName:(id)fp12;
- (void)_startLoadingStringFromHTMLData:(id)fp8 textEncodingName:(id)fp12;
- (id)attributedStringFromHTMLData:(id)fp8 textEncodingName:(id)fp12;
- (void)dealloc;
- (void)finalize;
- (void)handlePortMessage:(id)fp8;
- (id)htmlStringFromHTMLData:(id)fp8 textEncodingName:(id)fp12;
- (id)init;
- (id)stringFromHTMLData:(id)fp8 textEncodingName:(id)fp12;
- (id)stringFromHTMLData:(id)fp8 textEncodingName:(id)fp12 numberOfImages:(int *)fp16 numberOfCharacters:(int *)fp20;
- (void)webView:(id)fp8 decidePolicyForNavigationAction:(id)fp12 request:(id)fp16 frame:(id)fp20 decisionListener:(id)fp24;
- (void)webView:(id)fp8 didFailLoadWithError:(id)fp12 forFrame:(id)fp16;
- (void)webView:(id)fp8 didFailProvisionalLoadWithError:(id)fp12 forFrame:(id)fp16;
- (void)webView:(id)fp8 didFinishLoadForFrame:(id)fp12;
- (void)webView:(id)fp8 didStartProvisionalLoadForFrame:(id)fp12;
- (id)webView:(id)fp8 identifierForInitialRequest:(id)fp12 fromDataSource:(id)fp16;
- (void)webView:(id)fp8 locationChangeDone:(id)fp12 forDataSource:(id)fp16;
- (id)webView:(id)fp8 resource:(id)fp12 willSendRequest:(id)fp16 redirectResponse:(id)fp20 fromDataSource:(id)fp24;

@end

