/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSView.h"

@class AttachmentsView, NSImageView, NSTextView;

@interface MessageTilingView : NSView
{
    NSTextView *headerView;
    NSView *bodyView;
    AttachmentsView *attachmentsView;
    NSImageView *senderImageView;
    NSTextView *revealLinkView;
    unsigned int _doneInitializing:1;
    unsigned int _shouldShowSeparator:1;
    unsigned int _tilingSubviews:1;
    unsigned int _resizingFromSuperview:1;
    unsigned int _bodyViewIsLoaded:1;
    unsigned int _okayToResize:1;
    unsigned int _hasResizedBody:1;
    unsigned int _showRevealMessageLink;
    NSView *accessibilityLinkedView;
}

- (id)_revealLinkString;
- (id)_revealLinkView;
- (id)_textAttributesForRevealLink;
- (void)_updateRevealLinkPosition;
- (id)attachmentsView;
- (void)awakeFromNib;
- (id)bodyView;
- (struct _NSSize)contentSize;
- (void)dealloc;
- (void)drawRect:(struct _NSRect)fp8;
- (BOOL)isFlipped;
- (BOOL)isOpaque;
- (void)keyDown:(id)fp8;
- (BOOL)knowsPageRange:(struct _NSRange *)fp8;
- (void)mouseDown:(id)fp8;
- (void)resizeSubviewsWithOldSize:(struct _NSSize)fp8;
- (void)resizeWithOldSuperviewSize:(struct _NSSize)fp8;
- (id)revealLinkView;
- (id)senderImageView;
- (void)setBodyView:(id)fp8;
- (void)setBodyViewIsLoaded:(BOOL)fp8;
- (void)setShowRevealMessageLink:(BOOL)fp8;
- (void)setUpAccessiblityLinksFromView:(id)fp8;
- (void)showAttachmentsView:(BOOL)fp8;
- (BOOL)showRevealMessageLink;
- (BOOL)showRevealMessageLinkView;
- (void)showSenderImage:(BOOL)fp8;
- (void)showSeparator:(BOOL)fp8;
- (void)subviewFrameChanged:(id)fp8;
- (BOOL)textView:(id)fp8 clickedOnLink:(id)fp12 atIndex:(unsigned int)fp16;
- (void)tile;

@end

