/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSObject.h"

#import "MessageConsumerProtocol.h"

@class NSMutableArray;

@interface MessageCollector : NSObject <MessageConsumer>
{
    NSMutableArray *messages;
}

- (void)dealloc;
- (void)finalize;
- (id)init;
- (id)messages;
- (void)newMessagesAvailable:(id)fp8;
- (void)newMessagesAvailable:(id)fp8 ranks:(id)fp12;
- (BOOL)shouldCancel;

@end

