/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSObject.h"

@interface MessageDetails : NSObject
{
    unsigned int libraryID;
    unsigned int messageFlags;
    unsigned int uid;
    unsigned int encoding;
    BOOL isInvalid;
}

- (id)description;
- (id)init;
- (unsigned long)uid;

@end

