/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSTextView.h"

@interface MessageTextView : NSTextView
{
    unsigned int _deletingText:1;
    unsigned int _actuallyImportsGraphics:1;
    unsigned int _actuallyRichText:1;
    unsigned int _isTrackingMouse:1;
}

+ (void)initialize;
- (void)_attachmentFinishedDownloading:(id)fp8;
- (id)_attachmentForPoint:(struct _NSPoint)fp8;
- (struct _NSRect)_cellFrameForAttachment:(id)fp8 atCharIndex:(int)fp12;
- (BOOL)_readSelectionFromPasteboard:(id)fp8 type:(id)fp12 useCurrentStyle:(BOOL)fp16;
- (id)acceptableDragTypes;
- (BOOL)acceptsFirstResponder;
- (void)adjustFontSizeBy:(int)fp8;
- (id)attachmentForEvent:(id)fp8;
- (void)changeQuoteLevel:(id)fp8;
- (void)chooseApplicationToOpenAttachment:(id)fp8;
- (void)copy:(id)fp8;
- (void)copyWithGatekeeperApproval:(id)fp8;
- (void)dealloc;
- (id)defaultFont;
- (void)deleteAttachment:(id)fp8;
- (void)deleteDraggedAttachments:(id)fp8;
- (void)didChangeText;
- (void)doCommandBySelector:(SEL)fp8;
- (id)dragImageForSelectionWithEvent:(id)fp8 origin:(struct _NSPoint *)fp12;
- (unsigned int)dragOperationForDraggingInfo:(id)fp8 type:(id)fp12;
- (void)drawRect:(struct _NSRect)fp8;
- (id)hitTest:(struct _NSPoint)fp8;
- (id)imageOfAttachmentsFromRange:(struct _NSRange)fp8 lowerLeft:(struct _NSPoint *)fp16;
- (void)importInvitations:(id)fp8;
- (BOOL)importsGraphics;
- (id)initWithFrame:(struct _NSRect)fp8;
- (void)insertNewline:(id)fp8;
- (BOOL)isRichText;
- (void)keyDown:(id)fp8;
- (void)layoutManager:(id)fp8 didCompleteLayoutForTextContainer:(id)fp12 atEnd:(BOOL)fp16;
- (BOOL)linkTrackMouseDown:(id)fp8;
- (void)makeFontBigger:(id)fp8;
- (void)makeFontSmaller:(id)fp8;
- (id)menuForEvent:(id)fp8;
- (BOOL)moreThanOneAttachmentSelected;
- (void)mouseDown:(id)fp8;
- (void)openAttachment:(id)fp8;
- (void)openAttachmentWithApplication:(id)fp8;
- (void)orderFrontFontPanel:(id)fp8;
- (id)originalDragImageForSelectionWithEvent:(id)fp8 origin:(struct _NSPoint *)fp12;
- (void)originalSelectAll:(id)fp8;
- (void)pasteWithCurrentStyle:(id)fp8;
- (BOOL)readSelectionFromPasteboard:(id)fp8 type:(id)fp12;
- (id)readablePasteboardTypes;
- (void)resetCursorRects;
- (void)saveAttachment:(id)fp8;
- (void)saveAttachmentToDownloadsDirectory:(id)fp8;
- (id)searchString;
- (void)selectAll:(id)fp8;
- (void)selectText:(id)fp8;
- (id)selectedAttachments;
- (struct _NSRange)selectedSearchRange;
- (void)setDelegate:(id)fp8;
- (void)setImportsGraphics:(BOOL)fp8;
- (void)setRichText:(BOOL)fp8;
- (void)setSelectedRange:(struct _NSRange)fp8 affinity:(int)fp16 stillSelecting:(BOOL)fp20;
- (BOOL)shouldChangeTextInRange:(struct _NSRange)fp8 replacementString:(id)fp16;
- (void)showSearchResultsRange:(struct _NSRange)fp8;
- (void)textView:(id)fp8 clickedOnCell:(id)fp12 event:(id)fp16 inRect:(struct _NSRect)fp20 atIndex:(unsigned int)fp36;
- (id)typingAttributes;
- (BOOL)validateMenuItem:(id)fp8;
- (id)view:(id)fp8 stringForToolTip:(int)fp12 point:(struct _NSPoint)fp16 userData:(void *)fp24;
- (void)viewAttachmentInline:(id)fp8;
- (id)writablePasteboardTypes;
- (BOOL)writeSelectionToPasteboard:(id)fp8 type:(id)fp12;
- (BOOL)writeSelectionToPasteboard:(id)fp8 types:(id)fp12;

@end

