/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSObject.h"

@class MessageContentController, NSMutableArray, NSPrintInfo, NSPrintOperation, NSString, NSView, NSWindow;

@interface MessagePrinter : NSObject
{
    NSMutableArray *_messages;
    MessageContentController *_contentController;
    NSWindow *_window;
    NSPrintOperation *printOperation;
    NSPrintInfo *printInfo;
    unsigned int messageIndex;
    NSString *originalFilename;
    NSView *accessoryView;
    unsigned int scalingBehavior;
    NSWindow *onscreenWindow;
}

+ (unsigned int)scalingBehaviorFromDefaults;
+ (void)setScalingBehaviorInDefaults:(unsigned int)fp8;
- (void)cleanUp;
- (void)dealloc;
- (struct _CGDirectDisplayID *)displayIDForWindow:(id)fp8;
- (id)init;
- (void)initPrintInfo;
- (BOOL)loadNibFile;
- (void)printMessages:(id)fp8 viewingState:(id)fp12 showDefaultHeaders:(BOOL)fp16 forWindow:(id)fp20;
- (void)printNextMessage;
- (void)printOperationDidRun:(id)fp8 success:(BOOL)fp12 contextInfo:(id)fp16;
- (void)printSheetDidClose;
- (void)regularMessageIsReady:(id)fp8;
- (void)setMessages:(id)fp8;
- (void)toggleScalingBehavior:(id)fp8;
- (struct _NSRect)windowFrameForBehavior:(unsigned int)fp8 printInfo:(id)fp12;

@end

