/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import <Message/MessageHeaders.h>

@class NSMutableArray, NSMutableDictionary;

@interface MutableMessageHeaders : MessageHeaders
{
    NSMutableDictionary *_headersAdded;
    NSMutableArray *_headersRemoved;
}

- (void)_appendAddedHeaderKey:(id)fp8 value:(id)fp12 toData:(id)fp16;
- (void)_appendHeaderKey:(id)fp8 value:(id)fp12 toData:(id)fp16;
- (id)_encodedHeadersIncludingFromSpace:(BOOL)fp8;
- (id)_headerValueForKey:(id)fp8;
- (id)allHeaderKeys;
- (void)appendFromSpaceIfMissing;
- (void)dealloc;
- (void)finalize;
- (id)firstHeaderForKey:(id)fp8;
- (BOOL)hasHeaderForKey:(id)fp8;
- (id)mutableCopy;
- (void)removeHeaderForKey:(id)fp8;
- (void)setAddressList:(id)fp8 forKey:(id)fp12;
- (void)setHeader:(id)fp8 forKey:(id)fp12;

@end

