/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import <Message/ByteSet.h>

@interface MutableByteSet : ByteSet
{
}

- (void)addBytesInRange:(struct _NSRange)fp8;
- (void)invert;
- (void)removeBytesInRange:(struct _NSRange)fp8;

@end

