/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSObject.h"

@class NSView;

@interface MVComposeAccessoryViewOwner : NSObject
{
    NSView *accessoryView;
}

+ (id)composeAccessoryViewNibName;
+ (id)composeAccessoryViewOwner;
- (id)composeAccessoryView;
- (id)init;
- (BOOL)messageWillBeDelivered:(id)fp8;
- (BOOL)messageWillBeSaved:(id)fp8;
- (void)setupUIForMessage:(id)fp8;

@end

