/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import <Foundation/Foundation.h>

@interface MVMailBundle : NSObject
{
}

+ (id)allBundles;
+ (id)composeAccessoryViewOwnerClassName;
+ (id)composeAccessoryViewOwners;
+ (BOOL)hasComposeAccessoryViewOwner;
+ (BOOL)hasPreferencesPanel;
+ (id)preferencesOwnerClassName;
+ (id)preferencesPanelName;
+ (void)registerBundle;
+ (id)sharedInstance;
- (void)_registerBundleForNotifications;
- (void)dealloc;

@end

