/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "MessageStore.h"

@class NSData, TableOfContents;

@interface NeXTMbox : MessageStore
{
    NSData *_mboxData;
    TableOfContents *_toc;
    float _compactThreshold;
    unsigned int _mboxIsOnSMB:1;
    unsigned int _haveUpdatedMetadata:1;
    NSData *_incomingMboxData;
    unsigned int _importMode:1;
}

+ (BOOL)cheapStoreAtPathIsEmpty:(id)fp8;
+ (BOOL)createEmptyStoreForPath:(id)fp8;
+ (BOOL)storeAtPathIsWritable:(id)fp8;
- (void)_addIDsForAppendedMessages:(id)fp8 toArray:(id)fp12;
- (id)_appendMessage:(id)fp8 toFile:(id)fp12;
- (int)_appendMessages:(id)fp8 successes:(id *)fp12 failures:(id *)fp16 mboxName:(id)fp20 tableOfContents:(id)fp24;
- (void)_deleteAttachments:(id)fp8;
- (id)_fetchBodyDataForMessage:(id)fp8 andHeaderDataIfReadilyAvailable:(id *)fp12;
- (id)_fetchHeaderDataForMessage:(id)fp8;
- (void)_flushAllMessageData;
- (void)_incorporateMailFromIncoming;
- (void)_invalidate;
- (id)_lockFilePath;
- (void)_rebuildTableOfContentsSynchronously;
- (void)_releaseMboxData;
- (void)_resetAllMessages;
- (BOOL)_shouldCallCompactWhenClosing;
- (int)_writeMessagesToIncomingMail:(id)fp8 unsuccessfulOnes:(id)fp12 newMessageIDs:(id)fp16;
- (BOOL)allowsAppend;
- (int)appendMessages:(id)fp8 unsuccessfulOnes:(id)fp12 newMessageIDs:(id)fp16 newMessages:(id)fp20;
- (BOOL)canCompact;
- (float)compactThreshold;
- (void)dealloc;
- (void)doCompact;
- (void)finalize;
- (id)incomingMessages;
- (id)initWithMailboxUid:(id)fp8 readOnly:(BOOL)fp12;
- (BOOL)isSortedAscending;
- (id)messageForMessageID:(id)fp8;
- (id)messagesForImporter;
- (void)openSynchronouslyUpdatingMetadata:(BOOL)fp8;
- (void)setCompactThreshold:(float)fp8;
- (id)setFlagsFromDictionary:(id)fp8 forMessages:(id)fp12;
- (id)sortOrder;
- (void)suggestSortOrder:(id)fp8 ascending:(BOOL)fp12;
- (BOOL)tableOfContents:(id)fp8 loadedMessages:(id)fp12;
- (int)undoAppendOfMessageIDs:(id)fp8;
- (void)updateMetadata;
- (void)writeUpdatedMessageDataToDisk;

@end

