/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSArray.h"

@interface NSArray (AtomicAddress)
- (id)atomicAddressesOfType:(int)fp8;
- (id)attributedStringOfAddressesAttachments:(id *)fp8 type:(int)fp12;
@end

