/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSAttributedString.h"

@interface NSAttributedString (AtomicAddress)
+ (id)atomicAddressFromDictionary:(id)fp8;
- (id)addressAttachments;
- (id)addressBookRecord;
- (id)allAddresses;
- (id)atomicAddresses;
- (BOOL)containsAddressAttachments;
- (BOOL)containsOnlyAtoms;
- (struct _NSRange)convertPlainTextRange:(struct _NSRange)fp8;
- (struct _NSRange)convertToPlainTextRange:(struct _NSRange)fp8;
- (id)dictionaryRepresentation;
- (void)displayCommasExceptAtEnd;
- (void)displayCommasForAllAddresses;
- (BOOL)knownToHaveNoRecord;
- (id)mutableCopyWithNewAttachments:(id *)fp8;
- (id)replaceAttachmentsWithAddressesIncludeName:(BOOL)fp8;
- (id)stringOfAddressesWithAtomsExpandedIncludeName:(BOOL)fp8;
- (id)stringWithAtomsExpanded;
- (void)testSpotlighting;
- (id)unatomicAddress;
- (id)unatomicAddresses;
@end

