/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSColor.h"

@interface NSColor (NSColorUtilities)
+ (void)_configureColorMenuForBoneHeadClients:(id)fp8;
+ (id)activeLinkColor;
+ (id)allHighlightColors;
+ (id)allQuotingColors;
+ (void)clearThreadBackgroundColors;
+ (id)colorForHighlightColorValue:(int)fp8;
+ (id)colorForIdentifier:(id)fp8;
+ (id)colorPlist;
+ (id)colorWithIntValue:(int)fp8;
+ (void)configureColorMenu:(id)fp8;
+ (id)createSwatchForColor:(id)fp8;
+ (id)defaultQuotingColors;
+ (int)highlightColorValueForColor:(id)fp8;
+ (id)identifierForColor:(id)fp8;
+ (int)intWithIdentifierColor:(id)fp8;
+ (id)junkMailColor;
+ (id)lighterThreadBackgroundColor;
+ (id)linkColor;
+ (void)setThreadBackgroundColor:(id)fp8;
+ (id)threadBackgroundColor;
+ (id)visitedLinkColor;
- (int)intValue;
@end

