/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSDictionary.h"

@interface NSDictionary (Goodies)
- (BOOL)boolForKey:(id)fp8;
- (int)integerForKey:(id)fp8;
@end

