/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSFileWrapper.h"

@interface NSFileWrapper (HFSExtensions)
+ (id)allocWithZone:(struct _NSZone *)fp8;
- (id)contentID;
- (BOOL)couldConfuseWindowsClients;
- (unsigned long)creator;
- (unsigned short)finderFlags;
- (id)iconCreateIfNecessary:(BOOL)fp8;
- (unsigned int)imageBytes;
- (struct _NSSize)imageSize;
- (BOOL)isImageFile;
- (BOOL)isPlaceholder;
- (id)messageID;
- (id)mimeType;
- (id)preferredFilenameWithoutHiddenExtension;
- (id)resourceForkData;
- (void)setContentID:(id)fp8;
- (void)setCreator:(unsigned long)fp8;
- (void)setFinderFlags:(unsigned short)fp8;
- (void)setImageSize:(struct _NSSize)fp8 imageBytes:(unsigned int)fp16;
- (void)setMessageID:(id)fp8;
- (void)setMimeType:(id)fp8;
- (void)setResourceForkData:(id)fp8;
- (void)setShouldBeViewedInline:(BOOL)fp8;
- (void)setShouldHideExtension:(BOOL)fp8;
- (void)setType:(unsigned long)fp8;
- (void)setWhereFroms:(id)fp8;
- (BOOL)shouldBeViewedInline;
- (BOOL)shouldHideExtension;
- (id)tmpFullPath;
- (unsigned long)type;
- (id)whereFroms;
@end

