/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSImage.h"

@interface NSImage (ASBetterImageLookup)
+ (id)appIconIncludingUserCustomization;
+ (id)appIconWithUnreadBadge:(int)fp8 baseImageName:(id)fp12;
+ (id)betterImageNamed:(id)fp8;
+ (id)createScaledImageFromImage:(id)fp8 desiredSize:(struct _NSSize)fp12;
+ (id)imagePasteboardTypesWithPreferenceToPNG;
@end

