/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSSound.h"

@interface NSSound (MessageAdditions)
+ (void)_addSoundOrPathToPlayList:(id)fp8 playImmediately:(BOOL)fp12;
+ (void)_playNextSound;
+ (void)_playSound;
+ (void)_setupPlayList;
+ (void)addSoundPathToPlayList:(id)fp8 playImmediately:(BOOL)fp12;
+ (void)addSoundToPlayList:(id)fp8 playImmediately:(BOOL)fp12;
+ (id)appendSoundsToPaths:(id)fp8;
+ (id)librarySoundsDirs;
+ (id)networkLibrarySoundsDirs;
+ (void)sound:(id)fp8 didFinishPlaying:(BOOL)fp12;
+ (id)soundsAtPaths:(id)fp8;
+ (id)systemLibrarySoundsDirs;
+ (id)tildeLibrarySoundsDirs;
+ (id)validPathToSound:(id)fp8;
@end

