/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSString.h"

@interface NSString (MailAdditions)
- (void)drawEtchedInRect:(struct _NSRect)fp8 withTopColor:(id)fp24 bottomColor:(id)fp28 font:(id)fp32 centered:(BOOL)fp36 flipped:(BOOL)fp40;
@end

