/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSTableView.h"

@interface NSTableView (MailAdditions)
- (int)firstmostSelectedRow;
- (BOOL)isSelectionVisible;
- (int)lastmostSelectedRow;
- (void)scrollRowToVisible:(int)fp8 position:(int)fp12;
- (void)showSelectionAndCenter:(BOOL)fp8;
@end

