/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import <Message/Message.h>

@class MessageBody, MutableMessageHeaders;

@interface OutgoingMessage : Message
{
    MessageBody *messageBody;
    MutableMessageHeaders *messageHeaders;
}

- (void)dealloc;
- (void)finalize;
- (id)headers;
- (id)messageBody;
- (id)messageBodyIfAvailable;
- (id)messageDataIncludingFromSpace:(BOOL)fp8;
- (id)messageStore;
- (id)mutableHeaders;
- (void)setMutableHeaders:(id)fp8;

@end

