/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSObject.h"

@interface ParentalControlSettings : NSObject
{
}

+ (void)initialize;
+ (BOOL)isEmail:(id)fp8 inEmailList:(id)fp12;
+ (id)sharedInstance;
- (BOOL)_approveEmail:(id)fp8;
- (void)_approveEmailListChanged:(id)fp8;
- (id)_approvedEmails;
- (void)_defaultsDidChange;
- (id)_dictionaryFromEmail:(id)fp8;
- (BOOL)_isSelfEmail:(id)fp8;
- (void)_reallyHandleDefaultsChange;
- (BOOL)_rejectEmail:(id)fp8;
- (id)approveEmails:(id)fp8;
- (void)dealloc;
- (void)finalize;
- (BOOL)hasEmailBeenApproved:(id)fp8;
- (BOOL)haveEmailsBeenApproved:(id)fp8 unapprovedOnes:(id)fp12;
- (id)init;
- (BOOL)isInSpamProtectionMode;
- (BOOL)isParentEmail:(id)fp8;
- (id)parentEmails;
- (double)parentalControlEnabledTimeIntervalSince1970;
- (id)rejectEmails:(id)fp8;
- (void)saveChanges;

@end

