/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import <Message/MessageStore.h>

@class NSArray;

@interface RecoveredStore : MessageStore
{
    NSArray *_pathsToImport;
}

- (void)dealloc;
- (id)initWithMailboxUid:(id)fp8 readOnly:(BOOL)fp12 pathsToImport:(id)fp16;
- (id)messagesForImporter;

@end

