/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSView.h"

@class NSButton, NSImageView, NSMutableArray, NSProgressIndicator;

@interface SearchSliceView : NSView
{
    int _searchType;
    int _searchTarget;
    id _delegate;
    NSButton *_saveButton;
    NSProgressIndicator *_progressIndicator;
    NSMutableArray *_typeButtons;
    NSMutableArray *_targetButtons;
    NSImageView *_separator;
    unsigned int _layingOutItems:1;
    double _lastLayoutTime;
    BOOL _canContentSearchSelectedMailboxes;
}

- (void)_addButtonForSearchTarget:(int)fp8;
- (void)_addButtonForSearchType:(int)fp8;
- (id)_backgroundColor;
- (void)_layoutItems;
- (struct CGSize)_patternPhase;
- (void)_setupView;
- (void)_updateContentSearchButtonEnabledState;
- (void)_updateUI;
- (void)_updateUIToReflectSearchTarget;
- (void)_updateUIToReflectSearchType;
- (void)dealloc;
- (id)delegate;
- (void)drawRect:(struct _NSRect)fp8;
- (id)initWithFrame:(struct _NSRect)fp8;
- (id)initWithFrame:(struct _NSRect)fp8 searchType:(int)fp24 searchTarget:(int)fp28;
- (void)saveButtonAction:(id)fp8;
- (int)searchTarget;
- (void)searchTargetButtonAction:(id)fp8;
- (int)searchType;
- (void)searchTypeButtonAction:(id)fp8;
- (void)setCanContentSearchSelectedMailboxes:(BOOL)fp8;
- (void)setCanSaveSearch:(BOOL)fp8;
- (void)setCanSearchSelectedMailbox:(BOOL)fp8;
- (void)setDelegate:(id)fp8;
- (void)setFrame:(struct _NSRect)fp8;
- (void)setSearchTarget:(int)fp8;
- (void)setSearchType:(int)fp8;
- (void)startProgressAnimation;
- (void)stopProgressAnimation;
- (id)targetButtonWithTag:(int)fp8;
- (id)typeButtonWithTag:(int)fp8;
- (void)viewDidEndLiveResize;
- (void)viewWillStartLiveResize;

@end

