/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCopyingProtocol.h"

@class NSImage, NSMenu, NSString;

@interface SegmentItem : NSObject <NSCopying>
{
    float _width;
    NSImage *_image;
    NSString *_label;
    NSMenu *_menu;
    NSString *_toolTip;
    int _tag;
    struct {
        unsigned int needsRecalc:1;
        unsigned int selected:1;
        unsigned int disabled:1;
        unsigned int showMenuIndicator:1;
        unsigned int reserved:28;
    } _flags;
    float _fullWidth;
    float _shrinkage;
    struct _NSRect _imageRect;
    struct _NSRect _labelRect;
    struct _NSRect _menuIndRect;
    int _toolTipTag;
}

- (float)_displayWidth;
- (BOOL)_needsRecalc;
- (void)_recalcRectsForCell:(id)fp8;
- (BOOL)_setImage:(id)fp8;
- (BOOL)_setLabel:(id)fp8;
- (BOOL)_setMenu:(id)fp8;
- (void)_setNeedsRecalc;
- (BOOL)_setWidth:(float)fp8;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)dealloc;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (id)view:(id)fp8 stringForToolTip:(int)fp12 point:(struct _NSPoint)fp16 userData:(void *)fp24;

@end

