/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "MVMailBundle.h"

#import "SyncableDataOwnerProtocol.h"

@class NSMutableArray, NSMutableDictionary;

@interface SignatureBundle : MVMailBundle <SyncableDataOwner>
{
    NSMutableDictionary *_signatures;
    NSMutableArray *accounts;
    BOOL _isDirty;
    BOOL _isSavingSyncResults;
    NSMutableDictionary *_lastDefaultSignatures;
    int fileVersionNumber;
}

+ (id)_oldSignaturesPath;
+ (id)_reallyOldSignaturesPath;
+ (id)allSignaturesAccount;
+ (void)initialize;
+ (id)signaturesFolderPath;
+ (id)signaturesPlistPath;
- (id)activeSignatureWithId:(id)fp8;
- (id)activeSignatureWithName:(id)fp8;
- (void)addSignature:(id)fp8;
- (void)configurePopUpButton:(id)fp8 forAccount:(id)fp12 defaultSignature:(id)fp16 selectionMethod:(int)fp20 showAccount:(BOOL)fp24;
- (BOOL)dataWasSyncedVersion:(id)fp8 newData:(id)fp12 acceptedChanges:(id)fp16;
- (BOOL)dataWillBeSyncedVersion:(id *)fp8 data:(id *)fp12;
- (void)dealloc;
- (id)defaultSignatureForAccount:(id)fp8;
- (BOOL)deleteSignaturesNotPresentInNewSignatures:(id)fp8;
- (id)dictionaryRepresentationIncludingSyncInformation:(BOOL)fp8;
- (id)fixAccountIdsInPlist:(id)fp8;
- (id)init;
- (void)insertSignature:(id)fp8 atIndex:(int)fp12;
- (void)insertSignature:(id)fp8 atIndex:(int)fp12 forAccount:(id)fp16;
- (id)loadFromDictionary:(id)fp8;
- (void)loadLastDefaultSignatures;
- (unsigned int)numberOfSignatures;
- (BOOL)placeSignatureAboveQuotedText;
- (void)removeSignature:(id)fp8;
- (void)removeSignatureAtIndex:(int)fp8;
- (void)removeSignatureAtIndex:(int)fp8 forAccount:(id)fp12;
- (void)saveChangesToDisk;
- (void)setDefaultSignature:(id)fp8 forAccount:(id)fp12;
- (void)setDefaultSignatureId:(id)fp8 forAccountId:(id)fp12;
- (void)setPlaceSignatureAboveQuotedText:(BOOL)fp8;
- (void)setShowsComposeAccessoryView:(BOOL)fp8;
- (void)setSignatureSelectionMethod:(int)fp8 forAccount:(id)fp12;
- (BOOL)showComposeAccessoryView;
- (BOOL)showComposeAccessoryView:(char *)fp8;
- (id)signatureAccounts;
- (id)signatureAtIndex:(int)fp8;
- (id)signatureAtIndex:(int)fp8 forAccount:(id)fp12;
- (void)signatureNameChanged:(id)fp8;
- (int)signatureSelectionMethodForAccount:(id)fp8;
- (id)signatures;
- (id)signaturesForAccount:(id)fp8;
- (void)syncSignatures;
- (void)unsetShowsComposeAccessoryView;
- (BOOL)updateAccountList;

@end

