/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "MessageViewer.h"

#import "MVSelectionOwnerProtocol.h"

@class MessageStore, NSView, SpotlightBar;

@interface SingleMessageViewer : MessageViewer <MVSelectionOwner>
{
    NSView *_messageContentView;
    MessageStore *messageStore;
    SpotlightBar *_spotlightBar;
}

+ (void)restoreFromDefaults;
+ (void)saveDefaultsOmittingViewer:(id)fp8;
+ (id)viewerForMessage:(id)fp8 showAllHeaders:(BOOL)fp12 viewingState:(id)fp16;
- (void)_adjustNewSingleViewerWindowFrame;
- (void)_changeFlag:(id)fp8 state:(BOOL)fp12 forMessages:(id)fp16 undoActionName:(id)fp20;
- (void)_hideSpotlightBar;
- (BOOL)_isViewingMessage:(id)fp8;
- (void)_restoreViewer;
- (id)_saveDefaults;
- (BOOL)_selectionContainsMessagesWithAttachments;
- (BOOL)_selectionContainsMessagesWithFlaggedStatusEqualTo:(BOOL)fp8;
- (BOOL)_selectionContainsMessagesWithJunkMailLevelEqualTo:(int)fp8;
- (BOOL)_selectionContainsMessagesWithReadStatusEqualTo:(BOOL)fp8;
- (void)_setupFromDefaults;
- (void)_setupToolBar;
- (void)_showSpotlightBarWithSearchString:(id)fp8;
- (id)currentDisplayedMessage;
- (void)dealloc;
- (void)deleteMessages:(id)fp8;
- (void)deleteMessagesAllowingMoveToTrash:(BOOL)fp8;
- (void)editorWithGatekeeperApproval:(id)fp8;
- (void)forwardMessage:(id)fp8;
- (id)initForViewingMessage:(id)fp8 showAllHeaders:(BOOL)fp12 viewingState:(id)fp16;
- (id)initForViewingMessage:(id)fp8 showAllHeaders:(BOOL)fp12 viewingState:(id)fp16 fromDefaults:(BOOL)fp20;
- (id)initWithSavedDefaults:(id)fp8;
- (void)keyDown:(id)fp8;
- (void)messageFlagsDidChange:(id)fp8;
- (id)messageIDDictionary;
- (id)messageStore;
- (void)redirectMessage:(id)fp8;
- (void)replaceWithEditorForType:(int)fp8;
- (void)replyAllMessage:(id)fp8;
- (void)replyMessage:(id)fp8;
- (void)replyToOriginalSender:(id)fp8;
- (void)replyToSender:(id)fp8;
- (void)resignAsSelectionOwner;
- (void)revealMessage:(id)fp8;
- (void)selectMessages:(id)fp8;
- (id)selectedMessages;
- (id)selection;
- (BOOL)send:(id)fp8;
- (void)setSearchString:(id)fp8;
- (void)showAndMakeKey:(BOOL)fp8;
- (void)takeOverAsSelectionOwner;
- (BOOL)transferSelectionToMailbox:(id)fp8 deleteOriginals:(BOOL)fp12;

@end

