/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSObject.h"

@class CriteriaUIHelper, MailboxUid, NSTextField, NSTextView;

@interface SmartMailboxEditor : NSObject
{
    MailboxUid *mailboxBeingEdited;
    MailboxUid *mailboxBeingValidated;
    CriteriaUIHelper *criteriaUIHelper;
    NSTextField *nameField;
    NSTextField *groupNameField;
    NSTextField *searchStringField;
    NSTextView *mailboxesTextView;
    BOOL editedMailboxIsNew;
}

+ (BOOL)isEditingInProgress;
+ (BOOL)mailboxIsEditable:(id)fp8;
- (void)alertDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (void)cancelClicked:(id)fp8;
- (void)createNewMailboxGroup;
- (void)dealloc;
- (void)editSmartMailbox:(id)fp8 suggestedName:(id)fp12 isNew:(BOOL)fp16;
- (void)okClicked:(id)fp8;
- (void)saveEditedMailbox;
- (void)sheetDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;

@end

