/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import <Message/MailDelivery.h>

@class SMTPConnection;

@interface SMTPDelivery : MailDelivery
{
    SMTPConnection *_connection;
}

- (int)deliverMessageData:(id)fp8 toRecipients:(id)fp12;
- (Class)deliveryClass;

@end

