/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "DeliveryAccount.h"

@class NSTimer, SMTPConnection;

@interface SMTPAccount : DeliveryAccount
{
    SMTPConnection *_connection;
    NSTimer *_timer;
    int _lastTimerSetTime;
}

+ (id)accountTypeString;
+ (id)newDefaultInstance;
- (BOOL)_shouldTryDirectSSLConnectionOnPort:(unsigned int)fp8;
- (id)authenticatedConnection;
- (void)checkInConnection:(id)fp8;
- (Class)connectionClass;
- (void)connectionExpired:(id)fp8;
- (void)dealloc;
- (unsigned int)defaultPortNumber;
- (Class)deliveryClass;
- (void)disconnect:(id)fp8;
- (void)finalize;
- (id)passwordFromKeychain;
- (id)preferredAuthScheme;
- (void)releaseAllConnections;
- (id)saslProfileName;
- (id)serviceName;
- (void)setPasswordInKeychain:(id)fp8;
- (void)setPreferredAuthScheme:(id)fp8;
- (void)setTimer;

@end

