/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSObject.h"

@interface StmtHandle : NSObject
{
    struct sqlite3_stmt *stmt;
}

+ (id)handleForStmt:(struct sqlite3_stmt *)fp8;
- (void)dealloc;
- (id)initWithStmt:(struct sqlite3_stmt *)fp8;

@end

