/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSObject.h"

#import "MessageContentDisplayProtocol.h"

@class MessageBody, MessageHeaderDisplay, MessageTextView, NSMutableSet, NSScrollView;

@interface TextMessageDisplay : NSObject <MessageContentDisplay>
{
    NSScrollView *messageScroll;
    MessageTextView *textView;
    MessageHeaderDisplay *headerDisplay;
    MessageBody *messageBody;
    BOOL attachmentsMayBeLoading;
    BOOL needsSetUp;
    NSMutableSet *gatekeeperApprovedAttachments;
}

+ (id)copyDocumentForMessage:(id)fp8 viewingState:(id)fp12;
- (void)_webViewSelectionDidChange:(id)fp8;
- (void)adjustFontSizeBy:(int)fp8 viewingState:(id)fp12;
- (id)attachmentContextMenu;
- (id)attachmentsInSelection;
- (void)awakeFromNib;
- (void)cacheGatekeeperApprovalStatus:(BOOL)fp8 forAttachment:(id)fp12;
- (BOOL)cachedGatekeeperApprovalStatusForAttachment:(id)fp8;
- (id)contentView;
- (void)dealloc;
- (void)display:(id)fp8 inContainerView:(id)fp12 replacingView:(id)fp16;
- (void)displayAttributedString:(id)fp8;
- (id)dragImageForSelection;
- (id)findTarget;
- (void)headerTextIsChangingSelectionToRange:(struct _NSRange)fp8;
- (void)highlightSearchText:(id)fp8;
- (id)messageTextView:(id)fp8 willReturnMenu:(id)fp12 forEvent:(id)fp16;
- (void)prepareToRemoveView;
- (void)selectAll;
- (id)selectedText;
- (id)selectedWebArchive;
- (id)textView;
- (void)textView:(id)fp8 clickedOnCell:(id)fp12 inRect:(struct _NSRect)fp16 atIndex:(unsigned int)fp32;
- (BOOL)textView:(id)fp8 clickedOnLink:(id)fp12 atIndex:(unsigned int)fp16;
- (void)textView:(id)fp8 doubleClickedOnCell:(id)fp12 inRect:(struct _NSRect)fp16 atIndex:(unsigned int)fp32;
- (id)textView:(id)fp8 dragImageForSelectionWithEvent:(id)fp12 origin:(struct _NSPoint *)fp16;
- (void)textView:(id)fp8 draggedCell:(id)fp12 inRect:(struct _NSRect)fp16 event:(id)fp32 atIndex:(unsigned int)fp36;
- (void)textView:(id)fp8 setSelectedRange:(struct _NSRange)fp12 affinity:(int)fp20 stillSelecting:(BOOL)fp24;
- (BOOL)textView:(id)fp8 shouldWriteSelectionToPasteboard:(id)fp12 types:(id)fp16;
- (id)textView:(id)fp8 willWriteSelectionToPasteboard:(id)fp12 type:(id)fp16;
- (void)textViewDidSelectAll:(id)fp8;
- (void)updateURLMatches:(id)fp8 viewingState:(id)fp12;
- (id)webArchive;

@end

