/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "WebFrame.h"

@interface WebFrame (SizingExtras)
- (void)_setSize:(struct _NSSize)fp8 ofElement:(id)fp16;
- (void)adjustAttachmentView:(id)fp8;
- (void)adjustToDocumentView;
- (void)selectAttachmentView:(id)fp8;
@end

