/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "WebHTMLView.h"

@interface WebHTMLView (MailExtras)
- (BOOL)autoscroll:(id)fp8;
- (id)enclosingTilingView;
- (BOOL)findString:(id)fp8 options:(unsigned int)fp12;
- (void)takeFindStringFromSelection:(id)fp8;
@end

