/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import <Message/MessageBody.h>

@class NSMutableData;

@interface _OutgoingMessageBody : MessageBody
{
    NSMutableData *rawData;
}

- (void)setMessage:(id)fp8;
- (void)clearMessageWithoutReleasing;
- (void)dealloc;
- (id)rawData;
- (void)setRawData:(id)fp8;
- (id)mutableData;

@end

