/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSObject.h"

@class NSTextField, NSView;

@interface AccountSummary : NSObject
{
    NSView *_view;
    NSTextField *_accountDescription;
    NSTextField *_fullname;
    NSTextField *_emailAddress;
    NSTextField *_userName;
    NSTextField *_incomingServer;
    NSTextField *_incomingServerSSLMode;
    NSTextField *_outgoingServer;
    NSTextField *_outgoingServerSSLMode;
    NSTextField *_outlookServer;
    NSTextField *_outlookServerLabel;
}

- (id)init;
- (void)setupUIWithAccount:(id)fp8 deliveryAccount:(id)fp12;
- (void)setupUIWithAccount:(id)fp8;
- (id)view;

@end

