/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSObject.h"

@class ActivityMonitor, ActivityViewer, NSButton, NSProgressIndicator, NSTextField, NSView;

@interface ActivityViewEntry : NSObject
{
    NSView *_box;
    NSProgressIndicator *_progressBar;
    NSTextField *_statusField;
    NSButton *_stopButton;
    NSTextField *_taskNameField;
    ActivityMonitor *_activity;
    int _lastChangeCount;
    ActivityViewer *_viewer;
}

- (id)initForViewer:(id)fp8;
- (void)dealloc;
- (void)awakeFromNib;
- (void)setMonitoredActivity:(id)fp8;
- (id)monitoredActivity;
- (void)update;
- (void)_handleActivityEnded;
- (void)stop:(id)fp8;
- (BOOL)inUse;
- (void)setupUI;
- (id)view;

@end

