/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "ColorBackgroundView.h"

@class ActivityAggregate, NSButton, NSProgressIndicator, NSTextField, NSViewAnimation;

@interface ActivityAggregateView : ColorBackgroundView
{
    NSTextField *_nameTextField;
    NSTextField *_rateTextField;
    NSTextField *_statusTextField;
    NSButton *_stopButton;
    NSProgressIndicator *_progressIndicator;
    float _nameTextFieldSpace;
    float _rateTextFieldSpace;
    float _statusTextFieldSpace;
    float _progressIndicatorSpace;
    NSViewAnimation *_fadeInAnimation;
    NSViewAnimation *_fadeOutAnimation;
    ActivityAggregate *_activityAggregate;
}

- (id)fadeInAnimation;
- (id)fadeOutAnimation;
- (id)activityAggregate;
- (BOOL)yes;
- (void)setActivityAggregate:(id)fp8;
- (void)setHidden:(BOOL)fp8;
- (void)setHidden:(BOOL)fp8 withFade:(BOOL)fp12 duration:(double)fp16 resetAggregate:(BOOL)fp24;
- (void)awakeFromNib;
- (void)prepareForSlumber;
- (void)awakeFromSlumber;
- (void)updateNameTextField;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (void)hideShowRate;
- (void)frameDidChange:(id)fp8;
- (void)animationDidEnd:(id)fp8;
- (void)dealloc;

@end

