/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSObject.h"

@class ActivityMonitor, NSPanel, NSProgressIndicator, NSTextField, NSTimer;

@interface ActivityProgressPanel : NSObject
{
    NSPanel *_progressPanel;
    NSProgressIndicator *_progressBar;
    NSTextField *_statusMessage;
    ActivityMonitor *_monitor;
    NSTimer *_timer;
}

- (id)init;
- (void)_invalidateTimer;
- (void)dealloc;
- (void)setActivityMonitor:(id)fp8;
- (id)activityMonitor;
- (void)setStatusMessage:(id)fp8;
- (id)statusMessage;
- (id)panel;
- (void)_updateProgressBar;
- (void)activityStarted:(id)fp8;
- (void)activityEnded:(id)fp8;
- (void)cancel:(id)fp8;

@end

