/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSTextAttachmentCell.h"

@class AddressAttachment, NSMenu, NSMutableDictionary, NSView;

@interface AddressAttachmentCell : NSTextAttachmentCell
{
    AddressAttachment *attachment;
    struct _NSRect drawingRect;
    struct _NSRect hotSpot;
    struct _NSRect onlineHotSpot;
    NSMenu *menu;
    unsigned int characterIndex;
    struct _NSSize cellSize;
    BOOL isSpotlighted;
    BOOL shouldTestForSpotlighting;
    BOOL shouldShowComma;
    NSMutableDictionary *textAttributesRegular;
    NSMutableDictionary *textAttributesWhiteText;
    NSMutableDictionary *textAttributesTruncatedRegular;
    NSMutableDictionary *textAttributesTruncatedWhiteText;
    NSView *containingView;
    unsigned int isSelected:1;
    unsigned int leftSideHasSelection:1;
    unsigned int rightSideHasSelectedText:1;
    unsigned int rightSideHasSelectedAtom:1;
    unsigned int overrideRightSideSelection:1;
    unsigned int overrideLeftSideSelection:1;
    unsigned int hideLeftSideMargin:1;
    unsigned int subtractLeftSideMarginFromRightSide:1;
    unsigned int menuIsVisible:1;
}

+ (void)initialize;
+ (int)sizeForCellOfType:(int)fp8 withAddress:(id)fp12;
+ (float)heightForAtomType:(int)fp8;
+ (BOOL)isOnLineAddress:(id)fp8;
+ (void)_changePresenceImage;
- (id)initImageCell:(id)fp8;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)addressAttachment;
- (void)setAttachment:(id)fp8;
- (void)dealloc;
- (int)characterIndex;
- (struct _NSRect)drawingRect;
- (struct _NSRect)visibleRect;
- (struct _NSRect)atomBoundsRectForCellFrame:(struct _NSRect)fp8;
- (struct _NSRect)atomBoundsRect;
- (id)dragImage;
- (id)textAttributesWhiteText;
- (id)textAttributesTruncatedWhiteText;
- (id)textAttributesRegular;
- (id)textAttributesTruncatedRegular;
- (id)view:(id)fp8 stringForToolTip:(int)fp12 point:(struct _NSPoint)fp16 userData:(void *)fp24;
- (void)resetCursorAndToolTipRect:(struct _NSRect)fp8 inView:(id)fp24;
- (id)menu;
- (BOOL)validateMenuItem:(id)fp8;
- (BOOL)isOnLine;
- (void)openChat:(id)fp8;
- (void)openNewMessage:(id)fp8;
- (void)addToAddressBook:(id)fp8;
- (void)removeRecordFromAddressBook:(id)fp8 forRecent:(id)fp12;
- (void)openInAddressBook:(id)fp8;
- (void)createSmartMailbox:(id)fp8;
- (void)removeFromAddressHistory:(id)fp8;
- (void)changeAddress:(id)fp8;
- (void)copyAddressToClipboard:(id)fp8;
- (void)searchInSpotlight:(id)fp8;
- (BOOL)isSelected;
- (void)setIsSelected:(BOOL)fp8;
- (BOOL)rightSideHasSelectedText;
- (void)setRightSideHasSelectedText:(BOOL)fp8;
- (void)setRightSideHasSelectedAtom:(BOOL)fp8;
- (BOOL)leftSideHasSelection;
- (void)setLeftSideHasSelection:(BOOL)fp8;
- (void)setOverrideRightSideSelection:(BOOL)fp8;
- (void)setOverrideLeftSideSelection:(BOOL)fp8;
- (void)testSpotlighting;
- (void)setShouldShowComma:(BOOL)fp8;
- (BOOL)shouldDrawCommaRightNow;
- (void)selectedAddressChanged;
- (void)_presenceImageChanged:(id)fp8;
- (void)fontChanged;
- (void)sizeChanged;
- (void)addressBookRecordChanged;
- (void)drawWithFrame:(struct _NSRect)fp8 inView:(id)fp24;
- (void)drawWithFrame:(struct _NSRect)fp8 inView:(id)fp24 characterIndex:(unsigned int)fp28;
- (void)drawWithFrame:(struct _NSRect)fp8 inView:(id)fp24 characterIndex:(unsigned int)fp28 layoutManager:(id)fp32;
- (void)_drawAtomPartsWithRect:(struct _NSRect)fp8 cellFrame:(struct _NSRect)fp24;
- (void)_drawAtomWithRect:(struct _NSRect)fp8 cellFrame:(struct _NSRect)fp24 inView:(id)fp40;
- (struct _NSPoint)textDrawPointInRect:(struct _NSRect)fp8 ofView:(id)fp24;
- (struct _NSSize)cellSize;
- (struct _NSSize)sizeOfString:(id)fp8;
- (struct _NSRect)cellFrameForTextContainer:(id)fp8 proposedLineFragment:(struct _NSRect)fp12 glyphPosition:(struct _NSPoint)fp28 characterIndex:(unsigned int)fp36;
- (struct _NSPoint)cellBaselineOffset;
- (BOOL)trackMouse:(id)fp8 inRect:(struct _NSRect)fp12 ofView:(id)fp28 atCharacterIndex:(unsigned int)fp32 untilMouseUp:(BOOL)fp36;
- (BOOL)wantsToTrackMouse;
- (BOOL)wantsToTrackMouseForEvent:(id)fp8;
- (BOOL)wantsToTrackMouseForEvent:(id)fp8 inRect:(struct _NSRect)fp12 ofView:(id)fp28 atCharacterIndex:(unsigned int)fp32;
- (BOOL)shouldBeSpotlightedInView:(id)fp8;
- (void)mouseEntered:(id)fp8;
- (void)delayedMouseEntered:(id)fp8;
- (void)mouseExited:(id)fp8;
- (void)otherAtomBecameSpotlighted:(id)fp8;
- (id)accessibilityAttributeNames;
- (id)accessibilityAttributeValue:(id)fp8;
- (BOOL)accessibilityIsAttributeSettable:(id)fp8;
- (id)accessibilityActionNames;
- (id)accessibilityActionDescription:(id)fp8;
- (void)accessibilityPerformAction:(id)fp8;
- (void)showMenu;

@end

