/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSFileWrapper.h"

@class NSData, NSString;

@interface ArchiveFileWrapper : NSFileWrapper
{
    NSData *_archiveData;
    int _archiveType;
    NSFileWrapper *_realFileWrapper;
    NSString *_quarantinePath;
}

- (void)dealloc;
- (void)finalize;
- (id)initWithData:(id)fp8 archiveType:(int)fp12;
- (BOOL)writeToFile:(id)fp8 atomically:(BOOL)fp12 updateFilenames:(BOOL)fp16;
- (id)expandQuarantined;
- (void)removeQuarantine;
- (unsigned int)approximateSize;
- (BOOL)isRegularFile;
- (BOOL)isDirectory;
- (BOOL)isSymbolicLink;
- (id)serializedRepresentation;
- (id)addFileWrapper:(id)fp8;
- (void)removeFileWrapper:(id)fp8;
- (id)fileWrappers;
- (id)keyForFileWrapper:(id)fp8;
- (id)addFileWithPath:(id)fp8;
- (id)addRegularFileWithContents:(id)fp8 preferredFilename:(id)fp12;
- (id)addSymbolicLinkWithDestination:(id)fp8 preferredFilename:(id)fp12;
- (id)preferredFilename;
- (void)getCompressedData:(id *)fp8 archiveType:(int *)fp12;

@end

