/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, NSView;

@interface AttachmentDragSession : NSObject
{
    NSView *_sourceView;
    NSMutableArray *_attachments;
}

- (void)dealloc;
- (id)retain;
- (id)autorelease;
- (void)release;
- (id)initWithSourceView:(id)fp8 attachments:(id)fp12;
- (id)sourceView;
- (id)attachments;
- (BOOL)startDragFromPoint:(struct _NSPoint)fp8 event:(id)fp16 image:(id)fp20;
- (unsigned int)draggingSourceOperationMaskForLocal:(BOOL)fp8;
- (void)draggedImage:(id)fp8 beganAt:(struct _NSPoint)fp12;
- (void)draggedImage:(id)fp8 endedAt:(struct _NSPoint)fp12 operation:(unsigned int)fp20;
- (void)draggedImage:(id)fp8 movedTo:(struct _NSPoint)fp12;
- (BOOL)ignoreModifierKeysWhileDragging;
- (id)namesOfPromisedFilesDroppedAtDestination:(id)fp8;
- (void)pasteboard:(id)fp8 provideDataForType:(id)fp12;

@end

