/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSObject.h"

@class NSManagedObjectContext;

@interface BookmarksManager : NSObject
{
    NSManagedObjectContext *_managedObjectContext;
}

+ (id)_sharedPersistentStoreCoordinator;
+ (id)_createManagedObjectModel;
- (void)dealloc;
- (id)init;
- (void)_configureTransientFeedContext;
- (void)addAllRSSFeedsIfNecessary;
- (id)subscribedFeeds;
- (unsigned int)countOfSubscribedFeeds;
- (void)saveTransientFeedChanges;
- (void)discardTransientFeedChanges;
- (BOOL)updateContextWithChanges:(id)fp8;
- (void)clearTransientFeedContext;
- (id)transientFeedContext;
- (void)_setContext:(id)fp8;
- (id)addBookmarkWithSyncID:(id)fp8;
- (id)addFolderWithSyncID:(id)fp8 checkIfExists:(BOOL)fp12;
- (id)bookmarkWithSyncID:(id)fp8;
- (id)folderWithSyncID:(id)fp8;
- (id)addBookmarkWithURL:(id)fp8;
- (id)addSubscribedBookmarkWithURL:(id)fp8 name:(id)fp12;
- (id)bookmarksWithURL:(id)fp8;
- (id)bookmarkURLWithName:(id)fp8;
- (id)_itemsWithValue:(id)fp8 forKey:(id)fp12 entity:(id)fp16;
- (BOOL)setBookmarksWithURL:(id)fp8 isSubscribed:(BOOL)fp12 shouldDisplayUnderInbox:(BOOL)fp16;
- (BOOL)deleteBookmarkWithSyncID:(id)fp8;
- (BOOL)_deleteBookmark:(id)fp8;
- (BOOL)deleteFolderWithSyncID:(id)fp8;
- (BOOL)_deleteFolder:(id)fp8;
- (void)deleteAllBookmarks;
- (void)deleteAllFolders;
- (id)_allItemsForEntity:(id)fp8;
- (void)setSyncCount:(id)fp8;
- (id)syncCount;

@end

