/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSOperation.h"

@interface ConcurrentOperation : NSOperation
{
    struct {
        unsigned int isExecuting:1;
        unsigned int isFinished:1;
        unsigned int performOnMainThread:1;
        unsigned int performOnBackgroundThread:1;
        unsigned int manuallyMarkCompletion:1;
    } _flags;
}

- (BOOL)isConcurrent;
- (BOOL)isExecuting;
- (void)setExecuting:(BOOL)fp8;
- (BOOL)isFinished;
- (void)setFinished:(BOOL)fp8;

@end

