/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "DOMRange.h"

@interface DOMRange (ToDoExtras)
- (id)entireTodos;
- (BOOL)_hasToDoElements:(id)fp8 partialOK:(BOOL)fp12;
- (id)enclosingToDoElement;
- (BOOL)isWithinToDo;
- (BOOL)containsAnyToDos;
- (BOOL)containsEntireToDos;
- (id)anyTodoElements;
- (id)entireTodoElements;
- (BOOL)containsToDoCheckbox:(id)fp8;
- (BOOL)containsToDoCheckboxAndContent:(id)fp8;
- (id)effectiveToDoRangeIfDifferent;
@end

