/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSTextView.h"

@interface DraggingTextView : NSTextView
{
}

+ (id)addressingFieldEditorForObject:(id)fp8;
- (void)dealloc;
- (void)mouseDown:(id)fp8;
- (id)typingAttributes;
- (void)selectAll:(id)fp8;
- (void)setSelectedRange:(struct _NSRange)fp8;
- (void)setSelectedRange:(struct _NSRange)fp8 affinity:(unsigned int)fp16 stillSelecting:(BOOL)fp20;
- (struct _NSRange)selectionRangeForProposedRange:(struct _NSRange)fp8 granularity:(unsigned int)fp16;
- (void)replaceCharactersInRange:(struct _NSRange)fp8 withString:(id)fp16;
- (void)layoutManager:(id)fp8 didCompleteLayoutForTextContainer:(id)fp12 atEnd:(BOOL)fp16;
- (void)delayedLayoutInvalidation:(id)fp8;
- (void)doCommandBySelector:(SEL)fp8;
- (BOOL)prepareForDragOperation:(id)fp8;
- (BOOL)readSelectionFromPasteboard:(id)fp8 type:(id)fp12;
- (id)readablePasteboardTypes;
- (id)writablePasteboardTypes;
- (id)dragImageForSelectionWithEvent:(id)fp8 origin:(struct _NSPoint *)fp12;
- (unsigned int)draggingSourceOperationMaskForLocal:(BOOL)fp8;
- (BOOL)writeSelectionToPasteboard:(id)fp8 type:(id)fp12;
- (id)acceptableDragTypes;
- (BOOL)dragSelectionWithEvent:(id)fp8 offset:(struct _NSSize)fp12 slideBack:(BOOL)fp20;
- (void)draggedImage:(id)fp8 endedAt:(struct _NSPoint)fp12 operation:(unsigned int)fp20;
- (id)searchString;
- (struct _NSRange)selectedSearchRange;
- (void)showSearchResultsRange:(struct _NSRange)fp8;
- (id)menuForEvent:(id)fp8;
- (id)attachmentForPoint:(struct _NSPoint)fp8;
- (id)attachmentForEvent:(id)fp8;
- (struct _NSRect)_cellFrameForAttachment:(id)fp8 atCharIndex:(int)fp12;
- (void)concludeDragOperation:(id)fp8;
- (unsigned int)draggingEntered:(id)fp8;
- (unsigned int)draggingUpdated:(id)fp8;
- (void)draggingExited:(id)fp8;
- (BOOL)performDragOperation:(id)fp8;

@end

