/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSWindowController.h"

@class NSButton, NSProgressIndicator, NSTextField;

@interface DynamicErrorWindowController : NSWindowController
{
    NSTextField *_message;
    NSTextField *_explanation;
    NSButton *_leftButton;
    NSProgressIndicator *_progressIndicator;
    NSButton *_rightButton;
    NSButton *_helpButton;
    int _diagnosisCode;
    double _distanceToRightEdge;
    double _distanceBetweenButtons;
    double _distanceToBottomEdge;
    double _distanceFromProgresBarToButtons;
    double _progressIndicatorHeight;
    // Error parsing type: @"<DynamicErrorWindowDelegate>", name: _delegate
}

- (id)initWithDelegate:(id)fp8;
- (void)dealloc;
- (void)updateTextFieldHeightForNewContent:(id)fp8;
- (void)updateTextField:(id)fp8 withText:(id)fp12 belowControl:(id)fp16;
- (void)collectBasicWindowMetrics;
- (void)relocateButton:(id)fp8 relativeTo:(float)fp12;
- (void)awakeFromNib;
- (void)setDelegate:(id)fp8;
- (void)updateWindowLayout;
- (void)errorDiagnosedAs:(int)fp8;
- (void)leftActionSelected:(id)fp8;
- (void)rightActionSelected:(id)fp8;

@end

