/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "EmailImporter.h"

@interface FilesystemEmailImporter : EmailImporter
{
    char *fromSpaceDelimiter;
}

- (id)prepareForImport;
- (float)progressValueForMailboxAtPath:(id)fp8;
- (void)processUserSelection;
- (void)readMailbox:(id)fp8 intoURL:(id)fp12;
- (id)pathExtension;
- (char *)fromString;
- (BOOL)isValidMailbox:(id)fp8;
- (void)sniffLineDelimiterFromData:(id)fp8;
- (void)verifyFromSpaceHeaderForScanner:(id)fp8 dataLength:(int)fp12;

@end

