/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import <Message/IMAPMessage.h>

@class MessageHeaders, NSData;

@interface IMAPMessageWithCache : IMAPMessage
{
    NSData *_messageData;
    MessageHeaders *_headers;
}

- (void)dealloc;
- (id)messageData;
- (id)messageDataIncludingFromSpace:(BOOL)fp8 newDocumentID:(id)fp12;
- (void)setMessageData:(id)fp8;
- (BOOL)isMessageContentsLocallyAvailable;
- (id)headers;
- (void)setHeaders:(id)fp8;
- (id)headerData;

@end

