/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import <Message/IMAPConnection.h>

@interface IMAPConnection (MFPrivate)
- (BOOL)_readDataOfLength:(int)fp8 intoData:(id)fp12 error:(id *)fp16;
- (BOOL)_isFetchResponseValid:(id)fp8;
- (BOOL)_correctMailboxIsSelectedForOperation:(id)fp8;
- (id)_responseFromSendingOperation:(id)fp8;
- (BOOL)_commandShouldBeSentAgainOnError:(int)fp8;
- (BOOL)_isTemporaryError:(id)fp8;
- (void)_setError:(id)fp8 forCommand:(id)fp12;
- (BOOL)_recordUntaggedResponse:(id)fp8 forOperation:(id)fp12;
- (BOOL)_recordUntaggedResponse:(id)fp8 forOperation:(id)fp12 exists:(unsigned int *)fp16;
- (void)_recordResponse:(id)fp8 forOperation:(id)fp12;
- (BOOL)_recordMailboxResponse:(id)fp8 forOperation:(id)fp12;
- (BOOL)_recordMailboxResponse:(id)fp8 forOperation:(id)fp12 exists:(unsigned int *)fp16;
@end

