/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import <Message/IMAPClientUIDOperation.h>

@class NSArray, NSMutableIndexSet;

@interface IMAPClientUIDSearchOperation : IMAPClientUIDOperation
{
    NSArray *_terms;
    NSMutableIndexSet *_matchingUIDs;
}

- (void)dealloc;
- (id)initWithMailboxName:(id)fp8 range:(CDAnonymousStruct2)fp12 terms:(id)fp20;
- (const char *)commandTypeCString;
- (id)createCommandDataForLiteralPlus:(BOOL)fp8;
- (id)_createArgumentForSearchTerm:(id)fp8 isLiteral:(char *)fp12;
- (BOOL)executeOnConnection:(id)fp8;
- (id)matchingUIDs;
- (void)setMatchingUIDs:(id)fp8;
- (id)terms;
- (void)setTerms:(id)fp8;

@end

