/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import <Message/IMAPAggregateClientOperation.h>

@interface IMAPAggregateFetchUIDOperation : IMAPAggregateClientOperation
{
    unsigned int _expectedSize;
}

- (id)initWithOperations:(id)fp8 expectedSize:(unsigned long)fp12;
- (const char *)commandTypeCString;
- (void)cleanupAfterCompletion;
- (unsigned long)expectedSize;
- (void)setExpectedSize:(unsigned long)fp8;

@end

