/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import <Message/ConcurrentOperation.h>

@class IMAPGateway, NSCondition;

@interface IMAPClientOperation : ConcurrentOperation
{
    int _commandType;
    IMAPGateway *_gateway;
    NSCondition *_finishCondition;
    int _completionState;
}

+ (id)IMAPCreateQuotedString:(id)fp8;
+ (id)IMAPCreateStringForMailboxName:(id)fp8;
+ (id)IMAPNeedsLiteralCharacterSet;
+ (id)_IMAPNeedsQuoteCharacterSet;
- (void)dealloc;
- (id)init;
- (id)initWithCommandType:(int)fp8;
- (const char *)commandTypeCString;
- (BOOL)alwaysAllowToComplete;
- (int)requiredConnectionState;
- (int)composition;
- (BOOL)isWaitingToStart;
- (id)activityString;
- (id)detailsString;
- (void)cleanupAfterCompletion;
- (BOOL)completedSuccessfully;
- (void)increasePriority;
- (void)start;
- (void)main;
- (void)setupForExecution;
- (void)teardownFromExecution;
- (BOOL)executeOnConnection:(id)fp8;
- (void)setFinished:(BOOL)fp8;
- (id)description;
- (int)completionState;
- (void)setCompletionState:(int)fp8;
- (id)finishCondition;
- (void)setFinishCondition:(id)fp8;
- (id)gateway;
- (void)setGateway:(id)fp8;
- (int)commandType;
- (void)setCommandType:(int)fp8;

@end

