/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "TemporaryAttachmentOpener.h"

@interface InvitationAttachmentOpener : TemporaryAttachmentOpener
{
    BOOL _openImmediately;
}

- (id)initWithAttachments:(id)fp8 openImmediately:(BOOL)fp12;
- (void)_saveAttachmentsToICalCaches:(id)fp8;
- (void)beginSaveOfAttachments:(id)fp8 toTemporaryFolderWithName:(id)fp12 taskName:(id)fp16;

@end

