/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSObject.h"

@class ActivityAggregate, ActivityMonitor, Library;

@interface LibraryUpgrader : NSObject
{
    Library *_library;
    unsigned int _majorVersion;
    unsigned int _minorVersion;
    ActivityMonitor *_monitor;
    ActivityAggregate *_activity;
    id _delegate;
    struct sqlite3 *_upgraderWriterDB;
    BOOL _shouldFlushDB;
}

- (id)initWithLibrary:(id)fp8;
- (id)delegate;
- (void)setDelegate:(id)fp8;
- (void)dealloc;
- (void)dispose;
- (id)monitor;
- (void)setMonitor:(id)fp8;
- (id)activity;
- (void)setActivity:(id)fp8;
- (id)status;
- (void)setStatus:(id)fp8;
- (void)setStatusOnMainThread:(id)fp8;
- (void)getVersionInfo;
- (void)executeSQL:(id)fp8 transacted:(BOOL)fp12;
- (BOOL)updateMinorVersion:(unsigned int)fp8 usingDB:(struct sqlite3 *)fp12;
- (void)executeSQL:(id)fp8 updateMinorVersion:(unsigned int)fp12;
- (void)bootstrapVersioningEngine;
- (void)vacuum;
- (void)dropTriggers;
- (void)createTriggers;
- (BOOL)canRun:(id *)fp8;
- (BOOL)needsRun;
- (void)upgradeSchema;
- (void)postUpgradeDataMigration;
- (void)incrementProgressIndicator;
- (void)run;
- (void)notifyDelegate:(id)fp8;
- (void)addMessageType:(int)fp8;
- (void)addDocumentID:(int)fp8;
- (void)addPositionToRecipients:(int)fp8;
- (void)populateRecipientPosition:(int)fp8;
- (void)giveDraftsUniqueIDs:(int)fp8;
- (BOOL)replaceRecipientsAddressRowID:(long)fp8 withRowID:(long)fp12 usingDB:(struct sqlite3 *)fp16;
- (BOOL)replaceMessagesSenderRowID:(long)fp8 withRowID:(long)fp12 usingDB:(struct sqlite3 *)fp16;
- (BOOL)replaceAddressRowID:(long)fp8 withRowID:(long)fp12 usingDB:(struct sqlite3 *)fp16;
- (long)getSurvivingRowIDForDuplicatedRowID:(long)fp8 dupAddress:(char *)fp12 dupComment:(char *)fp16 usingDB:(struct sqlite3 *)fp20;
- (void)upgradeEmailAddressROWIDsToCaseInsensitive:(struct sqlite3 *)fp8;
- (void)createCaseInsensitiveTemporaryAddressTable;
- (void)replaceAddressesTableWithAddressesTemp:(int)fp8 usingDB:(struct sqlite3 *)fp12;
- (void)upgradeFrom4_10To4_11:(int)fp8;
- (void)_moveUnreadCountsOutOfAttributes;
- (void)moveUnreadCountsOutOfAttributes:(int)fp8;
- (void)upgradeColumnWidthPrefs:(int)fp8;
- (void)addDateCreatedColumnOnMessages:(int)fp8;
- (void)removeToDoIDUniqueRestriction:(int)fp8;
- (void)stampCurrentMinorVersion;
- (struct sqlite3 *)getReaderDB;
- (void)unlockReaderDB:(struct sqlite3 *)fp8;
- (struct sqlite3 *)getWriterDB;
- (void)unlockWriterDB:(struct sqlite3 *)fp8;
- (void)flushDBWhenDone;
- (void)_dispose;

@end

