/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSObject.h"

@class ActivityMonitor, NSButton, NSProgressIndicator, NSTextField, NSView;

@interface LoadingOverlay : NSObject
{
    NSView *_overlayView;
    NSProgressIndicator *_progressIndicator;
    NSTextField *_statusMessageField;
    NSButton *_cancelButton;
    ActivityMonitor *_monitor;
    id _modalDelegate;
}

- (id)initWithModalDelegate:(id)fp8;
- (void)dealloc;
- (void)displayInSuperview:(id)fp8;
- (void)displayInSuperviewAfterDelay:(id)fp8;
- (void)setActivityMonitor:(id)fp8;
- (void)setStatusMessage:(id)fp8;
- (id)statusMessage;
- (void)showCancelButton:(BOOL)fp8;
- (void)activityEnded:(id)fp8;
- (void)cancel:(id)fp8;
- (id)modalDelegate;
- (void)setModalDelegate:(id)fp8;
- (id)overlayView;
- (id)activityMonitor;

@end

