/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSView.h"

@class MailToolbarSpaceItemWithPin;

@interface MailToolbarSpace : NSView
{
    MailToolbarSpaceItemWithPin *_spaceItem;
}

- (id)initWithSize:(struct _NSSize)fp8 forSpaceItem:(id)fp16;
- (void)drawRect:(struct _NSRect)fp8;
- (void)viewDidMoveToWindow;

@end

