/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSScroller.h"

@class NSImage;

@interface MailScroller : NSScroller
{
    NSImage *paddingImage;
    NSImage *hiddenImage;
    NSImage *slotStartImage;
    NSImage *slotMiddleImage;
    NSImage *slotEndImage;
    NSImage *knobStartImage;
    NSImage *knobMiddleImage;
    NSImage *knobEndImage;
    float startPadding;
    float endPadding;
    BOOL isVertical;
}

- (id)initWithFrame:(struct _NSRect)fp8 isVertical:(BOOL)fp24;
- (void)dealloc;
- (struct _NSRect)_rectWithRect:(struct _NSRect)fp8 offset:(float)fp24 length:(float)fp28;
- (float)_getLengthFromSize:(struct _NSSize)fp8;
- (float)_getLengthFromImage:(id)fp8;
- (struct _NSRect)_drawingRectForCustomPart:(int)fp8;
- (struct _NSRect)_drawingRectForPart:(unsigned int)fp8;
- (struct _NSRect)rectForPart:(unsigned int)fp8;
- (BOOL)isUseful;
- (void)drawImage:(id)fp8 asPart:(int)fp12 withDirtyRect:(struct _NSRect)fp16;
- (void)drawRect:(struct _NSRect)fp8;
- (void)setImagesFlipped:(BOOL)fp8;
- (BOOL)isOpaque;
- (BOOL)isVertical;
- (void)setIsVertical:(BOOL)fp8;
- (float)endPadding;
- (void)setEndPadding:(float)fp8;
- (float)startPadding;
- (void)setStartPadding:(float)fp8;
- (id)knobEndImage;
- (void)setKnobEndImage:(id)fp8;
- (id)knobMiddleImage;
- (void)setKnobMiddleImage:(id)fp8;
- (id)knobStartImage;
- (void)setKnobStartImage:(id)fp8;
- (id)slotEndImage;
- (void)setSlotEndImage:(id)fp8;
- (id)slotMiddleImage;
- (void)setSlotMiddleImage:(id)fp8;
- (id)slotStartImage;
- (void)setSlotStartImage:(id)fp8;
- (id)hiddenImage;
- (void)setHiddenImage:(id)fp8;
- (id)paddingImage;
- (void)setPaddingImage:(id)fp8;

@end

