/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "MailApp.h"

@interface MailApp (AppleEvents)
- (void)_registerAppleEventQueue;
- (void)_registerAppleEventHandlers;
- (void)_unregisterAppleEventHandlers;
- (void)queueAppleEvent:(id)fp8 replyEvent:(id)fp12;
- (void)handleGURLAppleEvent:(id)fp8 replyEvent:(id)fp12;
- (void)handleMailWebPageEvent:(id)fp8 replyEvent:(id)fp12;
- (void)handleMailWebLinkEvent:(id)fp8 replyEvent:(id)fp12;
- (void)handlePeabodyEvent:(id)fp8 replyEvent:(id)fp12;
@end

