/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSObject.h"

@class MailboxUid, MailboxesChooser, NSButton, NSMutableArray, NSMutableDictionary, NSMutableSet, NSPopUpButton, NSTextField, NSView, NSWindow;

@interface MailboxesController : NSObject
{
    NSMutableArray *_accountsWithChildren;
    NSWindow *_newMailboxPanel;
    NSTextField *_newMailboxField;
    NSTextField *_newMailboxMessage;
    NSButton *_newMailboxOKButton;
    NSPopUpButton *_mailboxPopUp;
    MailboxesChooser *_mailboxesChooser;
    NSWindow *_newCalendarPanel;
    NSTextField *_newCalendarField;
    NSTextField *_newCalendarMessage;
    NSButton *_newCalendarOKButton;
    NSView *_exportChildrenView;
    NSButton *_exportChildrenCheckbox;
    id _currentMailboxSelectionOwner
    BOOL _currentTransferIsCopy;
    MailboxUid *_selectedParent;
    MailboxUid *_currentTransferMailbox;
    BOOL smartMailboxesNeedSaving;
    BOOL isSavingSyncResults;
    int currentFileVersion;
    id _menuEnabler;
    SEL _menuEnablerSelector;
    NSMutableSet *rootMailboxMenus;
    NSMutableDictionary *_contextualMenus;
}

+ (id)iconForMailboxUid:(id)fp8 smallSize:(BOOL)fp12;
+ (id)filteredMailUserInfoDictionary:(id)fp8;
+ (id)mergeOldMailUserInfoDictionary:(id)fp8 withSyncChanges:(id)fp12;
- (id)menuForMailboxUid:(id)fp8;
- (id)init;
- (void)dealloc;
- (void)awakeFromNib;
- (void)readDefaults;
- (void)saveDefaults;
- (id)accountsWithChildren;
- (void)_reloadAccountsWithChildren;
- (void)mailboxListingDidChange:(id)fp8;
- (void)setCurrentTransferMailbox:(id)fp8 deletedOriginals:(BOOL)fp12;
- (id)currentTransferMailbox;
- (BOOL)currentTransferDeletesOriginals;
- (id)mailboxSelectionOwner;
- (void)setMailboxSelectionOwnerFrom:(id)fp8;
- (void)resignMailboxSelectionOwnerFor:(id)fp8;
- (id)mailboxSelectionOwnerFromSender:(id)fp8;
- (BOOL)validateMenuItem:(id)fp8;
- (void)_synchronouslyCreateNewMailboxWithName:(id)fp8 parent:(id)fp12;
- (void)_configureNewMailboxPanelForMailbox:(id)fp8;
- (void)newMailbox:(id)fp8;
- (void)newMailboxSheetDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (void)_synchronouslyCreateNewCalendarWithName:(id)fp8 parent:(id)fp12;
- (void)_configureNewCalendarPanelForAccount:(id)fp8;
- (void)newCalendar:(id)fp8;
- (void)newCalendarSheetDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (void)newSmartMailbox:(id)fp8;
- (void)editSmartMailbox:(id)fp8;
- (void)duplicateSmartMailbox:(id)fp8;
- (void)newFolder:(id)fp8;
- (void)newGroup:(id)fp8;
- (void)mailboxPopUpChanged:(id)fp8;
- (void)_synchronouslyDeleteMailboxes:(id)fp8;
- (void)deleteMailbox:(id)fp8;
- (void)_synchronouslySetName:(id)fp8 andParent:(id)fp12 forMailboxes:(id)fp16;
- (void)renameMailbox:(id)fp8;
- (void)userEditedMailboxName:(id)fp8;
- (void)_exportMailboxSheetDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(id)fp16;
- (void)_exportMailboxes:(id)fp8 toDir:(id)fp12 includeChildren:(id)fp16;
- (void)exportMailbox:(id)fp8;
- (void)setSpecialMailbox:(id)fp8;
- (void)configureRSSFeeds:(id)fp8;
- (void)toggleShowsUnderInbox:(id)fp8;
- (void)markAllAsRead:(id)fp8;
- (void)_changeReadFlagForMessages:(id)fp8 flag:(BOOL)fp12;
- (id)_unreadMessagesInMailbox:(id)fp8;
- (void)queueUnreadCountUpdate;
- (void)coalesceUnreadCountUpdate;
- (void)libraryMessagesAdded:(id)fp8;
- (void)libraryFlagsChanged:(id)fp8;
- (void)startUnreadCountUpdateWithSequenceNumbers:(id)fp8;
- (void)updateUnreadCountsForSequenceNumber:(id)fp8 librarySequenceNumber:(id)fp12;
- (void)controlTextDidChange:(id)fp8;
- (void)okClicked:(id)fp8;
- (void)cancelClicked:(id)fp8;
- (void)bringUpTransferMenu:(id)fp8;
- (void)_setRootMailboxMenu:(id)fp8;
- (void)menuNeedsUpdate:(id)fp8;
- (BOOL)menuHasKeyEquivalent:(id)fp8 forEvent:(id)fp12 target:(id *)fp16 action:(SEL *)fp20;
- (void)_removeAllItemsFromMenu:(id)fp8;
- (void)resetDynamicMenuContext;
- (void)reallyTearDownDynamicMenus;
- (void)tearDownDynamicMenus:(id)fp8;
- (void)_addMailboxItemsToMenu:(id)fp8 startingFromMailbox:(id)fp12 includeMailboxes:(unsigned int)fp16 selectedMessages:(id)fp20 targetMessageType:(int)fp24;
- (void)_addMailboxItemsToMenu:(id)fp8 startingFromMailbox:(id)fp12;
- (void)setMenuEnabler:(id)fp8 selector:(SEL)fp12;
- (id)_menuItemForMailbox:(id)fp8;
- (void)_addItemsStartingWithMailbox:(id)fp8 toMenu:(id)fp12 withIndentationLevel:(int)fp16 selectedMessages:(id)fp20 targetMessageType:(int)fp24 disableNonStores:(BOOL)fp28;
- (void)addMailboxItemsToMenu:(id)fp8 target:(id)fp12 action:(SEL)fp16 startingAtMailbox:(id)fp20 showUnreadCounts:(BOOL)fp24 includeMailboxes:(unsigned int)fp28 selectedMessages:(id)fp32 targetMessageType:(int)fp36;
- (void)addMailboxItemsToMenu:(id)fp8 target:(id)fp12 action:(SEL)fp16 startingAtMailbox:(id)fp20 showUnreadCounts:(BOOL)fp24 targetMessageType:(int)fp28;
- (void)addMailboxItemsToMenu:(id)fp8 target:(id)fp12 action:(SEL)fp16 includeMailboxes:(unsigned int)fp20 selectedMessages:(id)fp24 targetMessageType:(int)fp28;
- (void)addMailboxItemsToMenu:(id)fp8 target:(id)fp12 action:(SEL)fp16;
- (id)menuItemForMailbox:(id)fp8 target:(id)fp12 action:(SEL)fp16 showUnreadCounts:(BOOL)fp20;
- (BOOL)moveAccount:(id)fp8 toAfterAccount:(id)fp12;
- (BOOL)fileManager:(id)fp8 shouldProceedAfterError:(id)fp12;
- (BOOL)removeAccount:(id)fp8;
- (BOOL)moveMailboxes:(id)fp8 toParentMailbox:(id)fp12;
- (void)_synchronouslyCopyMailboxes:(id)fp8 toParent:(id)fp12 originalParent:(id)fp16;
- (BOOL)copyMailboxes:(id)fp8 toParentMailbox:(id)fp12;
- (BOOL)moveOrCopy:(id)fp8 smartMailboxes:(id)fp12 toIndex:(unsigned int)fp16;
- (void)addSmartMailbox:(id)fp8 select:(BOOL)fp12;
- (void)tentativelyAddSmartMailbox:(id)fp8;
- (void)smartMailboxWasEdited:(id)fp8;
- (void)addSmartMailboxFolder:(id)fp8;
- (void)loadSmartMailboxes;
- (id)smartMailboxes;
- (void)subscribeToRSSFeed:(id)fp8 name:(id)fp12;
- (void)validateAndSubscribeToRSSFeed:(id)fp8;
- (void)nowWouldBeAGoodTimeToTerminate:(id)fp8;
- (id)smartMailboxesPathForFile:(id)fp8;
- (void)saveSmartMailboxes:(id)fp8;
- (void)writeSmartMailboxesToDisk;
- (id)unionedSmartMailboxesFromDisk;
- (id)sortMailboxUids:(id)fp8 withIdentifiers:(id)fp12;
- (id)sortMailboxesDictionaries:(id)fp8 withIdentifiers:(id)fp12;
- (id)readSmartMailboxesFromDisk;
- (id)loadDefaultSmartMailboxes;
- (id)smartMailboxesDictionaryRepresentations;
- (id)smartMailboxesDictionaryRepresentationsFilterSyncData:(BOOL)fp8;
- (id)smartMailboxesFromDictionaryRepresentations:(id)fp8;
- (id)smartMailboxesFromDictionaryRepresentations:(id)fp8 andMergeOldUserInfoFromMailboxes:(BOOL)fp12;
- (void)syncSmartMailboxes;
- (BOOL)dataWillBeSyncedVersion:(id *)fp8 data:(id *)fp12 type:(id)fp16;
- (BOOL)dataWasSyncedVersion:(id)fp8 newData:(id)fp12 acceptedChanges:(id)fp16;

@end

