/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import <Message/MailAccount.h>

@class NSString;

@interface MailCalDAVAccount : MailAccount
{
    NSString *_title;
    BOOL _isBeingDeleted;
}

+ (id)defaultPathNameForAccount;
+ (id)accountTypeString;
- (void)cleanupCalDAVAccountTitleForURLAndPath:(id)fp8;
- (id)initWithTitle:(id)fp8 groupID:(id)fp12;
- (void)dealloc;
- (BOOL)isActive;
- (id)uniqueId;
- (Class)storeClass;
- (Class)todoStoreClass;
- (BOOL)supportsNotes;
- (BOOL)supportsToDos;
- (BOOL)shouldStoreNotesInInbox;
- (id)mailboxPathExtension;
- (BOOL)synchronizesDataWithServer;
- (BOOL)allowsCalendarCreation;
- (BOOL)isEditableByUser;
- (BOOL)canParticipateInRules;
- (BOOL)providesAccountInformation;
- (BOOL)isZeroConfiguration;
- (BOOL)isRemoteAccount;
- (BOOL)hasTrashMailbox;
- (BOOL)supportsAppleScript;
- (BOOL)canMailboxBeDeleted:(id)fp8;
- (BOOL)canCreateNewMailboxes;
- (id)hostname;
- (BOOL)canFetch;
- (BOOL)shouldAutoFetch;
- (BOOL)isOffline;
- (BOOL)canGoOffline;
- (BOOL)shouldMoveDeletedMessagesToTrash;
- (BOOL)canMoveDeletedMessagesToTrash;
- (id)path;
- (void)setIsOffline:(BOOL)fp8;
- (BOOL)rootChildrenCanBePromoted;
- (id)trashMailboxUidCreateIfNeeded:(BOOL)fp8;
- (id)_URLScheme;
- (id)_specialMailboxNameForType:(int)fp8;
- (BOOL)deleteMailbox:(id)fp8;
- (id)_infoForMatchingURL:(id)fp8;
- (void)deleteAccount;
- (BOOL)isBeingDeleted;

@end

