/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import <Message/PerformanceLogger.h>

@class NSMutableArray;

@interface MainPerformanceLogger : PerformanceLogger
{
    NSMutableArray *_subtests;
}

+ (void)startLoggingForArea:(id)fp8 test:(id)fp12;
+ (void)stopLoggingForArea:(id)fp8 test:(id)fp12;
+ (void)logMarker:(id)fp8;
- (void)dealloc;
- (id)addLoggerForSubtest:(id)fp8;
- (id)description;
- (id)subtests;
- (void)setSubtests:(id)fp8;

@end

