/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSConcreteTextStorage.h"

@interface MessageTextStorage : NSConcreteTextStorage
{
    BOOL _isRichText;
    unsigned int _delegateRespondsToAttachmentsAdded:1;
    unsigned int _delegateRespondsToAttachmentsDeleteded:1;
    unsigned int _delegateRespondsToContentWillChange:1;
}

- (id)defaultFont;
- (BOOL)isRichText;
- (void)setRichText:(BOOL)fp8;
- (void)fixParagraphStyleAttributeInRange:(struct _NSRange)fp8;
- (void)fixQuotingDisplayAttributesInRange:(struct _NSRange)fp8;
- (void)replaceCharactersInRange:(struct _NSRange)fp8 withAttributedString:(id)fp16;

@end

