/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSTextContainer.h"

@interface MessageTextContainer : NSTextContainer
{
    struct _NSSize imageSize;
    struct _NSSize linkSize;
}

- (id)initWithContainerSize:(struct _NSSize)fp8;
- (void)setImageSize:(struct _NSSize)fp8;
- (struct _NSSize)imageSize;
- (void)setLinkSize:(struct _NSSize)fp8;
- (struct _NSSize)linkSize;
- (BOOL)isSimpleRectangularTextContainer;
- (BOOL)containsPoint:(struct _NSPoint)fp8;
- (struct _NSRect)lineFragmentRectForProposedRect:(struct _NSRect)fp8 sweepDirection:(unsigned int)fp24 movementDirection:(unsigned int)fp28 remainingRect:(struct _NSRect *)fp32;

@end

