/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "ComposeBackEnd.h"

@class LibraryMessage, MailAccount, NSDictionary, NSSet, NSString;

@interface NoteComposeBackEnd : ComposeBackEnd
{
    MailAccount *_account;
    NSString *_summary;
    NSString *_creationDateHeader;
    LibraryMessage *_associatedMessage;
    NSString *_backgroundColor;
    NSDictionary *_onLoadToDosByID;
    NSDictionary *_onLoadToDosByPreviousID;
    NSSet *_onLoadDeletedToDoIDs;
}

+ (id)supportedMailboxUidTypes;
- (void)setStateFromBackEnd:(id)fp8;
- (id)summary;
- (void)setSummary:(id)fp8;
- (id)sender;
- (BOOL)preserveAddedArchiveBody;
- (id)backgroundColor;
- (BOOL)defaultFormatIsRich;
- (id)account;
- (id)mailboxUidCreateIfNeeded:(BOOL)fp8;
- (id)generatedSubject;
- (void)setSubject:(id)fp8;
- (void)_backgroundSaveEnded:(id)fp8;
- (void)updateToDosInContent:(id)fp8 documentID:(id)fp12 referencedMessageID:(id)fp16;
- (id)htmlDocumentForSave;
- (id)htmlStringFromRange:(id)fp8 htmlDocument:(id)fp12 removeCustomAttributes:(BOOL)fp16 convertObjectsToImages:(BOOL)fp20 convertEditableElements:(BOOL)fp24;
- (id)outgoingMessageUsingWriter:(id)fp8 contents:(id)fp12 headers:(id)fp16 isDraft:(BOOL)fp20;
- (id)saveTaskName;
- (BOOL)isPaperless;
- (BOOL)hasChanges;
- (BOOL)saveMessage;
- (id)todoDocumentID;
- (BOOL)isEditingMessage:(id)fp8;
- (void)updateDocumentReference:(id)fp8;
- (void)finishPreparingContentWithEditorSettings:(id)fp8;
- (id)description;
- (void)dealloc;
- (id)onLoadDeletedToDoIDs;
- (void)setOnLoadDeletedToDoIDs:(id)fp8;
- (id)onLoadToDosByPreviousID;
- (void)setOnLoadToDosByPreviousID:(id)fp8;
- (id)onLoadToDosByID;
- (void)setOnLoadToDosByID:(id)fp8;
- (void)setBackgroundColor:(id)fp8;
- (id)creationDateHeader;
- (void)setCreationDateHeader:(id)fp8;
- (id)associatedMessage;
- (void)setAssociatedMessage:(id)fp8;
- (void)setAccount:(id)fp8;

@end

