/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSView.h"

@class WebView;

@interface NoteWindowContentView : NSView
{
    WebView *_webView;
}

- (id)initWithFrame:(struct _NSRect)fp8;
- (void)awakeFromNib;

@end

