/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSAlert.h"

@interface NSAlert (MFErrorSupport)
+ (id)createAlertForError:(id)fp8 defaultButton:(id)fp12 alternateButton:(id)fp16 otherButton:(id)fp20;
- (void)setEscapeKeyEquivalentOnButtonWithTitle:(id)fp8;
@end

