/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSAttributedString.h"

@interface NSAttributedString (plain_or_rich)
- (id)attachments;
- (id)attachmentsInRange:(struct _NSRange)fp8;
- (id)mimeTextAttachments;
- (struct _NSRange)rangeOfAttachment:(id)fp8;
- (BOOL)containsAttachments;
- (BOOL)containsAttachmentsThatCouldConfuseWindowsClients;
- (BOOL)containsRichTextInRange:(struct _NSRange)fp8;
- (BOOL)containsRichText;
- (BOOL)containsOnlyAttachments;
@end

