/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSBundle.h"

@interface NSBundle (MessageFrameworkAdditions)
+ (BOOL)localization:(id)fp8 isPreferredOverLocalization:(id)fp12;
+ (id)syncBundle;
- (BOOL)loadNibNamed:(id)fp8 owner:(id)fp12;
- (id)localizedShortVersion;
- (void)createLocalization:(id)fp8;
@end

