/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSUserDefaults.h"

@interface NSUserDefaults (FontAdditions)
- (id)mailboxListFont;
- (void)setMailboxListFont:(id)fp8;
- (id)noteFont;
- (void)setNoteFont:(id)fp8;
- (id)messageListFont;
- (void)setMessageListFont:(id)fp8;
- (id)mailboxListFontName;
- (float)mailboxListFontSize;
- (id)messageListFontName;
- (float)messageListFontSize;
- (void)setMessageListFontName:(id)fp8;
- (void)setMessageListFontSize:(float)fp8;
- (id)defaultNoteFontName;
- (id)defaultNoteFontSize;
- (id)defaultNoteFontAttributes;
- (id)defaultNoteMessageListFontName;
@end

