/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "OldCompletionController.h"

@interface OldCompletionController (AsyncLookupOfDirServicesServer)
- (void)initDirectoryServicesServer;
- (void)askABForDirectoryServicesServer:(id)fp8;
- (void)directoryServicesServerLookupCompleted;
- (void)directoryServicesServerLookupCancelled:(id)fp8;
- (void)setDirectoryServicesServer:(id)fp8;
- (id)directoryServicesServer;
@end

