/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "GenericAttachmentFetcher.h"

@interface PhotoExporter : GenericAttachmentFetcher
{
}

+ (BOOL)isPhotoFile:(id)fp8;
+ (void)exportPhotoAttachments:(id)fp8;
- (void)_exportAttachments:(id)fp8;
- (void)downloadedAllAttachments;

@end

