/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSTextAttachmentCell.h"

@interface ResizingTextAttachmentCell : NSTextAttachmentCell
{
    BOOL stretchImageToFitCellFrame;
}

- (void)setStretchImageToFitCellFrame:(BOOL)fp8;
- (void)drawWithFrame:(struct _NSRect)fp8 inView:(id)fp24;

@end

