/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "WebMessageDisplay.h"

@interface RSSArticleDisplay : WebMessageDisplay
{
}

+ (id)copyDocumentForMessage:(id)fp8 viewingState:(id)fp12;
+ (Class)documentClass;
- (id)webView:(id)fp8 identifierForInitialRequest:(id)fp12 fromDataSource:(id)fp16;
- (void)webView:(id)fp8 resource:(id)fp12 didFinishLoadingFromDataSource:(id)fp16;

@end

