/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSObject.h"

@class ActivityMonitor, InvocationQueue, NSConditionLock, NSDate, NSMutableDictionary, NSPort, NSString, NSThread, NSTimer, NSURL, PSClient;

@interface RSSInterchange : NSObject
{
    PSClient *_syndicationManager;
    NSConditionLock *_syndicationLock;
    NSThread *_syndicationThread;
    NSPort *_syndicationPort;
    ActivityMonitor *_activityMonitor;
    InvocationQueue *_delegateHandlerQueue;
    NSMutableDictionary *_feedsBeingUpdated;
    NSMutableDictionary *_updatedFeeds;
    BOOL _didReceiveArticles;
    NSString *_feedName;
    NSURL *_autodiscoveredURL;
    BOOL _waitingForFeedName;
    NSDate *_fetchDate;
    unsigned int _numberOfOutstandingFeedWrites;
    NSTimer *_manualCheckTimer;
    BOOL _manualCheckIsAllowed;
    BOOL _shareDeletionInterval;
    BOOL _fatalError;
}

+ (id)sharedInstance;
- (void)dealloc;
- (id)init;
- (void)fetchTemporaryFeedAtURL:(id)fp8 getName:(id *)fp12 getAutodiscoveredURL:(id *)fp16;
- (BOOL)_performSynchronousRefreshWithFeed:(id)fp8;
- (void)_setTemporaryFeedInformationFromURL:(id)fp8;
- (void)_setFeedName:(id)fp8;
- (id)_feedName;
- (void)_setAutodiscoveredURL:(id)fp8;
- (id)_autodiscoveredURL;
- (void)subscribeToFeedWithURL:(id)fp8;
- (void)_subscribeToFeedWithURL:(id)fp8;
- (void)unsubscribeToFeedWithURL:(id)fp8;
- (void)_unsubscribeToFeedWithURL:(id)fp8;
- (void)restoreFeedURLsForFeedInfo:(id)fp8;
- (void)_restoreFeedURLsForFeedInfo:(id)fp8;
- (void)setFetchFrequency:(int)fp8;
- (void)setDeletionFrequency:(int)fp8;
- (void)_setFrequency:(int)fp8 forMsgid:(int)fp12;
- (void)_setFetchFrequency:(int)fp8;
- (void)_setDeletionFrequency:(int)fp8;
- (void)setFlagsFromDictionary:(id)fp8 forMessages:(id)fp12;
- (void)_setFlagsFromDictionary:(id)fp8 forRemoteIDs:(id)fp12;
- (BOOL)updateAllFeeds;
- (void)_updateAllFeeds;
- (void)_synchronize;
- (void)updateFeedWithURL:(id)fp8;
- (void)_updateFeedWithURL:(id)fp8;
- (void)updateLastDateFetchedForNewArticles:(BOOL)fp8;
- (void)removeOldArticles;
- (void)_removeOldArticles;
- (void)_runManager;
- (void)handlePortMessage:(id)fp8;
- (void)_allowManualFeedCheck;
- (void)_setManualCheckTimer:(id)fp8;
- (id)_manualCheckTimer;
- (void)feedDidBeginRefresh:(id)fp8;
- (void)feedDidEndRefresh:(id)fp8;
- (void)feed:(id)fp8 didAddEntries:(id)fp12;
- (void)feed:(id)fp8 didUpdateEntries:(id)fp12;
- (void)feed:(id)fp8 didChangeFlagsInEntries:(id)fp12;
- (void)_setSyndicationManager:(id)fp8;
- (void)_setSyndicationLock:(id)fp8;
- (void)_setSyndicationPort:(id)fp8;
- (void)_configureSyndicationManager;
- (void)_setFetchDate:(id)fp8;
- (void)_writeDate;
- (id)_storeBeingUpdatedWithIdentifier:(id)fp8;
- (void)_delegateFeedDidEndRefresh:(id)fp8;
- (id)_createPortComponentsForFeedURL:(id)fp8;
- (id)_mailboxForFeed:(id)fp8;
- (void)_refreshFeed:(id)fp8;
- (id)_messageForError:(id)fp8;

@end

