/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "MessageTextStorage.h"

@interface ScriptableMessageTextStorage : MessageTextStorage
{
}

- (void)replaceCharactersInRange:(struct _NSRange)fp8 withAttributedString:(id)fp16;
- (void)addAttribute:(id)fp8 value:(id)fp12 range:(struct _NSRange)fp16;
- (void)setAttributes:(id)fp8 range:(struct _NSRange)fp12;

@end

