/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSSearchField.h"

@interface SearchTextField : NSSearchField
{
    struct {
        unsigned int dontDisplaySearchScope:1;
        unsigned int reserver:31;
    } _flags;
}

- (void)awakeFromNib;
- (BOOL)isDisplayingGraySearchScope;
- (void)displayGraySearchScopeIfAppropriate:(id)fp8;
- (void)removeGraySearchScope;
- (BOOL)becomeFirstResponder;
- (void)selectText:(id)fp8;
- (void)_cancelKey:(id)fp8;
- (unsigned int)draggingEntered:(id)fp8;
- (BOOL)performDragOperation:(id)fp8;

@end

