/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSToolbarItemGroup.h"

@class NSMutableArray;

@interface SegmentedToolbarItem : NSToolbarItemGroup
{
    NSMutableArray *alternateLabels;
}

- (id)initWithItemIdentifier:(id)fp8;
- (void)dealloc;
- (void)setAlternateLabels:(id)fp8;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)configureForDisplayMode:(unsigned int)fp8 andSizeMode:(unsigned int)fp12;
- (void)validate;
- (id)control;
- (void)controlAction:(id)fp8;
- (void)setSegmentCount:(int)fp8;
- (id)methodSignatureForSelector:(SEL)fp8;
- (void)forwardInvocation:(id)fp8;
- (id)labelForSegment:(int)fp8;
- (void)setLabel:(id)fp8 forSegment:(int)fp12;
- (id)alternateLabelForSegment:(int)fp8;
- (void)setAlternateLabel:(id)fp8 forSegment:(int)fp12;
- (id)paletteLabelForSegment:(int)fp8;
- (void)setPaletteLabel:(id)fp8 forSegment:(int)fp12;
- (SEL)actionForSegment:(int)fp8;
- (void)setAction:(SEL)fp8 forSegment:(int)fp12;
- (id)targetForSegment:(int)fp8;
- (void)setTarget:(id)fp8 forSegment:(int)fp12;
- (void)setTag:(int)fp8 forSegment:(int)fp12;
- (void)setToolTip:(id)fp8 forSegment:(int)fp12;
- (void)setMenu:(id)fp8 forSegment:(int)fp12;

@end

