/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSObject.h"

@class ActivityMonitor, MailAccount, QuotaUsage;

@interface SizeEngine : NSObject
{
    MailAccount *_account;
    QuotaUsage *_totalUsage;
    ActivityMonitor *_monitor;
    int _monitorAccessKey;
    BOOL _isActive;
}

- (id)initWithAccount:(id)fp8;
- (void)dealloc;
- (void)finalize;
- (id)account;
- (id)totalUsage;
- (void)refresh;
- (void)cancel;
- (void)start;
- (void)stop;

@end

