/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "Connection.h"

@class NSMutableArray, NSMutableData, NSString;

@interface SMTPConnection : Connection
{
    unsigned int _lastResponseCode:31;
    unsigned int _hideLoggedData:1;
    id _lastResponse;
    int _greeting;
    NSMutableArray *_serviceExtensions;
    NSMutableData *_mdata;
    NSString *_domainName;
    int _originalSocketTimeout;
    int _lastCommandTimestamp;
}

+ (void)initialize;
- (id)init;
- (void)dealloc;
- (void)finalize;
- (int)state;
- (id)lastResponse;
- (unsigned int)lastResponseCode;
- (id)domainName;
- (void)setDomainName:(id)fp8;
- (unsigned long long)maximumMessageBytes;
- (id)authenticationMechanisms;
- (BOOL)authenticateUsingAccount:(id)fp8;
- (BOOL)_reauthenticate;
- (BOOL)_authenticateUsingAccount:(id)fp8 authenticator:(id)fp12;
- (int)_authenticateUsingHostname:(id)fp8 username:(id)fp12 password:(id)fp16 authenticator:(id)fp20;
- (BOOL)_startTLSForHostname:(id)fp8 onPort:(unsigned int)fp12 securityLayerType:(int)fp16 accountClass:(Class)fp20;
- (int)_startTLSForSecurityLayerType:(int)fp8;
- (BOOL)connectUsingAccount:(id)fp8;
- (BOOL)reconnect;
- (void)_setupConnection;
- (BOOL)_teardownConnectionWithResult:(BOOL)fp8;
- (int)mailFrom:(id)fp8;
- (int)rcptTo:(id)fp8;
- (int)noop;
- (int)sendDatas:(id)fp8;
- (int)quit;
- (long)timeLastCommandWasSent;

@end

