/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import <Message/SpecialMailboxUid.h>

@interface SpecialMailboxUid (AppleScript)
+ (id)appleScriptNameForMailboxType:(int)fp8;
- (id)appleScriptKey;
- (id)objectSpecifier;
- (id)messages;
@end

