/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSAnimation.h"

@class ExpandingSplitView;

@interface SplitterAnimation : NSAnimation
{
    ExpandingSplitView *_splitView;
    float _startPercentage;
    float _endPercentage;
}

- (id)initWithSplitView:(id)fp8 endPercentage:(float)fp12;
- (id)initWithSplitView:(id)fp8 endPercentage:(float)fp12 duration:(double)fp16;
- (void)dealloc;
- (void)_updatePercentage;
- (void)setCurrentProgress:(float)fp8;

@end

