/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSObject.h"

#import "MessageContentDisplayProtocol.h"

@class MessageBody, MessageTextView, NSInvocation, NSScrollView;

@interface TextMessageDisplay : NSObject <MessageContentDisplay>
{
    NSScrollView *messageScroll;
    MessageTextView *textView;
    MessageBody *messageBody;
    BOOL needsSetUp;
    NSInvocation *displayChangedInvocation;
    id _delegate;
}

+ (id)copyDocumentForMessage:(id)fp8 viewingState:(id)fp12;
- (void)dealloc;
- (id)findTarget;
- (id)contentView;
- (id)textView;
- (void)awakeFromNib;
- (void)display:(id)fp8 inContainerView:(id)fp12 replacingView:(id)fp16 invokeWhenDisplayChanged:(id)fp20;
- (void)prepareToRemoveView;
- (id)selectedTextRepresentation;
- (void)setSelectedTextRepresentation:(id)fp8;
- (id)selectedText;
- (id)selectedWebArchive;
- (id)attachmentsInSelection;
- (id)webArchiveBaseURL:(id *)fp8;
- (void)highlightSearchText:(id)fp8;
- (void)adjustFontSizeBy:(int)fp8 viewingState:(id)fp12;
- (void)displayAttributedString:(id)fp8;
- (id)messageTextView:(id)fp8 willReturnMenu:(id)fp12 forEvent:(id)fp16;
- (struct __CFDictionary *)stringsForURLification;
- (void)updateURLMatches:(id)fp8 viewingState:(id)fp12;
- (void)detectDataInMessage:(id)fp8 usingContext:(id)fp12;
- (void)_setDisplayChangedInvocation:(id)fp8;
- (id)delegate;
- (void)setDelegate:(id)fp8;

@end

