/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "FilesystemEmailImporter.h"

@interface ThunderbirdEmailImporter : FilesystemEmailImporter
{
}

+ (id)name;
+ (id)explanatoryText;
- (id)pathExtension;
- (char *)fromString;

@end

