/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "WebView.h"

@interface TilingWebView : WebView
{
    unsigned int _isAdjusting:1;
    unsigned int _disableSizeToFit:1;
    float _leftMargin;
    float _minHeight;
}

- (BOOL)disableSizeToFit;
- (void)setDisableSizeToFit:(BOOL)fp8;
- (id)initWithFrame:(struct _NSRect)fp8 frameName:(id)fp24 groupName:(id)fp28;
- (void)adjustForTilingView:(id)fp8 oldSize:(struct _NSSize)fp12;
- (BOOL)createToDoUsing:(id)fp8;
- (void)sizeToFit;
- (float)minHeight;
- (void)setMinHeight:(float)fp8;
- (float)leftMargin;
- (void)setLeftMargin:(float)fp8;

@end

