/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSObject.h"

@class NSWindow, ToDoAlarm, ToDoAlarmView;

@interface ToDoAlarmViewController : NSObject
{
    ToDoAlarmView *_alarmView;
    ToDoAlarm *_alarm;
    NSWindow *_window;
}

- (id)init;
- (id)initWithWindow:(id)fp8;
- (void)dealloc;
- (id)window;
- (id)alarmView;
- (id)alarm;
- (void)setAlarm:(id)fp8;
- (void)changeAlarmType:(id)fp8;
- (void)changeDayOffsetType:(id)fp8;
- (void)changeOffsetDays:(id)fp8;
- (void)changeAlarmTime:(id)fp8;
- (void)changeReminderDate:(id)fp8;
- (void)changeSound:(id)fp8;
- (void)changeEmailAddress:(id)fp8;
- (void)changeFile:(id)fp8;
- (void)selectArbitraryFile:(id)fp8;
- (void)addAlarm:(id)fp8;
- (void)removeAlarm:(id)fp8;

@end

