/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "ToDoCheckBoxButtonCell.h"

@interface ToDoListCheckBoxCell : ToDoCheckBoxButtonCell
{
}

- (id)initTextCell:(id)fp8;
- (id)initImageCell:(id)fp8;
- (void)awakeFromNib;
- (void)_generalInit;
- (struct _NSRect)titleRectForBounds:(struct _NSRect)fp8;
- (struct _NSRect)imageRectForBounds:(struct _NSRect)fp8;
- (void)addTrackingAreasForView:(id)fp8 inRect:(struct _NSRect)fp12 withUserInfo:(id)fp28 mouseLocation:(struct _NSPoint)fp32;
- (void)mouseEntered:(id)fp8;
- (void)mouseExited:(id)fp8;

@end

