/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface ToDoUIDRemoteIDPair : NSObject
{
    NSString *_todoUID;
    NSString *_remoteID;
}

- (id)init;
- (id)initWithToDoUID:(id)fp8 remoteID:(id)fp12;
- (void)dealloc;
- (id)todoUID;
- (id)remoteID;

@end

