/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import <Message/ToDoCriterion.h>

@interface ToDoCriterion (PrivateLibraryAdditions)
- (BOOL)isExpressibleInTigerSchema;
- (id)SQLExpressionWithContext:(CDAnonymousStruct1 *)fp8 depth:(unsigned int)fp12 enclosingSmartMailboxes:(id)fp16;
@end

