/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import <Message/ToDosCache.h>

@interface ToDosCache (Internal)
- (id)_todoWithID:(id)fp8 loadIfNotFound:(BOOL)fp12;
- (id)_libraryToDoFromCalTask:(id)fp8 addToCache:(BOOL)fp12;
- (BOOL)_locked_haveRecordOfDeletedToDoWithID:(id)fp8;
- (void)_locked_removeDeletedToDoID:(id)fp8 forDocumentID:(id)fp12;
- (void)_locked_addDeletedToDoID:(id)fp8 forDocumentID:(id)fp12;
@end

