/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "ToDoAlarm.h"

@class NSMutableArray;

@interface ToDoCommonAlarmsProxy : ToDoAlarm
{
    NSMutableArray *_alarms;
    BOOL _propogateChanges;
}

+ (id)alarmProxyWithAlarms:(id)fp8;
- (id)initWithAlarm:(id)fp8;
- (id)initWithAlarms:(id)fp8;
- (void)dealloc;
- (id)alarms;
- (void)setAlarms:(id)fp8;
- (void)setPropogateChanges:(BOOL)fp8;
- (void)setHasNotChanged;
- (void)setEnabled:(BOOL)fp8;
- (void)setType:(int)fp8;
- (void)setOffsetType:(int)fp8;
- (void)setOffsetDays:(unsigned int)fp8;
- (void)setReminderDate:(id)fp8;
- (void)setTime:(int)fp8;
- (void)setSound:(id)fp8;
- (void)setEmailAddress:(id)fp8;
- (void)setUrl:(id)fp8;
- (void)setUnrecognizedData:(id)fp8;
- (int)offsetType;

@end

