/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableDictionary;

@interface ToDoCalendars : NSObject
{
    NSMutableDictionary *_calendarsMap;
    NSMutableDictionary *_groupsMap;
    Class _libraryClass;
}

+ (id)sharedInstance;
- (void)dealloc;
- (id)init;
- (id)newCalendarWithTitle:(id)fp8 calendarID:(id)fp12 inAccount:(id)fp16 createdGroup:(char *)fp20;
- (id)calendarWithID:(id)fp8;
- (id)calendarWithID:(id)fp8 orTitle:(id)fp12;
- (id)calendarWithID:(id)fp8 andTitle:(id)fp12;
- (id)anyEditableCalendarInAccount:(id)fp8;
- (id)calendarWithTitle:(id)fp8 account:(id)fp12;
- (id)calendarWithTitle:(id)fp8 calendarID:(id)fp12 account:(id)fp16 searchEditableCalendarsOnly:(BOOL)fp20 inCalendarStore:(BOOL)fp24;
- (id)calendarEnumerator;
- (id)allCalendars;
- (id)allEditableCalendarsInAccount:(id)fp8;
- (id)allCalendarsInAccount:(id)fp8;
- (id)loadAndCacheAllCalendarsInDisabledAccount:(id)fp8 usingGroup:(id)fp12;
- (void)markAllCalendarsAsNonEditable;
- (id)allUniqueCalendarNames;
- (void)addCalendars:(id)fp8;
- (void)deleteCalendarsWithIDs:(id)fp8;
- (void)deleteCalendars:(id)fp8;
- (id)calendarsFromLibrary;
- (void)addGroups:(id)fp8;
- (void)updateGroups:(id)fp8;
- (void)deleteGroups:(id)fp8;
- (id)calendarGroupWithID:(id)fp8;
- (id)calendarGroupForAccount:(id)fp8;
- (id)loadAndCacheCalendarGroupForDisabledAccount:(id)fp8;
- (id)allCalendarGroupsInActiveAccounts;
- (id)defaultCalendarTitle;
- (id)detailedGroupsDescription;

@end

