/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface ToDoDifferenceExpressionResult : NSObject
{
    int _operation;
    int _provider;
    NSString *_todoUID;
    NSString *_remoteID;
}

- (id)init;
- (id)initWithOperation:(int)fp8 provider:(int)fp12 todoUID:(id)fp16 remoteID:(id)fp20;
- (void)dealloc;
- (int)operation;
- (void)setOperation:(int)fp8;
- (int)provider;
- (void)setProvider:(int)fp8;
- (id)todoUID;
- (void)setToDoUID:(id)fp8;
- (id)remoteID;
- (void)setRemoteID:(id)fp8;
- (void)setOperation:(int)fp8 provider:(int)fp12 todoUID:(id)fp16 remoteID:(id)fp20;
- (BOOL)isAddDeleteOrUpdate;
- (BOOL)isAddDeleteUpdateOrOddity;
- (BOOL)isAdd;
- (BOOL)isDelete;
- (BOOL)isUpdate;
- (BOOL)isConflict;
- (BOOL)isInvalid;
- (BOOL)hasStoreSource;
- (BOOL)hasCacheSource;

@end

