/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "ToDoAlarmViewController.h"

@interface ToDoAlarmViewController (Internal)
- (void)commitFileToOpen:(id)fp8;
- (void)userSelectedFileToOpen:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (void)alarmChanged:(id)fp8;
- (id)undoManager;
@end

