/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSView.h"

@class NSTextField, ToDoMultipleAlarmsView, ToDoPlusMinusButton;

@interface ToDoAlarmEditorView : NSView
{
    ToDoMultipleAlarmsView *_alarmsView;
    ToDoPlusMinusButton *_addAlarmButton;
    NSTextField *_addAlarmLabel;
    NSTextField *_otherAlarmsText;
    ToDoPlusMinusButton *_otherAlarmsClearButton;
    float _addAlarmSectionHeight;
    float _otherAlarmsSectionHeight;
    float _verticalInset;
    BOOL _enabled;
}

- (id)initWithFrame:(struct _NSRect)fp8;
- (void)awakeFromNib;
- (void)drawRect:(struct _NSRect)fp8;
- (void)finishInitialLayout;
- (void)reLayout;
- (void)alarmsLayoutChanged:(id)fp8;
- (void)setAlarms:(id)fp8;
- (id)alarms;
- (void)setOtherAlarmsLabel:(id)fp8;
- (void)setOtherAlarmsHidden:(BOOL)fp8;
- (BOOL)isEnabled;
- (void)setEnabled:(BOOL)fp8;

@end

