/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "ToDoBackgroundView.h"

@interface ToDoBackgroundView (ForUseByOverallController)
- (void)updateViewForChangedProperties:(unsigned int)fp8;
@end

