/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "ToDoAlarmView.h"

@interface ToDoAlarmView (Internal)
- (void)_updateFilePopUp:(id)fp8;
- (void)_loadDynamicFilesFromDefaults;
- (void)_storeDynamicFilesInDefaults;
- (void)_numberOfDaysChanged:(id)fp8;
@end

