/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import <Message/TransientBookmarkItem.h>

@interface TransientBookmarkFolder : TransientBookmarkItem
{
    BOOL _localizedNameNeedRefresh;
}

+ (void)setEntity:(id)fp8;
+ (id)entity;
- (id)bookmarkChildren;
- (BOOL)containsFeed;
- (void)setContainsFeed:(BOOL)fp8;
- (void)calculateContainsFeed;
- (id)localizedName;
- (void)setLocalizedName:(id)fp8;
- (id)feedFolderChildren;
- (id)feedChildren;
- (unsigned int)_feedChildrenCount;
- (unsigned int)_feedFolderChildrenCount;
- (void)_updateContainsFeed:(BOOL)fp8;
- (void)didTurnIntoFault;

@end

