/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSObject.h"

@class MessageWebView, NSString, NSView, WebMessageDocument;

@interface WebMessageController : NSObject
{
    WebMessageDocument *_document;
    MessageWebView *_webView;
    NSView *_mainFrameDocumentView;
    NSString *_sender;
    id _delegate;
    BOOL _finishedFirstLayout;
}

+ (void)initialize;
- (id)initWithDocument:(id)fp8;
- (void)setWebView:(id)fp8;
- (id)webView;
- (void)setSender:(id)fp8;
- (void)setDocument:(id)fp8;
- (void)documentResized;
- (BOOL)hasFinishedLoading;
- (BOOL)hasFinishedFirstLayout;
- (void)webView:(id)fp8 didFirstLayoutInFrame:(id)fp12;
- (void)stopLoading;
- (void)dealloc;
- (void)adjustFontSizeBy:(int)fp8;
- (void)refreshWithViewingState:(id)fp8;
- (id)mainFrameDocumentView;
- (void)setMainFrameDocumentView:(id)fp8;
- (void)_openLink:(id)fp8;
- (void)_openLinkBehind:(id)fp8;
- (void)webView:(id)fp8 didFinishLoadForFrame:(id)fp12;
- (id)document;

@end

