/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSEnumerator.h"

@class DOMNode, EditableWebMessageDocument;

@interface _ComposeAttachmentEnumerator : NSEnumerator
{
    DOMNode *_currentNode;
    DOMNode *_containerNode;
    DOMNode *_endNode;
    EditableWebMessageDocument *_document;
    unsigned int acceptDeleted:1;
    unsigned int acceptNonDeleted:1;
    unsigned int createdIterator:1;
}

- (id)initWithDocument:(id)fp8 options:(int)fp12 range:(id)fp16;
- (void)dealloc;
- (short)acceptNode:(id)fp8;
- (id)nextObject;
- (id)document;
- (void)setDocument:(id)fp8;
- (id)endNode;
- (void)setEndNode:(id)fp8;
- (id)containerNode;
- (void)setContainerNode:(id)fp8;
- (id)currentNode;
- (void)setCurrentNode:(id)fp8;

@end

