/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class IMAPMailboxes, MailboxUid, NSArray, NSString;

@interface _IMAPMailboxEntry : NSObject
{
    NSString *_name;
    NSString *_path;
    BOOL _subscribed;
    NSArray *_children;
    NSArray *_filteredChildren;
    MailboxUid *_uid;
    BOOL _isNoSelect;
    BOOL _hasEnabledDescendants;
    _IMAPMailboxEntry *_parent;
    IMAPMailboxes *_controller;
}

- (void)dealloc;
- (int)compare:(id)fp8;
- (id)filteredChildren;
- (BOOL)isPathValidForCurrentFilter;
- (BOOL)isValidForCurrentFilter;

@end

