/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "ABMailRecent.h"

@interface ABMailRecent (MailAdditions)
- (id)middleName;
- (id)nickname;
- (id)extension;
- (id)mostRecentDate;
- (BOOL)hasRelatedAddressBookRecord;
- (BOOL)isGroup;
- (id)_fullName;
@end

