/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSPreferencesModule.h"

#import "AccountStatusDataSourceDelegate-Protocol.h"
#import "SyncableDataInterestedParty-Protocol.h"

@class AccountDetails, AccountStatusDataSource, MailAccount, NSButton, NSIndexSet, NSMutableArray, NSMutableDictionary, NSPopUpButton, NSString, NSTabView, NSTableView, NSTextField, NSTextView, NSView;

@interface AccountPreferences : NSPreferencesModule <SyncableDataInterestedParty, AccountStatusDataSourceDelegate>
{
    NSMutableArray *_accounts;
    AccountDetails *_accountDetails;
    NSTabView *detailTabView;
    NSTableView *accountsTable;
    NSButton *createAccountButton;
    NSButton *removeAccountButton;
    NSButton *helpButton;
    NSPopUpButton *accountTypePopup;
    NSTextField *accountTypeString;
    NSTextField *accountName;
    NSTextField *fullNameField;
    NSTextField *emailAddressField;
    NSTextField *username;
    NSTextField *hostname;
    NSTextField *password;
    AccountStatusDataSource *_deliveryASDS;
    NSPopUpButton *smtpAccountPopup;
    NSButton *lockDeliveryAccountButton;
    NSView *outlookWebAccessView;
    NSTextField *outlookWebAccessServerName;
    NSButton *editAliasesButton;
    MailAccount *_accountBeingEdited;
    MailAccount *_accountBeingValidated;
    BOOL _accountBeingEditedWasEnabledWhenEditingStarted;
    BOOL _creatingNewAccount;
    BOOL _passwordFieldHasBeenTouched;
    int _indexOfNewAccount;
    struct {
        unsigned int userWantsToQuit:1;
        unsigned int userWantsToClosePrefsPanel:1;
        unsigned int userWantsToChangeSelection:1;
        unsigned int userWantsToCreateNewAccount:1;
        unsigned int userWantsToOpenNewAccountAssistant:1;
    } _flags;
    NSIndexSet *_selectedRows;
    NSString *_selectedToolbarIdentifier;
    BOOL _ignoreTableViewSelectionCallbacks;
    BOOL _registeredForNotifications;
    BOOL _lastPopupSelectionWasITools;
    NSMutableDictionary *_userEnteredInfo;
    NSTextView *accountSupportURLField;
}

+ (void)addAccountType:(id)fp8 class:(Class)fp12;
+ (void)initialize;
+ (void)focusAccount:(id)fp8;
+ (void)editServerList:(id)fp8 selectedAccount:(id)fp12;
+ (void)configureAccountTypePopUp:(id)fp8;
+ (void)selectAccoutType:(Class)fp8 inTypePopup:(id)fp12;
+ (Class)accountClassOfSelectedItemInAccountTypePopup:(id)fp8;
+ (id)ispAccountInfoOfSelectedItemInAccountTypePopup:(id)fp8;
- (id)titleForIdentifier:(id)fp8;
- (id)windowTitle;
- (void)dealloc;
- (void)awakeFromNib;
- (void)accountsDidChange:(id)fp8;
- (id)init;
- (void)initializeFromDefaults;
- (void)nowWouldBeAGoodTimeToTerminate:(id)fp8;
- (void)moduleWasInstalled;
- (BOOL)moduleCanBeRemoved;
- (BOOL)preferencesWindowShouldClose;
- (void)_saveAccountInfo;
- (void)toggleAccountEnabled:(id)fp8;
- (void)toggleIncludeWhenCheckingForNewMail:(id)fp8;
- (BOOL)validateMenuItem:(id)fp8;
- (void)createNewAccount:(id)fp8;
- (void)_removeAccountBeingCreated;
- (void)editAccount:(id)fp8;
- (void)editMailAccount:(id)fp8;
- (void)removeAccountSheetDidEnd:(id)fp8 returnCode:(int)fp12 account:(id)fp16;
- (void)removeAccount:(id)fp8;
- (BOOL)isAccountInformationDirty;
- (void)_handleRequestToSwitchAwayFromSelectedAccountWithResponse:(BOOL)fp8;
- (void)saveAccountSheetDidEnd:(id)fp8 returnCode:(int)fp12 context:(void *)fp16;
- (BOOL)allowSwitchingAwayFromSelectedAccount;
- (void)setUIElementsEnabled:(BOOL)fp8;
- (void)_clearAccountUI;
- (id)selectedAccount;
- (void)_reloadDeliveryAccountPopup:(id)fp8;
- (void)_setupUIForAccountBeingEdited;
- (void)_runAccountDetailPanelForAccount:(id)fp8;
- (void)saveAccountBeingEdited;
- (void)tabView:(id)fp8 didSelectTabViewItem:(id)fp12;
- (void)_setupAccountFromValuesInUI:(id)fp8 forValidation:(BOOL)fp12;
- (void)_updateAccountTypePopup;
- (BOOL)newSettingsAreValid;
- (void)accountTypePopupWillPopup:(id)fp8;
- (void)accountTypeChanged:(id)fp8;
- (void)editAliases:(id)fp8;
- (void)editServerList:(id)fp8 selectedAccount:(id)fp12;
- (int)numberOfRowsInTableView:(id)fp8;
- (id)_accountAtRow:(int)fp8;
- (void)tableView:(id)fp8 willDisplayCell:(id)fp12 forTableColumn:(id)fp16 row:(int)fp20;
- (id)tableView:(id)fp8 toolTipForCell:(id)fp12 rect:(struct _NSRect *)fp16 tableColumn:(id)fp20 row:(int)fp24 mouseLocation:(struct _NSPoint)fp28;
- (id)tableView:(id)fp8 objectValueForTableColumn:(id)fp12 row:(int)fp16;
- (BOOL)selectionShouldChangeInTableView:(id)fp8;
- (void)tableViewSelectionDidChange:(id)fp8;
- (BOOL)tableView:(id)fp8 writeRows:(id)fp12 toPasteboard:(id)fp16;
- (unsigned int)tableView:(id)fp8 validateDrop:(id)fp12 proposedRow:(int)fp16 proposedDropOperation:(unsigned int)fp20;
- (BOOL)tableView:(id)fp8 acceptDrop:(id)fp12 row:(int)fp16 dropOperation:(unsigned int)fp20;
- (void)controlTextDidChange:(id)fp8;
- (BOOL)dataWillBeSynced;
- (void)dataWasSynced;
- (id)accountTypeNameForAccountClass:(Class)fp8;
- (id)_newAccountName;
- (Class)_newAccountClass;

@end

