/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

#import "SyncableDataOwner-Protocol.h"

@class NSMutableDictionary;

@interface Account : NSObject <SyncableDataOwner>
{
    unsigned int _isOffline:1;
    unsigned int _willingToGoOnline:1;
    unsigned int _autosynchronizingEnabled:1;
    unsigned int _promptedToTrustSSLCertificates:1;
    unsigned int _isActive:2;
    NSMutableDictionary *_info;
}

+ (void)initialize;
+ (BOOL)haveAccountsBeenConfigured;
+ (id)readAccountsUsingDefaultsKey:(id)fp8 forceReadFromMailPreferences:(BOOL)fp12;
+ (id)readAccountsUsingDefaultsKey:(id)fp8;
+ (void)_backupPreferencesObject:(id)fp8 forKey:(id)fp12;
+ (void)saveAccounts:(id)fp8 usingDefaultsKey:(id)fp12;
+ (void)saveAccountInfoToDefaults;
+ (id)accountsVersion;
+ (id)createAccountWithDictionary:(id)fp8;
+ (id)accountTypeString;
+ (id)_meCardFromMacBuddyPlistFile;
+ (id)myFullName;
+ (id)myEmailAddress;
+ (BOOL)allObjectsInArrayAreOffline:(id)fp8;
+ (BOOL)defaultsToSSL;
+ (void)_loadISPPlist:(id)fp8 bundle:(id)fp12 path:(id)fp16;
+ (void)_loadISPPlistsAtPath:(id)fp8;
+ (id)_ispPlist;
+ (id)ISPReceivingAccountForDomain:(id)fp8;
+ (id)ISPReceivingAccountForIdentifier:(id)fp8;
+ (id)ISPDeliveryAccountsForISPReceivingAccount:(id)fp8;
+ (id)ISPAccounts;
- (id)init;
- (void)dealloc;
- (void)finalize;
- (id)info;
- (void)setInfo:(id)fp8;
- (void)setAutosynchronizingEnabled:(BOOL)fp8;
- (void)_queueAccountInfoDidChange;
- (id)accountInfo;
- (void)_setAccountInfo:(id)fp8;
- (void)setAccountInfo:(id)fp8;
- (id)defaultsDictionary;
- (void)updateFromSyncedDictionary:(id)fp8;
- (BOOL)isActive;
- (void)setIsActive:(BOOL)fp8;
- (BOOL)isInactivatedInsteadOfBeingDeleted;
- (void)setInactivatedInsteadOfBeingDeleted:(BOOL)fp8;
- (BOOL)canGoOffline;
- (BOOL)isOffline;
- (void)setIsOffline:(BOOL)fp8;
- (BOOL)isWillingToGoOnline;
- (void)setIsWillingToGoOnline:(BOOL)fp8;
- (id)storedDisplayName;
- (void)setStoredDisplayName:(id)fp8;
- (id)displayName;
- (void)setDisplayName:(id)fp8;
- (id)username;
- (void)setUsername:(id)fp8;
- (id)hostname;
- (void)setHostname:(id)fp8;
- (void)setPasswordInKeychain:(id)fp8;
- (void)_removePasswordInKeychain;
- (void)setTemporaryPassword:(id)fp8;
- (void)setPassword:(id)fp8;
- (id)passwordFromStoredUserInfo;
- (id)passwordFromKeychain;
- (id)password;
- (id)promptUserForPasswordWithMessage:(id)fp8;
- (id)promptUserIfNeededForPasswordWithMessage:(id)fp8;
- (unsigned int)portNumber;
- (unsigned int)defaultPortNumber;
- (unsigned int)defaultSecurePortNumber;
- (void)setPortNumber:(unsigned int)fp8;
- (id)serviceName;
- (id)secureServiceName;
- (void)releaseAllConnections;
- (void)validateConnections;
- (BOOL)usesSSL;
- (void)setUsesSSL:(BOOL)fp8;
- (int)securityLayerType;
- (void)setSecurityLayerType:(int)fp8;
- (id)domain;
- (void)setDomain:(id)fp8;
- (void)accountInfoDidChange;
- (id)preferredAuthScheme;
- (void)setPreferredAuthScheme:(id)fp8;
- (id)saslProfileName;
- (Class)connectionClass;
- (BOOL)requiresAuthentication;
- (id)authenticatedConnection;
- (BOOL)_shouldTryDirectSSLConnectionOnPort:(unsigned int)fp8;
- (BOOL)_shouldRetryConnectionWithoutCertificateCheckingAfterError:(id)fp8;
- (BOOL)_connectAndAuthenticate:(id)fp8;
- (id)ISPAccountID;
- (void)setISPAccountID:(id)fp8;
- (id)uniqueId;
- (id)nameForMailboxUid:(id)fp8;
- (id)_ispAccountDictionary;
- (id)_guessedISPAccountDictionary;
- (id)supportURL;
- (id)supportURLLabel;
- (id)subscriptionURL;
- (id)subscriptionURLLabel;
- (id)accountTypeString;
- (BOOL)dataWillBeSyncedVersion:(id *)fp8 data:(id *)fp12 type:(id)fp16;
- (BOOL)dataWasSyncedVersion:(id)fp8 type:(id)fp12 newData:(id)fp16 acceptedChanges:(id)fp20;
- (void)updateAccountsFromPlist:(id)fp8 acceptedChanges:(id)fp12;
- (void)heal;
- (BOOL)isValid;
- (void)setAccountInfoObject:(id)fp8 forKey:(id)fp12;
- (void)removeAccountInfoObjectForKey:(id)fp8;

@end

