/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class MFError, NSMachPort, NSString;

@interface ActivityMonitor : NSObject
{
    NSMachPort *_cancelPort;
    NSString *_taskName;
    NSString *_statusMessage;
    NSString *_descriptionString;
    double _percentDone;
    unsigned int _key:13;
    unsigned int _canCancel:1;
    unsigned int _shouldCancel:1;
    unsigned int _isActive:1;
    unsigned int _priority:8;
    unsigned int _changeCount:8;
    id _delegate;
    id _target;
    MFError *_error;
    int shouldUnifyDoneness;
    float previousDoneness;
    int currentProgressStage;
    int numberOfProgressStages;
    double _startTime;
    float _itemValue;
    float _itemMinValue;
    float _itemMaxValue;
    unsigned int _itemsDone;
    unsigned int _itemsTotal;
    BOOL _isProgressing;
    NSString *_itemDescription;
    float _doneValue;
    double _itemLastNotifiedTime;
    float _itemDone;
    unsigned int _itemFudgeFactor;
    int _activityType;
}

+ (float)determinateProgress;
+ (id)currentMonitor;
- (id)init;
- (void)dealloc;
- (void)finalize;
- (BOOL)isActive;
- (void)setDelegate:(id)fp8;
- (void)postActivityStarting;
- (void)handlePortMessage:(id)fp8;
- (void)postActivityFinished;
- (void)_didChange;
- (int)changeCount;
- (void)setStatusMessage:(id)fp8;
- (void)setStatusMessage:(id)fp8 percentDone:(double)fp12;
- (id)statusMessage;
- (void)setPercentDone:(double)fp8;
- (double)percentDone;
- (float)unifiedFractionDone;
- (void)beginProgressFor:(int)fp8;
- (unsigned char)priority;
- (void)setPriority:(unsigned char)fp8;
- (id)activityDescription;
- (id)description;
- (id)taskName;
- (void)setTaskName:(id)fp8;
- (void)setActivityTarget:(id)fp8;
- (id)activityTarget;
- (void)addActivityTarget:(id)fp8;
- (void)removeActivityTarget:(id)fp8;
- (void)setPrimaryTarget:(id)fp8;
- (id)activityTargets;
- (BOOL)canBeCancelled;
- (void)setCanBeCancelled:(BOOL)fp8;
- (BOOL)shouldCancel;
- (void)setShouldCancel:(BOOL)fp8;
- (void)cancel;
- (int)acquireExclusiveAccessKey;
- (void)relinquishExclusiveAccessKey:(int)fp8;
- (void)setStatusMessage:(id)fp8 percentDone:(double)fp12 withKey:(int)fp20;
- (void)setStatusMessage:(id)fp8 withKey:(int)fp12;
- (void)setPercentDone:(double)fp8 withKey:(int)fp16;
- (id)error;
- (void)setError:(id)fp8;
- (void)_setCancelPort:(id)fp8;
- (id)cancelPort;
- (void)updateDoneValue;
- (void)setDoneValue:(float)fp8;
- (int)activityType;
- (void)setActivityType:(int)fp8;
- (void)setItemFudgeFactor:(unsigned int)fp8;
- (void)setIsProgressing:(BOOL)fp8;
- (void)setItemMaxValue:(float)fp8;
- (void)setItemIndeterminateValue;
- (void)setItem:(id)fp8;
- (void)resetItemValue;
- (void)setItemValue:(float)fp8;
- (void)setItemsDone:(unsigned int)fp8;
- (void)setItemsTotal:(unsigned int)fp8;
- (void)incrementItemValue:(float)fp8;
- (void)incrementItemsDone:(unsigned int)fp8;
- (void)incrementItemsTotal:(unsigned int)fp8;
- (void)markCompleted:(BOOL)fp8;
- (void)resetActivityType;
- (id)itemDescription;
- (void)setItemDescription:(id)fp8;
- (unsigned int)itemsTotal;
- (unsigned int)itemsDone;
- (float)itemValue;
- (float)itemMaxValue;
- (float)itemMinValue;
- (void)setItemMinValue:(float)fp8;
- (float)doneValue;
- (BOOL)isProgressing;

@end

