/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class ActivityAggregate, NSTimer;

@interface ActivityAggregator : NSObject
{
    NSTimer *_timer;
    ActivityAggregate *_in;
    ActivityAggregate *_out;
    unsigned int _numTimeBasedValueObservers;
    unsigned int _numberOfInterestingAggregates;
    double _timeBasedValueObserversLastNotifiedTime;
}

+ (id)sharedInstance;
+ (id)allocWithZone:(struct _NSZone *)fp8;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)retain;
- (unsigned int)retainCount;
- (void)release;
- (id)autorelease;
- (id)in;
- (id)out;
- (id)timer;
- (void)setTimer:(id)fp8;
- (void)installTimer;
- (void)uninstallTimer;
- (void)updateTimeBasedValues;
- (void)updateUnitBasedValues;
- (void)uiTimerFired;
- (void)recordInBytes:(unsigned int)fp8;
- (void)recordOutBytes:(unsigned int)fp8;
- (void)activityMonitor:(id)fp8 didChangeTypeFrom:(int)fp12;
- (void)registerTimeBasedValueObserver:(id)fp8;
- (void)unregisterTimeBasedValueObserver:(id)fp8;
- (void)activityAggregateDidStart:(id)fp8;
- (void)activityAggregateDidEnd:(id)fp8;

@end

