/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSView.h"

@class MessageTextView, NSArray, NSButton, NSControl, NSImage, NSTextField;

@interface AttachmentsView : NSView
{
    NSButton *disclosureButton;
    NSTextField *descriptionField;
    MessageTextView *attachmentsTextView;
    NSImage *paperclip;
    struct _NSPoint paperclipPoint;
    int headerIndent;
    struct _NSRect rectToAvoid;
    NSArray *_attachments;
    id _delegate;
    NSControl *_saveButton;
    NSButton *_quickLookButton;
}

+ (id)newAttachmentsView;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (void)awakeFromNib;
- (void)dealloc;
- (BOOL)isFlipped;
- (void)_saveAllAttachmentsWithoutPrompting:(id)fp8;
- (void)_saveAllAttachments:(id)fp8;
- (void)_saveAttachment:(id)fp8;
- (void)_doQuickLook:(id)fp8;
- (void)_addAttachmentsToIPhoto:(id)fp8;
- (BOOL)attachmentsIncludePhoto;
- (void)_configureSaveMenu:(id)fp8;
- (void)_saveButtonWillPopUp:(id)fp8;
- (void)_clearSaveButtonMenu;
- (void)_configureButtons;
- (void)display:(id)fp8;
- (void)prepareToRemoveView;
- (void)showAttachmentsArea:(BOOL)fp8 viewingState:(id)fp12;
- (void)textViewSelectionChanged:(id)fp8;
- (void)clearSelection:(id)fp8;
- (void)positionSubviews;
- (void)positionSubviewsShowingAttachmentsTextView:(BOOL)fp8;
- (void)dontDrawInSenderImage;
- (void)drawRect:(struct _NSRect)fp8;
- (BOOL)isOpaque;
- (void)saveAllAttachments:(id)fp8;
- (id)attachmentContextMenuForEvent:(id)fp8;
- (void)textView:(id)fp8 doubleClickedOnCell:(id)fp12 inRect:(struct _NSRect)fp16 atIndex:(unsigned int)fp32;
- (void)textView:(id)fp8 draggedCell:(id)fp12 inRect:(struct _NSRect)fp16 event:(id)fp32 atIndex:(unsigned int)fp36;
- (void)attachmentsTextViewFrameChanged:(id)fp8;
- (void)viewFrameDidChange:(id)fp8;
- (void)mouseDown:(id)fp8;
- (BOOL)accessibilityIsIgnored;
- (id)accessibilityAttributeValue:(id)fp8;
- (id)delegate;
- (void)setDelegate:(id)fp8;
- (id)attachments;
- (void)setAttachments:(id)fp8;

@end

