/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface AuthorTransporter : NSObject
{
    NSString *name;
    NSString *email;
}

- (void)dealloc;
- (id)initWithAuthor:(id)fp8;
- (id)email;
- (void)setEmail:(id)fp8;
- (id)name;
- (void)setName:(id)fp8;

@end

