/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSScrollView.h"

@interface AutosizingScrollView : NSScrollView
{
    float _maxHeight;
    unsigned int _resizingContent:1;
    unsigned int _UNUSED:31;
}

+ (struct _NSSize)frameSizeForContentSize:(struct _NSSize)fp8 hasHorizontalScroller:(BOOL)fp16 hasVerticalScroller:(BOOL)fp20 borderType:(unsigned int)fp24;
+ (struct _NSSize)contentSizeForFrameSize:(struct _NSSize)fp8 hasHorizontalScroller:(BOOL)fp16 hasVerticalScroller:(BOOL)fp20 borderType:(unsigned int)fp24;
- (id)initWithFrame:(struct _NSRect)fp8;
- (void)drawRect:(struct _NSRect)fp8;
- (void)tile;
- (void)docViewFrameChanged;
- (void)setMaxHeight:(float)fp8;
- (float)maxHeight;
- (void)setTag:(int)fp8;
- (int)tag;

@end

