/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSMenu.h"

@interface BindingsEnabledMenu : NSMenu
{
}

- (id)addItemWithTitle:(id)fp8 action:(SEL)fp12 keyEquivalent:(id)fp16;
- (id)insertItemWithTitle:(id)fp8 action:(SEL)fp12 keyEquivalent:(id)fp16 atIndex:(unsigned int)fp20;

@end

