/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSButton.h"

@class NSImage;

@interface BorderlessButton : NSButton
{
    NSImage *activeImage;
    NSImage *inactiveImage;
}

- (BOOL)isOpaque;
- (void)dealloc;
- (void)setEnabled:(BOOL)fp8;
- (id)inactiveImage;
- (void)setInactiveImage:(id)fp8;
- (id)activeImage;
- (void)setActiveImage:(id)fp8;

@end

