/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSWindowController.h"

@class NSView, NSWindow;

@interface ChildWindowController : NSWindowController
{
    NSWindow *_parentWindow;
    id _delegate;
    struct {
        unsigned int windowIsOpen:1;
        unsigned int shareKey:1;
        unsigned int closeWhenResigningKey:1;
        unsigned int delegateRespondsToBestFrameOriginForWindow:1;
        unsigned int viewPostingSheet:1;
        unsigned int reserved:27;
    } _flags;
    NSView *_firstKeyView;
    NSView *_lastKeyView;
}

- (id)initWithWindow:(id)fp8;
- (void)dealloc;
- (id)window;
- (id)parentWindow;
- (void)setParentWindow:(id)fp8;
- (BOOL)sharesKey;
- (void)setSharesKey:(BOOL)fp8;
- (id)delegate;
- (void)setDelegate:(id)fp8;
- (BOOL)shouldCloseWhenResigningKey;
- (void)setShouldCloseWhenResigningKey:(BOOL)fp8;
- (id)firstKeyView;
- (id)lastKeyView;
- (BOOL)isWindowOpen;
- (void)addNotifications;
- (void)removeNotifications;
- (void)showWindow:(id)fp8;
- (BOOL)canClose;
- (void)closeWindow:(id)fp8;
- (void)close;
- (void)closeImmediately;
- (struct _NSPoint)bestWindowFrameOrigin;
- (void)closeIfNecessaryForEvent:(id)fp8 before:(BOOL)fp12;
- (void)viewWillPostSheet:(id)fp8;
- (void)viewDonePostingSheet:(id)fp8;
- (void)menuDidBeginTracking:(id)fp8;
- (void)parentWindowDidResignKey:(id)fp8;
- (void)parentWindowWillClose:(id)fp8;
- (void)parentWindowWillBeginSheet:(id)fp8;
- (void)parentWindowDidResize:(id)fp8;
- (void)parentWindowDidMove:(id)fp8;
- (void)parentWindowDidUpdate:(id)fp8;
- (void)windowWillClose:(id)fp8;
- (void)windowDidResignKey:(id)fp8;
- (void)windowDidResize:(id)fp8;
- (void)window:(id)fp8 didProcessEvent:(id)fp12;

@end

