/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSString;

@interface Criterion : NSObject
{
    NSString *_uniqueId;
    NSString *_name;
    NSString *_expression;
    NSString *_criterionIdentifier;
    int _criterionType;
    int _qualifier;
    int _dateUnits;
    BOOL _dateIsRelative;
    NSArray *_criteria;
    BOOL _allCriteriaMustBeSatisfied;
    NSString *_cachedAccountURLForSyncConflictResolution;
    int _specialMailboxUidType;
}

+ (id)criteriaFromDefaultsArray:(id)fp8;
+ (id)criteriaFromDefaultsArray:(id)fp8 removingRecognizedKeys:(BOOL)fp12;
+ (id)defaultsArrayFromCriteria:(id)fp8;
+ (id)compoundCriterionWithCriteria:(id)fp8;
+ (int)criterionTypeForString:(id)fp8;
+ (id)stringForCriterionType:(int)fp8;
- (id)compoundCriterionBySplittingExpression;
- (void)dealloc;
- (id)init;
- (id)initWithCriterion:(id)fp8 expression:(id)fp12;
- (id)initWithDictionary:(id)fp8 andRemoveRecognizedKeysIfMutable:(BOOL)fp12;
- (id)initWithDictionary:(id)fp8;
- (id)dictionaryRepresentation;
- (int)criterionType;
- (BOOL)hasExpression;
- (void)setCriterionType:(int)fp8;
- (void)setCriterionIdentifier:(id)fp8;
- (void)_setCriterionIdentifier:(id)fp8;
- (id)criterionIdentifier;
- (id)_qualifierString;
- (BOOL)containsBodyCriterion;
- (int)ruleQualifierForString:(id)fp8;
- (id)stringForRuleQualifier:(int)fp8;
- (id)simplifyOnce;
- (id)simplifiedCriterion;
- (void)setCriteria:(id)fp8;
- (id)descriptionWithDepth:(unsigned int)fp8;
- (id)description;
- (BOOL)isValid:(id *)fp8 options:(unsigned long)fp12;
- (int)specialMailboxUidType;
- (void)setSpecialMailboxUidType:(int)fp8;
- (BOOL)allCriteriaMustBeSatisfied;
- (void)setAllCriteriaMustBeSatisfied:(BOOL)fp8;
- (id)criteria;
- (BOOL)dateIsRelative;
- (void)setDateIsRelative:(BOOL)fp8;
- (int)dateUnits;
- (void)setDateUnits:(int)fp8;
- (int)qualifier;
- (void)setQualifier:(int)fp8;
- (id)expression;
- (void)setExpression:(id)fp8;
- (id)name;
- (void)setName:(id)fp8;

@end

