/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "DOMHTMLDocument.h"

@interface DOMHTMLDocument (MailExtras)
+ (id)listElements;
- (BOOL)containsSelectionMarkers;
- (id)createDocumentFragmentWithMarkupString:(id)fp8;
- (id)createFragmentForStringLosingBR:(id)fp8;
- (id)createMessageQuoteElement;
- (id)createNonemptyDivElementWithPlainStyle;
- (id)createFragmentForWebArchive:(id)fp8;
- (id)createFragmentForWebArchive:(id)fp8 baseURL:(id)fp12;
- (id)createFragmentForWebArchive:(id)fp8 baseURL:(id)fp12 bodyAsDiv:(BOOL)fp16;
- (id)createSpanElementWithTabs:(int)fp8;
- (id)createFragmentForURL:(id)fp8 text:(id)fp12;
- (id)head;
- (id)backgroundImageURLs;
- (BOOL)convertStationeryBackgroundImageURLs;
- (id)createElement:(id)fp8 class:(id)fp12 id:(id)fp16 editable:(id)fp20;
- (struct __CFDictionary *)stringsAndTextNodes;
@end

