/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "TilingWebView.h"

@class DOMHTMLElement, DOMNode;

@interface EditingMessageWebView : TilingWebView
{
    DOMHTMLElement *_contentElement;
    DOMNode *cursorPositionNode;
    struct {
        unsigned int delegateRespondsToCanInsertFromDraggingInfo:1;
        unsigned int delegateRespondsToCanInsertFromPasteboard:1;
        unsigned int removingAttachments:1;
    } _flags;
}

+ (id)insertablePasteboardTypes;
- (id)mailPreferredPboardTypeFromTypes:(id)fp8 pasteboard:(id)fp12 isForDrag:(BOOL)fp16 preferHTML:(BOOL)fp20;
- (void)setEditingDelegate:(id)fp8;
- (BOOL)replaceSelectionWithPasteboardContentsPasteboard:(id)fp8 pasteboardType:(id)fp12 action:(int)fp16 options:(int)fp20;
- (BOOL)replaceSelectionWithPasteboardContentsDraggingInfo:(id)fp8 pasteboardType:(id)fp12 action:(int)fp16 options:(int)fp20;
- (BOOL)_replaceSelectionWithPasteboardContentsDraggingInfo:(id)fp8 pasteboard:(id)fp12 pasteboardType:(id)fp16 action:(int)fp20 options:(int)fp24;
- (BOOL)replaceSelectionUsingContext:(id)fp8;
- (BOOL)replaceSelectionWithFragment:(id)fp8 attachments:(id)fp12 pasteboard:(id)fp16 types:(id)fp20 action:(int)fp24 options:(int)fp28 isPlainText:(BOOL)fp32;
- (BOOL)isContentEditable;
- (id)contentElement;
- (void)setContentElement:(id)fp8;
- (void)dealloc;
- (BOOL)isSelectionInContentElement;
- (BOOL)selectionCouldBeMadeIntoALink;
- (BOOL)validateUserInterfaceItem:(id)fp8;
- (void)deleteNode:(id)fp8;
- (void)deleteRange:(id)fp8;
- (void)replaceNode:(id)fp8 oldNode:(id)fp12;
- (void)insertNode:(id)fp8 parent:(id)fp12 nextSibling:(id)fp16;
- (void)insertNode:(id)fp8 parent:(id)fp12 offset:(int)fp16;
- (void)setValue:(id)fp8 forAttribute:(id)fp12 ofElement:(id)fp16;
- (void)setStyleProperty:(id)fp8 value:(id)fp12 priority:(id)fp16 ofElement:(id)fp20;
- (BOOL)removingAttachments;
- (BOOL)removeHeadFromDocument:(id)fp8;
- (BOOL)removeFormattingFromTree:(id)fp8 forDocument:(id)fp12;
- (BOOL)removeRichNodesAndStyleFromTree:(id)fp8 forDocument:(id)fp12;
- (void)consolidateTextAndWhitespaceInTree:(id)fp8;
- (void)removeAllFormatting;
- (void)removeAllFormattingFromContentElementOnly:(BOOL)fp8 includingAttachments:(BOOL)fp12;
- (void)insertTemporarySelectionMarkersForRange:(id)fp8;
- (void)restoreSelectionFromTemporaryMarkers;
- (void)restoreSelectionFromTemporaryMarkers:(BOOL)fp8;
- (void)deleteTemporarySelectionMarkersFromDocument:(id)fp8;
- (id)temporaryEndingSelectionMarker;
- (id)temporaryStartingSelectionMarker;
- (id)selectedAnchor;
- (BOOL)isFirstLineOfDocument;
- (id)selectedContainerWithNameInArray:(id)fp8;
- (void)saveSelectionForUndo;
- (void)insertNode:(id)fp8 atRange:(id)fp12;
- (id)insertablePasteboardTypes;
- (void)registerForDraggedTypes:(id)fp8;
- (void)saveMessageToDrafts:(id)fp8;
- (unsigned int)draggingEntered:(id)fp8;
- (unsigned int)draggingUpdated:(id)fp8;
- (void)draggingExited:(id)fp8;
- (BOOL)prepareForDragOperation:(id)fp8;
- (BOOL)performDragOperation:(id)fp8;
- (void)concludeDragOperation:(id)fp8;
- (BOOL)wantsPeriodicDraggingUpdates;
- (void)dragImage:(id)fp8 at:(struct _NSPoint)fp12 offset:(struct _NSSize)fp20 event:(id)fp28 pasteboard:(id)fp32 source:(id)fp36 slideBack:(BOOL)fp40;
- (void)undo:(id)fp8;
- (void)redo:(id)fp8;
- (void)paste:(id)fp8;
- (void)pasteAsQuotation:(id)fp8;
- (void)pasteWithCurrentStyle:(id)fp8;
- (void)setCursorPositionNode:(id)fp8;
- (BOOL)becomeFirstResponder;
- (void)editLink:(id)fp8;
- (void)removeLink:(id)fp8;
- (void)addHorizontalRule:(id)fp8;
- (void)increaseIndentation:(id)fp8;
- (void)decreaseIndentation:(id)fp8;
- (void)changeIndentationIfAllowed:(int)fp8;
- (void)changeIndentation:(int)fp8;
- (BOOL)removeAllQuotingFromTree:(id)fp8;
- (void)changeQuoteLevel:(id)fp8;
- (void)splitUpBlockQuotesOverlappingStartOfRange:(id)fp8;
- (void)splitUpBlockQuotesOverlappingEndOfRange:(id)fp8;
- (int)compareRange:(id)fp8 toEndOfNode:(id)fp12;
- (void)removeBlockQuoteFromTree:(id)fp8;
- (void)removeFragmentBlockQuote:(id)fp8;
- (void)makeFontBigger:(id)fp8;
- (void)makeFontSmaller:(id)fp8;
- (void)viewWillStartLiveResize;
- (void)toggleVisibilityOfSublist:(id)fp8 ofItem:(id)fp12;
- (void)changeDocumentBackgroundColorToColor:(id)fp8;
- (void)viewDidEndLiveResize;
- (void)layoutResizingAttachmentViews;

@end

