/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSView.h"

@interface EmptyFavoritesMessageView : NSView
{
}

- (void)drawRect:(struct _NSRect)fp8;
- (BOOL)isOpaque;

@end

