/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSButton, NSMatrix, NSString, NSTextField;

@interface FindPanel : NSObject
{
    NSButton *findNextButton;
    NSTextField *findTextField;
    NSButton *ignoreCaseButton;
    NSMatrix *replaceAllScopeMatrix;
    NSTextField *replaceTextField;
    NSTextField *statusField;
    NSString *findString;
    BOOL lastFindWasSuccessful;
}

+ (id)sharedInstance;
- (id)init;
- (void)_appDidActivate;
- (void)dealloc;
- (id)findString;
- (void)setFindString:(id)fp8;
- (void)setFindString:(id)fp8 writeToPasteboard:(BOOL)fp12;
- (id)findPanel;
- (void)orderFrontFindPanel:(id)fp8;
- (void)findNextAndOrderFindPanelOut:(id)fp8;
- (void)findNext:(id)fp8;
- (void)findPrevious:(id)fp8;
- (void)ignoreCaseButtonClicked:(id)fp8;
- (void)replace:(id)fp8;
- (void)replaceAndFind:(id)fp8;
- (void)replaceAll:(id)fp8;

@end

