/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Message/IMAPClientFetchDataItem.h>

@class NSArray, NSString;

@interface IMAPClientFetchBodyDataItem : IMAPClientFetchDataItem
{
    int _textSectionSpecifier;
    NSString *_partSectionSpecifier;
    NSArray *_headerFieldNames;
    BOOL _peek;
    struct _NSRange _dataRange;
}

+ (id)createSectionSpecifierFromPart:(id)fp8 text:(int)fp12;
- (void)dealloc;
- (id)initWithPartSectionSpecifier:(id)fp8 textSectionSpecifier:(int)fp12 dataRange:(struct _NSRange)fp16;
- (id)initWithHeaderFieldNames:(id)fp8;
- (id)initWithPartSectionSpecifier:(id)fp8 textSectionSpecifier:(int)fp12 peek:(BOOL)fp16 headerFieldNames:(id)fp20 dataRange:(struct _NSRange)fp24;
- (BOOL)isHeader;
- (void)_finalizeCommandString;
- (BOOL)isEqual:(id)fp8;
- (unsigned int)hash;
- (struct _NSRange)dataRange;
- (void)setDataRange:(struct _NSRange)fp8;
- (BOOL)peek;
- (void)setPeek:(BOOL)fp8;
- (id)headerFieldNames;
- (void)setHeaderFieldNames:(id)fp8;
- (id)partSectionSpecifier;
- (void)setPartSectionSpecifier:(id)fp8;
- (int)textSectionSpecifier;
- (void)setTextSectionSpecifier:(int)fp8;

@end

