/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Message/SizeEngine.h>

@class NSMutableArray, NSMutableDictionary, NSMutableSet;

@interface IMAPSizeEngine : SizeEngine
{
    unsigned int _quotaStatus:3;
    unsigned int _workerThreadCount;
    struct __CFDictionary *_usageByMailboxUid;
    NSMutableDictionary *_mailboxesByQuotaRoot;
    NSMutableArray *_mailboxesToSize;
    NSMutableArray *_quotasToFetch;
    NSMutableSet *_observedIMAPMailboxes;
    NSMutableSet *_observedIMAPQuotaRoots;
}

- (id)initWithIMAPAccount:(id)fp8;
- (void)dealloc;
- (void)finalize;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (void)_addUsageInfoFromMailbox:(id)fp8;
- (void)_addQuotaRootsFromMailbox:(id)fp8;
- (BOOL)_changeUsageInfo:(CDAnonymousStruct3 *)fp8 forMailboxUid:(id)fp12 refetchQuotas:(BOOL)fp16;
- (void)_changeQuotaRoots:(id)fp8 forMailboxUid:(id)fp12;
- (void)_sizeChangedForMailboxUid:(id)fp8;
- (void)_mailboxSizeChanged:(id)fp8;
- (void)handleMailboxSizeChanged:(id)fp8;
- (void)_mailbox:(id)fp8 didRemoveUsage:(id)fp12 fromQuotaRoots:(id)fp16;
- (void)_mailboxBecameInvalid:(id)fp8;
- (void)_refetchListing:(id)fp8;
- (void)_getSizeForMailboxUid:(id)fp8;
- (void)_runWorkerThread;
- (BOOL)_prepareToRefresh;
- (BOOL)_shouldStartWorkerThread;
- (int)quotaStatus;
- (id)quotaNames;
- (id)usageForMailbox:(id)fp8;
- (id)usageForQuotaName:(id)fp8;
- (id)mutableCopyOfMailboxesForQuotaName:(id)fp8;
- (BOOL)mailbox:(id)fp8 usesQuotaName:(id)fp12;

@end

