/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class MFError, NSString;

@interface IMAPResponse : NSObject
{
    unsigned int _responseType:8;
    NSString *_tag;
    union _IMAPResponseData _data;
    MFError *_error;
    BOOL _wasHandled;
}

- (int)responseType;
- (void)setResponseType:(int)fp8;
- (BOOL)isUntagged;
- (BOOL)isAlertResponse;
- (id)tag;
- (void)setTag:(id)fp8;
- (void)dealloc;
- (void)finalize;
- (int)responseCode;
- (id)responseInfo;
- (id)userData;
- (id)userString;
- (void)setUserData:(id)fp8 responseCode:(int)fp12 responseInfo:(id)fp16;
- (id)capabilities;
- (void)setCapabilities:(id)fp8;
- (unsigned long)number;
- (void)setNumber:(unsigned long)fp8;
- (id)flags;
- (void)setFlags:(id)fp8;
- (id)mailboxName;
- (id)statusEntries;
- (void)setMailboxName:(id)fp8 statusEntries:(id)fp12;
- (id)searchResults;
- (void)setSearchResults:(id)fp8;
- (unsigned long)mailboxAttributes;
- (id)separator;
- (void)setMailboxAttributes:(unsigned long)fp8 separator:(id)fp12 mailboxName:(id)fp16;
- (id)fetchResultWithType:(int)fp8;
- (id)fetchResults;
- (void)setFetchResults:(id)fp8;
- (BOOL)isValid;
- (void)setIsValid:(BOOL)fp8;
- (id)quotaRootNames;
- (void)setMailboxName:(id)fp8 quotaRootNames:(id)fp12;
- (id)quotaRootName;
- (id)quotas;
- (void)setQuotaRootName:(id)fp8 quotas:(id)fp12;
- (int)uidFlagsChange;
- (void)setUidFlagsChange:(int)fp8;
- (id)uids;
- (void)setUids:(id)fp8;
- (id)flagsFetchResult;
- (void)setFlagsFetchResult:(id)fp8;
- (id)responseName;
- (id)parameters;
- (void)setResponseName:(id)fp8 parameters:(id)fp12;
- (id)description;
- (id)initWithConnection:(id)fp8 error:(id *)fp12;
- (void)setError:(id)fp8;
- (id)error;
- (BOOL)wasHandled;
- (void)setWasHandled:(BOOL)fp8;

@end

