/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "AccountDetails.h"

@class NSButton, NSPopUpButton, NSTextField;

@interface IMAPAccountDetails : AccountDetails
{
    NSButton *_compactWhenClosing;
    NSPopUpButton *_messageCaching;
    NSTextField *_serverPathPrefix;
    BOOL warnedAboutCachingAndIndexing;
    NSButton *_keepDraftsOnServer;
    NSButton *_keepSentMessagesOnServer;
    NSButton *_keepTrashOnServer;
    NSButton *_keepJunkOnServer;
    NSButton *_useIDLECommand;
}

- (Class)accountClass;
- (void)setupUIFromValuesInAccount:(id)fp8;
- (void)setupAccountFromValuesInUI:(id)fp8 forValidation:(BOOL)fp12;
- (void)setUIElementsEnabled:(BOOL)fp8;
- (BOOL)isAccountInformationDirty:(id)fp8;
- (void)didDisplayTabViewItem:(id)fp8;
- (void)_confirmCacheChangeSheetEnded:(id)fp8 alertReturn:(int)fp12 context:(void *)fp16;
- (void)cachePolicyChanged:(id)fp8;

@end

