/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableDictionary;

@interface JunkRecorder : NSObject
{
    BOOL _isShort;
    BOOL _isSigned;
    int _imageCount;
    int _characterCount;
    float _imageToTextRatio;
    NSMutableDictionary *_imageInfos;
    float _lsmScore;
}

- (id)init;
- (void)dealloc;
- (id)description;
- (float)lsmScore;
- (void)setLsmScore:(float)fp8;
- (BOOL)isShort;
- (void)setIsShort:(BOOL)fp8;
- (BOOL)isSigned;
- (void)setIsSigned:(BOOL)fp8;
- (id)imageInfos;
- (void)setImageInfos:(id)fp8;
- (float)imageToTextRatio;
- (void)setImageToTextRatio:(float)fp8;
- (int)characterCount;
- (void)setCharacterCount:(int)fp8;
- (int)imageCount;
- (void)setImageCount:(int)fp8;

@end

