/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol LibraryInterface <NSObject>
+ (unsigned int)mailboxIDForMailboxUid:(id)fp8;
+ (id)storeForMailboxID:(unsigned int)fp8;
+ (id)urlForMailboxID:(unsigned int)fp8;
+ (BOOL)addToDos:(id)fp8;
+ (BOOL)deleteToDos:(id)fp8;
+ (BOOL)updateToDos:(id)fp8;
+ (id)allToDos;
+ (id)allToDosForMailboxID:(unsigned int)fp8;
+ (id)allToDosForDocumentID:(id)fp8;
+ (unsigned int)maximumToDoRemoteIDForMailbox:(id)fp8;
+ (BOOL)updateToDo:(id)fp8 toRemoteID:(id)fp12;
+ (unsigned int)toDoMailboxIdForMailAccount:(id)fp8;
+ (id)findToDoIDForAlarmID:(id)fp8;
+ (BOOL)addCalendars:(id)fp8;
+ (BOOL)updateCalendars:(id)fp8;
+ (BOOL)deleteCalendars:(id)fp8;
+ (id)allToDoCalendars;
+ (id)todoIDsMatchingCriterion:(id)fp8;
@end

