/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "IMAPObject-Protocol.h"
#import "MFChanging-Protocol.h"

@protocol LibraryObject <IMAPObject, MFChanging>
- (unsigned int)libraryID;
- (unsigned long)uid;
- (void)setUid:(unsigned long)fp8;
- (id)remoteID;
- (void)setRemoteID:(id)fp8;
@end

