/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class InvocationQueue, Location, NSMutableArray;

@interface LocationManager : NSObject
{
    NSMutableArray *_locations;
    Location *_current;
    InvocationQueue *_invocationQueue;
    BOOL supressNotifications;
}

+ (id)sharedManager;
+ (id)currentLocation;
- (id)init;
- (id)initWithUserDefaultsArray:(id)fp8;
- (void)dealloc;
- (void)setCurrentLocation:(id)fp8;
- (id)currentLocation;
- (void)addLocation:(id)fp8;
- (id)locationForDomain:(id)fp8;
- (id)locationForIPAddress:(id)fp8;
- (void)_networkChanged:(id)fp8;
- (void)_determineCurrentLocation;
- (void)_managedLocationChanged:(id)fp8;
- (void)_unarchiveLocations:(id)fp8;
- (id)_archivedLocations;

@end

