/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSTextFieldCell.h"

@class NSImage, NSProgressIndicator;

@interface MailboxListCell : NSTextFieldCell
{
    int rolledOverIndicator;
    BOOL isClickedOn;
    BOOL isPublicOrShared;
    BOOL shouldReverseArrowIndicator;
    int alertState;
    int feedInboxState;
    NSImage *icon;
    unsigned int badgeCount;
    NSProgressIndicator *progressIndicator;
    id item;
}

- (void)showProgressIndicator:(id)fp8 fractionDone:(double)fp12;
- (void)startProgressIndicatorAnimation:(id)fp8;
- (void)positionProgressIndicatorInRect:(struct _NSRect)fp8;
- (id)badgeTextColor;
- (id)badgeColor;
- (id)indicatorColorForRollover:(BOOL)fp8;
- (void)controlTintChanged:(id)fp8;
- (id)drawIndicator:(int)fp8 withImage:(id)fp12 circled:(BOOL)fp16 cellFrame:(struct _NSRect *)fp20 trackingAreaTarget:(id)fp24;
- (id)badgeTextAttributes;
- (void)drawBadgeCenteredInRect:(struct _NSRect)fp8;
- (float)badgeWidth;
- (float)idealWidth;
- (id)initTextCell:(id)fp8;
- (id)initImageCell:(id)fp8;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)dealloc;
- (void)drawWithFrame:(struct _NSRect)fp8 inView:(id)fp24;
- (void)drawInteriorWithFrame:(struct _NSRect)fp8 inView:(id)fp24;
- (void)selectWithFrame:(struct _NSRect)fp8 inView:(id)fp24 editor:(id)fp28 delegate:(id)fp32 start:(int)fp36 length:(int)fp40;
- (struct _NSRect)expansionFrameWithFrame:(struct _NSRect)fp8 inView:(id)fp24;
- (void)drawWithExpansionFrame:(struct _NSRect)fp8 inView:(id)fp24;
- (id)toolTipForPoint:(struct _NSPoint)fp8 rect:(struct _NSRect *)fp16 trackingAreas:(id)fp20;
- (id)accessibilityAttributeNames;
- (id)accessibilityAttributeValue:(id)fp8;
- (BOOL)accessibilityIsAttributeSettable:(id)fp8;
- (BOOL)shouldReverseArrowIndicator;
- (void)setShouldReverseArrowIndicator:(BOOL)fp8;
- (id)item;
- (void)setItem:(id)fp8;
- (id)progressIndicator;
- (void)setProgressIndicator:(id)fp8;
- (unsigned int)badgeCount;
- (void)setBadgeCount:(unsigned int)fp8;
- (id)icon;
- (void)setIcon:(id)fp8;
- (int)feedInboxState;
- (void)setFeedInboxState:(int)fp8;
- (int)alertState;
- (void)setAlertState:(int)fp8;
- (BOOL)isPublicOrShared;
- (void)setIsPublicOrShared:(BOOL)fp8;
- (BOOL)isClickedOn;
- (void)setIsClickedOn:(BOOL)fp8;
- (int)rolledOverIndicator;
- (void)setRolledOverIndicator:(int)fp8;

@end

