/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MailApp.h"

@interface MailApp (ApplescriptGeneralPreferences)
- (BOOL)playOtherMailSounds;
- (void)setPlayOtherMailSounds:(BOOL)fp8;
- (id)newMailSoundPath;
- (void)setNewMailSoundPath:(id)fp8;
- (id)newMailSound;
- (void)setNewMailSound:(id)fp8;
- (id)downloadFolderPath;
- (void)setDownloadFolderPath:(id)fp8;
- (BOOL)indexDecryptedMessages;
- (void)setIndexDecryptedMessages:(BOOL)fp8;
@end

