/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSOutlineView.h"

@interface MailboxesOutlineView : NSOutlineView
{
    BOOL allowsSelectAll;
    BOOL acceptsFirstResponderOnMouseDown;
    BOOL showsUnnecessaryDisclosureTriangles;
}

- (id)initWithCoder:(id)fp8;
- (struct _NSRect)frameOfOutlineCellAtRow:(int)fp8;
- (void)keyDown:(id)fp8;
- (BOOL)acceptsFirstResponder;
- (BOOL)becomeFirstResponder;
- (BOOL)resignFirstResponder;
- (void)mouseDown:(id)fp8;
- (void)mouseUp:(id)fp8;
- (void)selectAll:(id)fp8;
- (void)editColumn:(int)fp8 row:(int)fp12 withEvent:(id)fp16 select:(BOOL)fp20;
- (id)menuForEvent:(id)fp8;
- (BOOL)canFocusCell:(id)fp8 atTableColumn:(id)fp12 row:(int)fp16;
- (BOOL)shouldCollapseAutoExpandedItemsForDeposited:(BOOL)fp8;
- (BOOL)inLiveResize;
- (BOOL)showsUnnecessaryDisclosureTriangles;
- (void)setShowsUnnecessaryDisclosureTriangles:(BOOL)fp8;
- (BOOL)acceptsFirstResponderOnMouseDown;
- (void)setAcceptsFirstResponderOnMouseDown:(BOOL)fp8;
- (BOOL)allowsSelectAll;
- (void)setAllowsSelectAll:(BOOL)fp8;

@end

