/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Message/MailboxUid.h>

@interface MailboxUid (SmartMailboxCycleDetection)
- (BOOL)isPointedToByCriterion:(id)fp8 traversedMailboxes:(id)fp12;
- (BOOL)isPointedToBySmartMailbox:(id)fp8 traversedMailboxes:(id)fp12;
- (BOOL)isPointedToBySmartMailbox:(id)fp8;
@end

