/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MailApp.h"

@interface MailApp (ApplescriptSignaturePreferences)
- (id)signatures;
- (BOOL)chooseSignatureWhenComposing;
- (void)setChooseSignatureWhenComposing:(BOOL)fp8;
- (id)selectedSignature;
- (void)setSelectedSignature:(id)fp8;
@end

