/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SingleMessageViewer.h"

@class NSMenu, NSMutableArray, NSMutableDictionary;

@interface MessageBrowser : SingleMessageViewer
{
    NSMutableArray *_messages;
    unsigned int _includeDeleted:1;
    int _currentIndex;
    int _previousIndex;
    int _nextIndex;
    int _firstIndex;
    int _lastIndex;
    NSMutableDictionary *_messagesByID;
    NSMenu *_previousMenu;
    NSMenu *_nextMenu;
}

+ (void)restoreFromDefaults;
+ (id)browserForMessages:(id)fp8 isSortedAscending:(BOOL)fp12 includeDeleted:(BOOL)fp16;
- (id)initWithSavedDefaults:(id)fp8;
- (id)_saveDefaults;
- (void)_setupFromDefaults;
- (void)dealloc;
- (BOOL)_validateAction:(SEL)fp8 tag:(int)fp12;
- (BOOL)validateToolbarItem:(id)fp8;
- (BOOL)replaceWithEditorForType:(int)fp8;
- (void)_close;
- (int)_newCurrentIndexFromCurrentIndex:(int)fp8;
- (void)messageFlagsDidChange:(id)fp8;
- (void)messagesCompacted:(id)fp8;
- (void)_reallyRedeleteMessage:(id)fp8;
- (void)_redeleteMessage:(id)fp8;
- (void)_reallyUndeleteMessage:(id)fp8;
- (void)_undeleteMessage:(id)fp8;
- (void)_reallyDeleteMessage:(id)fp8 allowMoveToTrash:(BOOL)fp12;
- (void)deleteMessagesAllowingMoveToTrash:(BOOL)fp8;
- (void)setupToolbar;
- (void)showNextMessage:(id)fp8;
- (void)showPreviousMessage:(id)fp8;
- (void)showFirstMessage:(id)fp8;
- (void)keyDown:(id)fp8;
- (id)_initWithMessages:(id)fp8 isSortedAscending:(BOOL)fp12 includeDeleted:(BOOL)fp16;
- (void)_showMessage:(id)fp8;
- (void)_menuItemSelected:(id)fp8;
- (id)_imageForMessage:(id)fp8;
- (void)_addMessage:(id)fp8 toMenu:(id)fp12;
- (void)_updateMenuItemImagesForMenu:(id)fp8;
- (void)_updatePreviousNextMenuItemImages;
- (BOOL)_shouldDisplayMessage:(id)fp8;
- (void)_updatePreviousNextMenus;
- (void)_updateFirstAndLastIndex;
- (void)_nextMessageIndex:(int *)fp8 previousIndex:(int *)fp12 fromCurrentIndex:(int)fp16;
- (void)_updatePreviousAndNextIndex;
- (void)_showMessageAtIndex:(int)fp8;
- (BOOL)_isMessageIndexValid:(int)fp8;
- (int)_firstMessageIndex;
- (int)_lastMessageIndex;
- (int)_previousMessageIndex;
- (int)_nextMessageIndex;
- (void)_showFirstMessage;
- (void)_showLastMessage;
- (void)_showPreviousMessage;
- (void)_showNextMessage;

@end

