/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

#import "MessageDeletionTransfer-Protocol.h"

@class NSMutableArray;

@interface MessageTransfer : NSObject <MessageDeletionTransfer>
{
    id _delegate;
    NSMutableArray *_operations;
    BOOL _deleteOriginals;
    BOOL _registeredForUndo;
    BOOL _allowsUndo;
    BOOL _isDeleteOperation;
    NSMutableArray *_todosAdded;
    NSMutableArray *_todosDeleted;
    NSMutableArray *_severedToDoProperties;
    BOOL _undoInProgress;
    BOOL _needToUndoTransfer;
}

+ (void)initialize;
+ (void)_undo:(id)fp8;
+ (void)_redo:(id)fp8;
+ (BOOL)shouldProceedWithMailboxDeletions:(id)fp8;
+ (void)queueMailboxDeletions:(id)fp8;
- (void)dealloc;
- (id)initWithMessages:(id)fp8 targetMailboxUid:(id)fp12 isDeleteOperation:(BOOL)fp16;
- (BOOL)canBeginTransfer;
- (void)beginTransfer;
- (void)_completedTransferWithError:(id)fp8;
- (void)clearMessageLinksForToDos:(id)fp8 addingToDoPropertiesToArray:(id)fp12;
- (void)restoreMessageLinksFromToDoProperties:(id)fp8;
- (void)_registerForUndoType:(int)fp8;
- (void)_undo;
- (void)_undoSettingFlags:(id)fp8 transferringMessages:(id)fp12;
- (void)_redo;
- (id)copyToDos:(id)fp8 destinationAccount:(id)fp12 makeUnique:(BOOL)fp16 newDocumentIDsByOld:(id)fp20;
- (void)deleteToDosForNotes:(id)fp8;
- (void)moveToDosForNotes:(id)fp8 destinationAccount:(id)fp12;
- (void)copyToDosForNotes:(id)fp8 newDocumentIDsByOld:(id)fp12 destinationAccount:(id)fp16;
- (void)clearToDoMessageLinks:(id)fp8;
- (void)handleToDosForOperation:(id)fp8 newDocumentIDsByOld:(id)fp12 missedMessages:(id)fp16;
- (void)postWillBeginDocumentTransferNotification:(id)fp8;
- (void)postDidEndDocumentTransferNotification:(id)fp8 result:(int)fp12 destinationAccount:(id)fp16 missedMessages:(id)fp20;
- (void)_synchronouslyPerformTransfer;
- (id)destinationMailboxes;
- (id)sourceStores;
- (id)_undoActionNameForMessageCount:(unsigned int)fp8;
- (BOOL)allowsUndo;
- (void)setAllowsUndo:(BOOL)fp8;
- (BOOL)deleteOriginals;
- (void)setDeleteOriginals:(BOOL)fp8;
- (id)delegate;
- (void)setDelegate:(id)fp8;

@end

