/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Message/MessageCriterion.h>

@interface MessageCriterion (PrivateLibraryAdditions)
- (id)fixOnceWithExpandedSmartMailboxes:(id)fp8;
- (id)criterionByMergingBodyCriteria;
- (BOOL)hasNumberCriterion;
- (BOOL)isExpressibleInTigerSchema;
- (id)SQLExpressionWithContext:(CDAnonymousStruct1 *)fp8 depth:(unsigned int)fp12 enclosingSmartMailboxes:(id)fp16;
@end

