/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class Message;

@interface MessageBody : NSObject
{
    Message *_message;
    unsigned int _messageID;
    BOOL _isMessageIDValid;
}

- (id)init;
- (void)setMessage:(id)fp8;
- (id)message;
- (id)attributedString;
- (BOOL)isHTML;
- (BOOL)isRich;
- (BOOL)isSignedByMe;
- (void)calculateNumberOfAttachmentsIfNeeded;
- (void)calculateNumberOfAttachmentsDecodeIfNeeded;
- (unsigned int)numberOfAttachmentsSigned:(char *)fp8 encrypted:(char *)fp12;
- (id)attachments;
- (id)attachmentFilenames;
- (id)textHtmlPart;
- (id)webArchive;
- (void)dealloc;
- (BOOL)isMessageIDValid;
- (void)setIsMessageIDValid:(BOOL)fp8;
- (id)actualMessage;
- (void)setActualMessage:(id)fp8;
- (unsigned int)messageID;
- (void)setMessageID:(unsigned int)fp8;

@end

