/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray;

@interface MetadataLogger : NSObject
{
    BOOL _logiCalToDoSync;
    BOOL _logStoresToDoSync;
    BOOL _logInternal;
    BOOL _logCommits;
    BOOL _logReconciler;
    NSArray *_logToDoActivityOnHost;
}

+ (id)sharedInstance;
- (id)init;
- (void)dealloc;
- (void)logToDos:(id)fp8;
- (void)logCalendars:(id)fp8;
- (void)addingToDos:(id)fp8 reflectToCalendarStore:(id)fp12;
- (void)deletingToDos:(id)fp8 reflectToCalendarStore:(id)fp12;
- (void)updatingToDos:(id)fp8 reflectToCalendarStore:(id)fp12;
- (void)commitAddingToDos:(id)fp8 reflectToCalendarStore:(id)fp12;
- (void)commitDeletingToDos:(id)fp8 reflectToCalendarStore:(id)fp12;
- (void)commitUpdatingToDos:(id)fp8 reflectToCalendarStore:(id)fp12;
- (void)toDosFromIMAP:(id)fp8;
- (void)toDosFromiCal:(id)fp8;
- (void)messageNotToDo:(id)fp8;
- (void)updatingToDoWithID:(id)fp8 newRemoteID:(id)fp12;
- (void)imapToDosToInsert:(id)fp8 imapToDosToUpdate:(id)fp12;
- (void)libraryToDoStore:(id)fp8 isAddingToDos:(id)fp12;
- (void)libraryToDoStore:(id)fp8 isUpdatingToDos:(id)fp12;
- (void)libraryToDoStore:(id)fp8 isDeletingToDos:(id)fp12;
- (void)libraryToDoIMAPStore:(id)fp8 isAddingToDos:(id)fp12;
- (void)libraryToDoIMAPStore:(id)fp8 isUpdatingToDos:(id)fp12;
- (void)libraryToDoIMAPStore:(id)fp8 isDeletingToDos:(id)fp12;
- (void)startingReconciliationForMailbox:(unsigned int)fp8 requester:(id)fp12;
- (void)finishedReconciliationForMailbox:(unsigned int)fp8 requester:(id)fp12;
- (void)storeWithID:(unsigned int)fp8 hasAdds:(id)fp12 updates:(id)fp16 deletes:(id)fp20;
- (void)cacheWithID:(unsigned int)fp8 hasAdds:(id)fp12 updates:(id)fp16 deletes:(id)fp20;
- (void)analyzerWorkingWithStoreSnapshot:(id)fp8 referenceSnapshot:(id)fp12 cacheSnapshot:(id)fp16;
- (void)aboutToAnalyzeDifferenceTable:(id)fp8;
- (void)processedDifferenceTableExpression:(id)fp8 result:(id)fp12;
- (void)calendarsFromiCal:(id)fp8;
- (void)addingCalendars:(id)fp8 reflectToCalendarStore:(id)fp12;
- (void)updatingCalendars:(id)fp8 reflectToCalendarStore:(id)fp12;
- (void)deletingCalendars:(id)fp8 reflectToCalendarStore:(id)fp12;
- (unsigned int)nextCommandNumber;

@end

