/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Message/MimeTextAttachment.h>

@interface MimeTextAttachment (ScriptingSupport)
- (id)appleScriptNameOfAttachment;
- (id)appleScriptMIMEType;
- (void)_loadFileWrapperForCommand:(id)fp8;
- (void)_finishSaveAttachmentCommand:(id)fp8;
- (id)handleSaveAttachmentCommand:(id)fp8;
- (id)appleScriptApproximateSize;
- (id)uniqueID;
- (id)objectSpecifier;
@end

