/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Message/NetworkController.h>

@interface NetworkController (Private)
- (void)_postNotification:(id)fp8;
- (void)_postNetworkChangeNotification:(id)fp8;
- (void)_triggerDialForHostname:(id)fp8;
- (void)_registerForNotificationKeys:(id)fp8 patterns:(id)fp12;
@end

