/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSDictionary.h"

@interface NSDictionary (Goodies)
- (BOOL)boolForKey:(id)fp8;
- (int)integerForKey:(id)fp8;
- (float)floatForKey:(id)fp8;
- (struct _NSSize)sizeForKey:(id)fp8;
- (id)objectForIntegerKey:(int)fp8;
@end

