/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@interface NSObject (ToDoAlarmsDelegate)
- (void)toDoAlarms:(id)fp8 alarmAdded:(id)fp12;
- (void)toDoAlarms:(id)fp8 alarmRemoved:(id)fp12;
- (void)toDoAlarms:(id)fp8 alarmUpdated:(id)fp12;
@end

