/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSString.h"

@interface NSString (MimeEnrichedReader)
+ (id)htmlStringFromMimeRichTextString:(id)fp8;
+ (id)htmlStringFromMimeEnrichedString:(id)fp8;
+ (id)stringFromMimeEnrichedString:(id)fp8;
@end

