/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSTextView.h"

@interface NSTextView (FindPanelSupport)
- (void)jumpToSelection:(id)fp8;
- (void)takeFindStringFromSelection:(id)fp8;
- (BOOL)findString:(id)fp8 options:(unsigned int)fp12;
- (BOOL)canReplace;
- (unsigned int)replaceString:(id)fp8 withString:(id)fp12 options:(unsigned int)fp16;
@end

