/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSUndoManager.h"

@interface NSUndoManager (ToDoUndoManager)
- (void)setValue:(id)fp8 forKey:(id)fp12 inToDo:(id)fp16;
- (void)setValue:(id)fp8 forKey:(id)fp12 inAlarm:(id)fp16;
- (void)addToDos:(id)fp8;
- (void)deleteToDos:(id)fp8;
- (void)addAlarm:(id)fp8 toAlarms:(id)fp12;
- (void)insertAlarm:(id)fp8 atIndex:(unsigned int)fp12 intoAlarms:(id)fp16;
- (void)removeAlarmAtIndex:(unsigned int)fp8 fromAlarms:(id)fp12;
- (void)removeAlarm:(id)fp8 fromAlarms:(id)fp12;
@end

