/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSUserDefaults.h"

@interface NSUserDefaults (MessageAdditions)
- (id)downloadDirectoryPath;
- (void)setDownloadDirectoryPath:(id)fp8;
- (id)autoDownloadDirectoryPath;
- (BOOL)junkMailTransitionHasBeenShown;
- (void)setJunkMailTransitionHasBeenShown:(BOOL)fp8;
- (int)junkMailDaysTillOfferingTransition;
- (void)setJunkMailDaysTillOfferingTransition:(int)fp8;
- (BOOL)junkMailTrustHeaders;
- (void)setJunkMailTrustHeaders:(BOOL)fp8;
- (int)junkMailBehavior;
- (void)setJunkMailBehavior:(int)fp8;
- (BOOL)junkMailEvaluationAfterRules;
- (void)setJunkMailEvaluationAfterRules:(BOOL)fp8;
- (double)autoSaveDelay;
- (double)autoSaveStoreDelay;
- (BOOL)autosaveWindows;
- (void)setAutosaveWindows:(BOOL)fp8;
- (BOOL)storeNotesInInboxIsDiscovered;
- (void)setStoreNotesInInboxIsDiscovered:(BOOL)fp8;
- (id)defaultNoteToDoAccount;
- (void)setDefaultNoteToDoAccount:(id)fp8;
- (id)defaultNoteAccount;
- (id)defaultToDoAccount;
- (BOOL)iPhoneHasBeenSynced;
- (BOOL)allowArrowKeyMainWindowFocusChange;
- (id)notePaperColor;
- (id)userNotePaperColor;
- (id)defaultNotePaperColor;
@end

