/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSButton, NSPanel, NSSecureTextField, NSTextField;

@interface PasswordPanel : NSObject
{
    NSPanel *_passwordPanel;
    NSSecureTextField *_passwordField;
    NSTextField *_passwordMessage;
    NSTextField *_passwordTitle;
    NSButton *_rememberPassword;
}

+ (id)passwordPanel;
- (void)dealloc;
- (id)init;
- (void)setTitle:(id)fp8;
- (void)setMessage:(id)fp8;
- (id)message;
- (id)promptModallyForPassword;
- (void)setCanRememberPassword:(BOOL)fp8;
- (BOOL)canRememberPassword;
- (void)setRememberPassword:(BOOL)fp8;
- (BOOL)rememberPassword;
- (void)passwordPanelOK:(id)fp8;
- (void)passwordPanelCancel:(id)fp8;
- (BOOL)control:(id)fp8 textView:(id)fp12 doCommandBySelector:(SEL)fp16;

@end

