/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "Quota.h"

@class NSButton, NSMutableArray, NSMutableAttributedString, NSMutableDictionary, NSPopUpButton, NSProgressIndicator, NSTableView, NSTextField;

@interface POPQuota : Quota
{
    NSPopUpButton *_showMessagesPopup;
    NSTextField *_usageField;
    NSTableView *_quotaTable;
    NSProgressIndicator *_progressIndicator;
    NSTextField *_progressField;
    NSButton *_deleteButton;
    NSMutableAttributedString *_truncatedString;
    NSMutableDictionary *_truncatedParagraphStyle;
    struct _QuotaSimpleSortDescriptor _simpleSortDescs[5];
    NSMutableArray *_messageIDs;
}

- (id)initWithPOPAccount:(id)fp8;
- (void)dealloc;
- (void)deleteFromServer:(id)fp8;
- (void)deleteMessagesSheetDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (BOOL)_shouldShowMessage:(id)fp8 showMessageType:(int)fp12;
- (id)_filterMessages:(id)fp8 showMessageType:(int)fp12;
- (void)_updateUsageField;
- (void)showMessagesPopupChanged:(id)fp8;
- (void)engineDidStart;
- (void)engineDidFinish;
- (void)updateProgress:(id)fp8;
- (void)engineUpdated:(id)fp8;
- (unsigned int)numberOfSortDescriptors;
- (const struct _QuotaSimpleSortDescriptor *)sortDescriptorAtIndex:(unsigned int)fp8;
- (int)numberOfRowsInTableView:(id)fp8;
- (id)_truncatedAttributedStringForString:(id)fp8;
- (id)tableView:(id)fp8 objectValueForTableColumn:(id)fp12 row:(int)fp16;
- (void)tableView:(id)fp8 willDisplayCell:(id)fp12 forTableColumn:(id)fp16 row:(int)fp20;
- (void)tableView:(id)fp8 sortDescriptorsDidChange:(id)fp12;
- (void)tableViewSelectionDidChange:(id)fp8;
- (void)_syncSortDescriptors;
- (void)_resortMessages;
- (int)_addMessage:(id)fp8;
- (BOOL)_updateMessage:(id)fp8;
- (void)_deleteServerMessagesStarted:(id)fp8;
- (void)_deleteServerMessagesCompleted:(id)fp8;

@end

