/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSImage, NSMutableDictionary;

@interface PresenceTracker : NSObject
{
    NSMutableDictionary *_emailToPerson;
    NSMutableDictionary *_abPersonToStatus;
    BOOL _isListening;
    NSImage *_availableStatusImage;
}

+ (id)sharedInstance;
+ (id)allocWithZone:(struct _NSZone *)fp8;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)retain;
- (unsigned int)retainCount;
- (void)release;
- (id)autorelease;
- (id)availableStatusImage;
- (id)init;
- (void)cacheInformationForABPerson:(id)fp8;
- (BOOL)personWithEmailIsOnline:(id)fp8;
- (id)addressCardUIDForEmail:(id)fp8;
- (void)clearCache;
- (void)clearOnlineStatus;
- (void)reloadCache;
- (void)updateStatusForABPerson:(id)fp8 withStatus:(id)fp12;
- (void)startListening;
- (void)stopListening;
- (void)imPersonStatusChangedNotification:(id)fp8;
- (void)imStatusImagesChangedAppearanceNotification:(id)fp8;
- (void)abDatabaseChangedExternallyNotification:(id)fp8;

@end

