/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSView.h"

@class NSLevelIndicator;

@interface QuotaBar : NSView
{
    NSLevelIndicator *_levelIndicator;
}

- (id)_labelFont;
- (id)initWithFrame:(struct _NSRect)fp8;
- (void)dealloc;
- (void)setQuotaUsed:(unsigned long long)fp8 limit:(unsigned long long)fp16;
- (void)drawRect:(struct _NSRect)fp8;
- (id)accessibilityAttributeNames;
- (id)accessibilityAttributeValue:(id)fp8;

@end

