/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Message/PlaceholderFileWrapper.h>

@class NSURL;

@interface RemotePlaceholderFileWrapper : PlaceholderFileWrapper
{
    NSURL *_url;
}

- (void)dealloc;
- (id)remoteAccessMimeType;
- (id)initWithURL:(id)fp8;
- (BOOL)isRemotelyAccessed;
- (id)symbolicLinkDestination;
- (id)URL;
- (unsigned int)approximateSize;

@end

