/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSPanel.h"

@class NSURLAuthenticationChallenge;

@interface RSSAuthenticationPanel : NSPanel
{
    id mainLabel;
    id panel;
    id password;
    id smallLabel;
    id username;
    id imageView;
    BOOL nibLoaded;
    BOOL usingSheet;
    id callback;
    id context;
    SEL selector;
    NSURLAuthenticationChallenge *challenge;
}

- (id)initWithCallback:(id)fp8 selector:(SEL)fp12 context:(id)fp16;
- (void)dealloc;
- (void)cancel:(id)fp8;
- (void)logIn:(id)fp8;
- (BOOL)loadNib;
- (void)setUpForChallenge:(id)fp8;
- (void)runAsModalDialogWithChallenge:(id)fp8;
- (void)runAsSheetOnWindow:(id)fp8 withChallenge:(id)fp12;
- (void)sheetDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;

@end

