/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSDate, NSDictionary, SafariBookmark;

@interface SafariBookmarksWatcher : NSObject
{
    Class _bookmarkClass;
    NSDate *_modDate;
    NSArray *_schemes;
    SafariBookmark *_root;
    NSDictionary *_uuids;
    NSDictionary *_urls;
}

- (id)initWithSchemes:(id)fp8;
- (void)dealloc;
- (void)setBookmarkClass:(Class)fp8;
- (id)tree;
- (id)bookmarkWithUUID:(id)fp8;
- (id)bookmarkWithURL:(id)fp8;
- (BOOL)_setRoot:(id)fp8;
- (BOOL)refresh;
- (BOOL)refreshFromBookmarks:(id)fp8;

@end

