/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSView.h"

@class NSButton, NSMutableArray, NSProgressIndicator;

@interface SearchSliceView : NSView
{
    NSButton *_saveButton;
    NSProgressIndicator *_progressIndicator;
    NSMutableArray *_fieldButtons;
    NSMutableArray *_targetButtons;
    unsigned int _layingOutItems:1;
    double _lastLayoutTime;
    BOOL _canContentSearchSelectedMailboxes;
    struct _NSPoint separatorOrigin;
    int _searchField;
    int _searchTarget;
    int _searchArea;
    id _delegate;
}

- (id)createSearchButton;
- (void)_addButtonForSearchField:(int)fp8 inArea:(int)fp12;
- (void)_addButtonForSearchTarget:(int)fp8;
- (void)_updateUIToReflectSearchArea;
- (void)_updateUIToReflectSearchTarget;
- (void)_updateUIToReflectSearchField;
- (id)typeButtonWithTag:(int)fp8;
- (void)_updateContentSearchButtonEnabledState;
- (void)_updateUI;
- (void)_layoutItems;
- (void)_addFieldButtonsForSearchArea:(int)fp8;
- (void)_setupView;
- (id)initWithFrame:(struct _NSRect)fp8 searchField:(int)fp24 searchTarget:(int)fp28 searchArea:(int)fp32;
- (id)initWithFrame:(struct _NSRect)fp8;
- (void)dealloc;
- (void)setDelegate:(id)fp8;
- (id)targetButtonWithTag:(int)fp8;
- (void)setCanSearchSelectedMailbox:(BOOL)fp8;
- (void)setCanContentSearchSelectedMailboxes:(BOOL)fp8;
- (void)setSearchTarget:(int)fp8;
- (void)setSearchField:(int)fp8;
- (void)startProgressAnimation;
- (void)stopProgressAnimation;
- (void)setCanSaveSearch:(BOOL)fp8;
- (void)drawRect:(struct _NSRect)fp8;
- (void)searchFieldButtonAction:(id)fp8;
- (void)searchTargetButtonAction:(id)fp8;
- (void)saveButtonAction:(id)fp8;
- (void)setFrame:(struct _NSRect)fp8;
- (void)viewWillStartLiveResize;
- (void)viewDidEndLiveResize;
- (BOOL)_anySearchMailboxesAreCached;
- (id)delegate;
- (int)searchArea;
- (void)setSearchArea:(int)fp8;
- (int)searchTarget;
- (int)searchField;

@end

