/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSManagedObjectContext;

@interface SeenMessagesManager : NSObject
{
    NSManagedObjectContext *_managedObjectContext;
    id _account;
}

- (id)initWithAccountID:(id)fp8 createAccount:(BOOL)fp12;
- (void)dealloc;
- (id)_accountForAccountID:(id)fp8;
- (id)_addAccountWithID:(id)fp8;
- (id)seenMessageForMessageID:(id)fp8;
- (unsigned int)countOfSeenMessages;
- (id)addMessageID:(id)fp8 dateSeen:(id)fp12;
- (void)removeMessageIDs:(id)fp8;
- (id)seenMessages;
- (id)messagesToBeDeletedFromServer;
- (void)removeServerDeletedMessages;
- (void)removeMessagesNotOnServer:(id)fp8;
- (void)saveChanges;
- (void)_configureManagedObjectContext;
- (id)managedObjectContext;
- (void)setManagedObjectContext:(id)fp8;
- (id)account;
- (void)setAccount:(id)fp8;

@end

