/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Message/DeliveryAccount.h>

@class NSTimer, SMTPConnection;

@interface SMTPAccount : DeliveryAccount
{
    SMTPConnection *_connection;
    NSTimer *_timer;
    int _lastTimerSetTime;
    unsigned int _lastUsedPort;
}

+ (id)accountTypeString;
+ (id)newDefaultInstance;
- (Class)deliveryClass;
- (unsigned int)defaultPortNumber;
- (id)serviceName;
- (id)saslProfileName;
- (unsigned int)secondaryDefaultPortNumber;
- (unsigned int)tertiaryDefaultPortNumber;
- (BOOL)_portNumberIsADefaultPortNumber;
- (unsigned int)portNumber;
- (void)setPortNumber:(unsigned int)fp8;
- (BOOL)shouldTryDefaultPorts;
- (void)setShouldTryDefaultPorts:(BOOL)fp8;
- (Class)connectionClass;
- (id)preferredAuthScheme;
- (void)setPreferredAuthScheme:(id)fp8;
- (void)_setStandardPortsConnectionErrorMessage;
- (id)createConnectedConnection;
- (id)authenticatedConnection;
- (void)checkInConnection:(id)fp8;
- (void)setTimer;
- (void)connectionExpired:(id)fp8;
- (void)disconnect:(id)fp8;
- (BOOL)_shouldTryDirectSSLConnectionOnPort:(unsigned int)fp8;
- (void)releaseAllConnections;
- (void)setPasswordInKeychain:(id)fp8;
- (id)passwordFromKeychain;
- (BOOL)isEqual:(id)fp8;
- (unsigned int)hash;
- (void)dealloc;
- (void)finalize;

@end

