/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class ComposeBackEnd, EditableWebMessageDocument, NSMutableArray, NSMutableDictionary, NSString, NSTimer, Stationery, WebView;

@interface StationeryController : NSObject
{
    Stationery *stationery;
    BOOL isStationeryLoaded;
    NSString *currentColor;
    float letterTopMargin;
    float letterWidth;
    id savedResourceLoadDelegate;
    id savedFrameLoadDelegate;
    int numberOfResourcesNotYetLoaded;
    BOOL isLoadingStationery;
    BOOL isChangingStationeryColor;
    BOOL isLoadingResources;
    BOOL shouldAnimateTransitions;
    WebView *webView;
    ComposeBackEnd *composeBackEnd;
    EditableWebMessageDocument *messageDocument;
    NSMutableDictionary *fontElementsWithColors;
    NSMutableArray *colorsThatHaveBeenDisplayed;
    NSTimer *flushWindowTimer;
}

- (void)dealloc;
- (BOOL)isUpdatingWebView;
- (void)setComposeBackEnd:(id)fp8;
- (void)setWebView:(id)fp8;
- (id)stationery;
- (void)setStationery:(id)fp8;
- (BOOL)isStationeryLoaded;
- (void)setStationeryIsLoaded:(BOOL)fp8;
- (id)color;
- (void)setColor:(id)fp8;
- (void)showColorOptions;
- (void)loadStationery:(id)fp8;
- (void)webView:(id)fp8 didFinishLoadForFrame:(id)fp12;
- (void)finishLoadingStationery;
- (void)webView:(id)fp8 didFailLoadWithError:(id)fp12 forFrame:(id)fp16;
- (id)webView:(id)fp8 identifierForInitialRequest:(id)fp12 fromDataSource:(id)fp16;
- (void)webView:(id)fp8 resource:(id)fp12 didFinishLoadingFromDataSource:(id)fp16;
- (void)webView:(id)fp8 didLoadResourceFromMemoryCache:(id)fp12 response:(id)fp16 length:(int)fp20 fromDataSource:(id)fp24;
- (void)timerDidFire:(id)fp8;
- (void)webViewDidFinishLoadingAllResources;
- (void)userClickedOnStationeryBackground:(id)fp8;
- (void)changeStationeryColor:(id)fp8;
- (id)mimeBodyForAttachmentWithURL:(id)fp8;
- (id)stationeryFromCurrentMessageError:(id *)fp8;

@end

