/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "GenericAttachmentFetcher.h"

@class NSString;

@interface TemporaryAttachmentOpener : GenericAttachmentFetcher
{
    NSString *_applicationPath;
}

- (id)initWithAttachments:(id)fp8 applicationPath:(id)fp12;
- (void)dealloc;
- (void)downloadedAllAttachments;
- (void)_openAttachmentAtPath:(id)fp8;
- (void)didSaveAttachment:(id)fp8 toPath:(id)fp12;
- (double)temporaryFolderTimeout;

@end

