/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCopying-Protocol.h"

@class CalTask, NSData, NSDate, NSMutableArray, NSString, NSURL, ToDoAlarms, ToDoCalendar;

@interface ToDo : NSObject <NSCopying>
{
    BOOL _dueDateEnabled;
    NSDate *_dueDate;
    BOOL _completed;
    NSDate *_dateCompleted;
    ToDoAlarms *_alarms;
    BOOL _priorityEnabled;
    int _priority;
    ToDoCalendar *_calendar;
    NSString *_calendarID;
    NSString *_calendarTitle;
    NSString *_title;
    NSString *_notes;
    NSURL *_url;
    NSString *_todoID;
    NSString *_previousToDoID;
    NSData *_referencedTextLocation;
    NSString *_documentID;
    NSData *_referencedMessageID;
    NSDate *_dateCreated;
    NSData *_unrecognizedData;
    NSDate *_dateStamp;
    BOOL _hasChanged;
    int _changedProperties;
    CalTask *_calTask;
    NSMutableArray *_keysDigest;
}

+ (id)decodeMailitemURI:(id)fp8;
- (id)initWithGUID:(id)fp8 dueDate:(id)fp12 priority:(int)fp16 calendar:(id)fp20;
- (id)init;
- (id)initWithTitle:(id)fp8;
- (int)todoAlarmPriority:(unsigned int)fp8;
- (unsigned int)calAlarmPriority:(int)fp8;
- (id)initWithCalTask:(id)fp8;
- (id)calTaskFromToDo;
- (void)updateNonCalTaskInformationFrom:(id)fp8;
- (void)updateWithCalTask:(id)fp8;
- (void)dealloc;
- (id)initWithData:(id)fp8;
- (id)data;
- (BOOL)isEquivalentToCalTask:(id)fp8;
- (BOOL)isIdenticalTo:(id)fp8;
- (BOOL)isEquivalentTo:(id)fp8;
- (void)_todoChangedProperties:(unsigned int)fp8;
- (void)postToDoInfoChangedNotification:(unsigned int)fp8;
- (int)changedProperties;
- (id)todoID;
- (void)setToDoID:(id)fp8;
- (id)previousToDoID;
- (void)setPreviousToDoID:(id)fp8;
- (BOOL)hasChanged;
- (void)setHasNotChanged;
- (BOOL)hasMessageReference;
- (id)messageReference;
- (id)documentID;
- (void)setDocumentID:(id)fp8;
- (id)documentUUID;
- (id)referencedMessageID;
- (void)setReferencedMessageID:(id)fp8;
- (id)referencedTextLocation;
- (void)setReferencedTextLocation:(id)fp8;
- (BOOL)overdue;
- (BOOL)dueDateEnabled;
- (void)setDueDateEnabled:(BOOL)fp8;
- (id)dueDate;
- (void)setDueDate:(id)fp8;
- (id)effectiveDueDate;
- (BOOL)completed;
- (void)setCompleted:(BOOL)fp8;
- (int)effectiveCompleteState;
- (id)dateCompleted;
- (void)setDateCompleted:(id)fp8;
- (id)dateCreated;
- (void)setDateCreated:(id)fp8;
- (id)dateStamp;
- (void)setDateStamp:(id)fp8;
- (id)alarms;
- (int)numberOfAlarms;
- (void)setAlarms:(id)fp8;
- (BOOL)priorityEnabled;
- (void)setPriorityEnabled:(BOOL)fp8;
- (int)priority;
- (void)setPriority:(int)fp8;
- (int)effectivePriority;
- (id)calendar;
- (void)setCalendar:(id)fp8;
- (void)setCalendarUsingID:(id)fp8;
- (void)calendarUpdated:(id)fp8;
- (id)title;
- (void)setTitle:(id)fp8;
- (id)notes;
- (void)setNotes:(id)fp8;
- (BOOL)notesHaveChanged;
- (id)url;
- (void)setUrl:(id)fp8;
- (id)unrecognizedData;
- (void)setUnrecognizedData:(id)fp8;
- (BOOL)isEditable;
- (void)prepareToAddAgain;
- (void)mergeFromToDo:(id)fp8 overwriteDirtyProperties:(BOOL)fp12 usingCondition:(void *)fp16;
- (id)description;
- (id)shortDescription;
- (id)richDescription;
- (id)account;
- (id)todoStore;
- (void)buildSetOfRecognizedKeys;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (BOOL)isUnique;
- (void)unique;
- (void)clearMessageLinks;
- (id)mailitemURIWithReferences:(BOOL)fp8;
- (void)toDoAlarms:(id)fp8 alarmAdded:(id)fp12;
- (void)toDoAlarms:(id)fp8 alarmRemoved:(id)fp12;
- (void)toDoAlarms:(id)fp8 alarmUpdated:(id)fp12;
- (id)calTask;
- (void)setCalTask:(id)fp8;
- (id)calendarTitle;
- (id)calendarID;
- (void)postNotificationName:(id)fp8 userInfo:(id)fp12 onCenter:(id)fp16;
- (id)uniqueID;
- (id)changedPropertiesBitField;
- (void)setChangedPropertiesBitField:(id)fp8;
- (id)copyWithZone:(struct _NSZone *)fp8;

@end

