/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class ToDoUIDRemoteIDPair;

@interface ToDoDifferenceExpression : NSObject
{
    ToDoUIDRemoteIDPair *_storeDifference;
    int _storeDifferenceType;
    ToDoUIDRemoteIDPair *_cacheDifference;
    int _cacheDifferenceType;
    BOOL _avoidAsserts;
}

- (id)init;
- (void)dealloc;
- (id)storeDifference;
- (void)setStoreDifference:(id)fp8 type:(int)fp12;
- (id)cacheDifference;
- (void)setCacheDifference:(id)fp8 type:(int)fp12;
- (id)generateResult;
- (id)generateForcedStoreResult;
- (id)generateForcedCacheResult;
- (int)resolveConflictForStoreAgent:(id)fp8 cacheAgent:(id)fp12 mailboxID:(unsigned int)fp16;
- (id)description;
- (void)setAvoidAsserts:(BOOL)fp8;
- (void)handleInvalidResult:(id)fp8;

@end

