/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSDatePicker.h"

@interface ToDoDatePicker : NSDatePicker
{
}

- (void)awakeFromNib;
- (void)setFrame:(struct _NSRect)fp8;
- (void)setFrameSize:(struct _NSSize)fp8;
- (void)setBounds:(struct _NSRect)fp8;
- (void)setBoundsSize:(struct _NSSize)fp8;

@end

