/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSDateFormatter.h"

@interface ToDoDateFormatter : NSDateFormatter
{
    unsigned int _dateStyle;
    BOOL shouldUseRelativeDate;
}

+ (int)dayInterval:(id)fp8;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (BOOL)shouldUseRelativeDate;
- (void)setShouldUseRelativeDate:(BOOL)fp8;
- (unsigned int)timeStyle;
- (void)setTimeStyle:(unsigned int)fp8;
- (id)stringFromDate:(id)fp8;
- (id)dateFromString:(id)fp8;
- (float)widthOfDate:(id)fp8 withAttributes:(id)fp12;
- (float)widthOfLongestDateStringWithAttributes:(id)fp8;
- (id)stringForObjectValue:(id)fp8;
- (id)attributedStringForObjectValue:(id)fp8 withDefaultAttributes:(id)fp12;
- (id)editingStringForObjectValue:(id)fp8;
- (BOOL)getObjectValue:(id *)fp8 forString:(id)fp12 errorDescription:(id *)fp16;

@end

