/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary, NSRecursiveLock;

@interface ToDosCache : NSObject
{
    NSMutableDictionary *_todosByGUID;
    NSMutableDictionary *_deletedToDoIDsByDocumentID;
    BOOL _checkConsistency;
    Class _libraryClass;
    NSRecursiveLock *_lock;
    NSMutableArray *_listeners;
    id <CalendarStoreConduit> _calendarStoreConduit;
}

- (id)initWithLibraryClass:(Class)fp8 checkingConsistency:(BOOL)fp12;
- (void)dealloc;
- (void)addListener:(id)fp8;
- (void)removeListener:(id)fp8;
- (void)addToDo:(id)fp8;
- (void)updateToDo:(id)fp8;
- (void)removeToDo:(id)fp8;
- (id)cachedToDoWithID:(id)fp8;
- (id)todoWithID:(id)fp8;
- (id)todoWithPreviousID:(id)fp8;
- (BOOL)hasToDoWithIDBeenDeleted:(id)fp8;
- (id)allDeletedToDoIDsForDocumentID:(id)fp8;
- (id)libraryToDoFromCalTask:(id)fp8;
- (id)libraryToDoFromNewCalTask:(id)fp8;
- (id)allToDosForMailboxID:(unsigned int)fp8;
- (id)loadAndCacheToDosInDisabledAccount:(id)fp8;
- (id)todosByIDForDocumentID:(id)fp8 byPreviousID:(id *)fp12;
- (id)allToDosForDocumentID:(id)fp8;
- (id)allToDosForMessage:(id)fp8;
- (id)lastToDoWithID:(id)fp8 inMailbox:(id)fp12;
- (id)allToDosInActiveAccounts;
- (id)listOfToDoIDsInCalendarWithID:(id)fp8;
- (id)todosMatchingCriterion:(id)fp8;
- (id)todosInActiveAccountsMatchingCriterion:(id)fp8;

@end

