/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSPopUpButtonCell.h"

@interface ToDoPopUpButtonCell : NSPopUpButtonCell
{
}

- (id)_originalPopupImage;
- (id)_tintedPopupImage;
- (id)_popupImage;
- (id)_enabledTextColor;
- (id)_disabledTextColor;
- (id)initWithMenu:(id)fp8 andCell:(id)fp12;
- (float)leadingSpace;
- (struct _NSRect)titleRectForBounds:(struct _NSRect)fp8;
- (struct _NSSize)cellSize;
- (struct _NSRect)imageRectForBounds:(struct _NSRect)fp8;
- (void)drawInteriorWithFrame:(struct _NSRect)fp8 inView:(id)fp24;
- (void)drawTitleWithFrame:(struct _NSRect)fp8 inView:(id)fp24;

@end

