/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, NSMutableSet;

@interface ToDoMall : NSObject
{
    NSMutableArray *_toDoStores;
    NSMutableArray *_toDoList;
    NSMutableArray *_sortDescriptors;
    NSMutableSet *_toDoIDs;
    id _delegate;
    BOOL _delegateRespondsToListContentsWillCompletelyChange;
    BOOL _delegateRespondsToListContentsCompletelyChanged;
    BOOL _delegateRespondsToListWasSorted;
    BOOL _delegateRespondsToAddedAtIndex;
    BOOL _delegateRespondsToDeletedAtIndex;
    BOOL _delegateRespondsToUpdatedAtIndex;
}

- (id)init;
- (void)dealloc;
- (void)setMailboxUids:(id)fp8;
- (id)sortDescriptors;
- (void)setSortDescriptors:(id)fp8;
- (unsigned int)count;
- (unsigned int)incompleteCount;
- (id)toDoAtIndex:(unsigned int)fp8;
- (unsigned int)indexOfToDo:(id)fp8;
- (id)indexesOfToDos:(id)fp8;
- (id)toDosAtIndexes:(id)fp8;
- (void)addToDos:(id)fp8;
- (void)deleteToDos:(id)fp8;
- (id)delegate;
- (void)setDelegate:(id)fp8;
- (void)searchForString:(id)fp8 in:(int)fp12 withSelectedMailboxes:(id)fp16 withOptions:(int)fp20;
- (id)criterionForString:(id)fp8 in:(int)fp12 withSelectedMailboxes:(id)fp16 withOptions:(int)fp20 breakWords:(BOOL)fp24;
- (void)reallySearchForString:(id)fp8 in:(int)fp12 withSelectedMailboxes:(id)fp16 withOptions:(int)fp20;
- (void)clearSearchResults;

@end

