/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class CalGroup, MailAccount, NSString;

@interface ToDoCalendarGroup : NSObject
{
    MailAccount *_account;
    NSString *_groupID;
    NSString *_title;
    int _type;
    CalGroup *_calGroup;
}

- (id)initIMAPGroupWithTitle:(id)fp8 groupID:(id)fp12 account:(id)fp16;
- (id)initWithCalGroup:(id)fp8;
- (void)dealloc;
- (id)calGroupFromToDoCalendarGroup;
- (void)updateWithCalGroup:(id)fp8;
- (BOOL)isIdenticalToCalGroup:(id)fp8;
- (id)title;
- (void)setTitle:(id)fp8;
- (id)groupID;
- (void)setGroupID:(id)fp8;
- (id)account;
- (int)type;
- (void)setType:(int)fp8;
- (int)typeFromCalGroupType:(id)fp8;
- (void)setTypeFromCalGroupType:(id)fp8;
- (id)calGroupType;
- (id)calGroup;
- (void)setCalGroup:(id)fp8;
- (id)description;
- (id)shortDescription;

@end

