/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCopying-Protocol.h"

@class CalCalendar, MailAccount, NSColor, NSString, NSURL;

@interface ToDoCalendar : NSObject <NSCopying>
{
    NSString *_calendarID;
    NSString *_title;
    NSColor *_color;
    BOOL _editable;
    NSURL *_url;
    MailAccount *_account;
    int _type;
    NSString *_groupID;
    CalCalendar *_calCalendar;
    BOOL _hasChanged;
    int _changedProperties;
}

- (id)initWithCalCalendar:(id)fp8 account:(id)fp12;
- (id)calCalendarFromToDoCalendar;
- (void)updateWithCalCalendar:(id)fp8;
- (void)dealloc;
- (BOOL)isIdenticalToCalCalendar:(id)fp8;
- (int)changedProperties;
- (id)title;
- (void)setTitle:(id)fp8;
- (id)color;
- (void)setColor:(id)fp8;
- (BOOL)isEditable;
- (void)setEditable:(BOOL)fp8;
- (int)type;
- (void)setType:(int)fp8;
- (int)typeFromCalCalendarType:(id)fp8;
- (void)setTypeFromCalCalendarType:(id)fp8;
- (id)calCalendarType;
- (id)calendarID;
- (void)setCalendarID:(id)fp8;
- (id)url;
- (void)setUrl:(id)fp8;
- (BOOL)hasChanged;
- (void)setHasNotChanged;
- (id)description;
- (id)shortDescription;
- (int)compare:(id)fp8;
- (id)initWithData:(id)fp8;
- (id)data;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (id)calCalendar;
- (void)setCalCalendar:(id)fp8;
- (id)account;
- (void)mergeIn:(id)fp8;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)groupID;
- (void)setGroupID:(id)fp8;

@end

