/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSViewTextAttachmentCell.h"

@class NSView;

@interface ViewTextAttachmentCell : NSViewTextAttachmentCell
{
    NSView *_view;
    NSView *_containingView;
    struct _NSSize _viewSize;
}

- (void)_viewFrameChanged;
- (void)_viewFrameChanged:(id)fp8;
- (id)initWithView:(id)fp8;
- (id)controlView;
- (void)setControlView:(id)fp8;
- (id)view;
- (id)viewWithFrame:(struct _NSRect)fp8 forView:(id)fp24 characterIndex:(unsigned int)fp28 layoutManager:(id)fp32;
- (struct _NSSize)cellSize;
- (void)releaseView:(id)fp8;
- (void)dealloc;

@end

