/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol WebHTMLHighlighter
- (struct _NSRect)highlightRectForLine:(struct _NSRect)fp8 representedNode:(id)fp24;
- (void)paintHighlightForBox:(struct _NSRect)fp8 onLine:(struct _NSRect)fp24 behindText:(BOOL)fp40 entireLine:(BOOL)fp44 representedNode:(id)fp48;
- (struct _NSRect)highlightRectForLine:(struct _NSRect)fp8;
- (void)paintHighlightForBox:(struct _NSRect)fp8 onLine:(struct _NSRect)fp24 behindText:(BOOL)fp40 entireLine:(BOOL)fp44;
@end

