/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WebMessageController.h"

#import "MessageContentDisplay-Protocol.h"

@class ActivityMonitor, MessageViewingState, NSInvocation;

@interface WebMessageDisplay : WebMessageController <MessageContentDisplay>
{
    NSInvocation *_displayChangedInvocation;
    ActivityMonitor *urlificationMonitor;
    float _textSizeMultiplier;
    MessageViewingState *_viewingState;
}

+ (void)initialize;
+ (id)copyDocumentForMessage:(id)fp8 viewingState:(id)fp12;
+ (Class)documentClass;
+ (id)webResourcesForAttachments:(id)fp8 urls:(id)fp12;
- (id)initWithDocument:(id)fp8;
- (void)dealloc;
- (id)contentView;
- (id)textView;
- (void)documentResized;
- (void)display:(id)fp8 inContainerView:(id)fp12 replacingView:(id)fp16 invokeWhenDisplayChanged:(id)fp20;
- (void)prepareToRemoveView;
- (void)invalidateViewingState;
- (BOOL)isOkayToDownloadAttachment:(id)fp8;
- (void)attachmentFinishedDownloading:(id)fp8;
- (void)highlightSearchText:(id)fp8;
- (void)setSelectedTextRepresentation:(id)fp8;
- (id)selectedTextRepresentation;
- (id)selectedText;
- (id)selectedWebArchive;
- (id)attachmentsInSelection;
- (id)webArchiveBaseURL:(id *)fp8;
- (void)adjustFontSizeBy:(int)fp8 viewingState:(id)fp12;
- (id)findTarget;
- (struct __CFDictionary *)stringsForURLification;
- (void)updateURLMatches:(id)fp8 viewingState:(id)fp12;
- (void)detectDataInMessage:(id)fp8 usingContext:(id)fp12;
- (BOOL)scrollVerticallyBy:(float)fp8;
- (float)verticalPageScrollDistance;
- (BOOL)scrollHorizontallyBy:(float)fp8;
- (void)webView:(id)fp8 didWriteSelectionToPasteboard:(id)fp12;
- (void)webView:(id)fp8 didCommitLoadForFrame:(id)fp12;
- (void)webView:(id)fp8 didFinishLoadForFrame:(id)fp12;
- (void)_setDisplayChangedInvocation:(id)fp8;
- (id)delegate;
- (void)setDelegate:(id)fp8;

@end

