/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class MimeBody, MimePart, NSData, NSDictionary, NSMutableDictionary, NSURL, WebArchive;

@interface WebMessageDocument : NSObject
{
    NSDictionary *_partsByURL;
    NSMutableDictionary *_attachmentsByURL;
    NSMutableDictionary *backgroundImageAttachments;
    NSURL *_baseURL;
    MimeBody *_mimeBody;
    MimePart *_htmlPart;
    NSData *_htmlData;
    WebArchive *_webArchive;
    unsigned int _preferredCharset;
    unsigned int _uniqueId:30;
    unsigned int _shouldDownloadRemoteURLs:1;
    unsigned int _containsRemoteContent:1;
    BOOL _messageIsFromMicrosoft;
}

+ (id)openDocuments;
+ (id)invalidBaseURL;
+ (void)document:(id *)fp8 attachment:(id *)fp12 forURL:(id)fp16;
+ (id)documentWithUniqueIdentifier:(unsigned int)fp8;
- (void)dealloc;
- (void)finalize;
- (id)init;
- (id)initWithMimeBody:(id)fp8;
- (id)initWithMimePart:(id)fp8;
- (void)grabAttachmentsFromArchive;
- (id)mimePartForURL:(id)fp8;
- (id)attachmentForURL:(id)fp8;
- (void)addAttachment:(id)fp8 forURL:(id)fp12;
- (BOOL)hasAttachment:(id)fp8;
- (id)userAttachments;
- (BOOL)hasAttachments;
- (id)attachments;
- (id)mimeBody;
- (id)baseURL;
- (void)setPreferredEncoding:(unsigned long)fp8;
- (id)preferredCharacterSet;
- (unsigned int)uniqueIdentifier;
- (id)htmlData;
- (id)webArchive;
- (id)fileWrapper;
- (void)setShouldDownloadRemoteURLs:(BOOL)fp8;
- (BOOL)shouldDownloadRemoteURLs;
- (void)setContainsRemoteContent:(BOOL)fp8;
- (BOOL)containsRemoteContent;
- (void)setMessageIsFromMicrosoft:(BOOL)fp8;
- (BOOL)messageIsFromMicrosoft;

@end

